Repository OCA/pos, pull requests merged in 2018-04, with the labels that each got.

#196 [FIX] pos_payment_terminal : fixes currencies with decimals <>2
  pos_payment_terminal/static/src/js/pos_payment_terminal.js
Labels: needs fixing, needs review

#268 [10][ADD] pos_fix_search_limit
  pos_fix_search_limit/README.rst
  pos_fix_search_limit/__init__.py
  pos_fix_search_limit/__manifest__.py
  pos_fix_search_limit/static/src/js/pos_fix_search_limit.js
  pos_fix_search_limit/views/pos_fix_limit.xml
Labels: needs review

#117 [ADD] 9.0 pos return
  pos_return_order/README.rst
  pos_return_order/__init__.py
  pos_return_order/__openerp__.py
  pos_return_order/demo/product_product.xml
  pos_return_order/i18n/fr.po
  pos_return_order/models/__init__.py
  pos_return_order/models/pos_order.py
  pos_return_order/models/pos_order_line.py
  pos_return_order/models/pos_partial_return_wizard.py
  pos_return_order/models/pos_partial_return_wizard_line.py
  pos_return_order/models/product_template.py
  pos_return_order/static/description/icon.png
  pos_return_order/static/description/initial_pos_order_required.png
  pos_return_order/static/description/partial_return_wizard.png
  pos_return_order/static/description/product_returnable_bottle.png
  pos_return_order/static/description/returned_qty_over_initial.png
  pos_return_order/static/description/sum_returned_qty_over_initial.png
  pos_return_order/static/img/product_returnable_bottle-image.jpg
  pos_return_order/views/action.xml
  pos_return_order/views/pos_order_line_view.xml
  pos_return_order/views/pos_order_view.xml
  pos_return_order/views/pos_partial_return_wizard_view.xml
  pos_return_order/views/product_product_view.xml
Labels: needs review

#254 [10][FIX] Protect crash at runtime if oca-decorator not installed
  pos_pricelist/__init__.py
  pos_pricelist/models/pos_config.py
Labels: needs review

#142 [FIX][8.0] travis: Update travis file to new standard
  .travis.yml
  hw_customer_display/controllers/main.py
  hw_telium_payment_terminal/controllers/main.py
  pos_order_to_sale_order/models/sale_order.py
  requirements.txt
Labels: help wanted, work in progress
