Repository OCA/pos, pull requests merged in 2018-11, with the labels that each got.

#306 [10][FIX] pos_backend_partner css in tree view.
  pos_backend_partner/__manifest__.py
  pos_backend_partner/static/src/css/pos_backend_partner.css
Labels: approved

#307 [ADD][pos_config_show_accounting] POS Config Show Accounting
  pos_config_show_accounting/__init__.py
  pos_config_show_accounting/__manifest__.py
  pos_config_show_accounting/models/__init__.py
  pos_config_show_accounting/models/pos_config.py
  pos_config_show_accounting/readme/CONTRIBUTORS.rst
  pos_config_show_accounting/readme/DESCRIPTION.rst
  pos_config_show_accounting/readme/USAGE.rst
  pos_config_show_accounting/static/description/icon.png
  pos_config_show_accounting/tests/__init__.py
  pos_config_show_accounting/tests/test_pos_config_show_accounting.py
Labels: approved, ready to merge

#311 [FIX] pos_pricelist do not load unexisting field #131
  pos_pricelist/static/src/js/models.js
Labels: approved, needs review
