Repository OCA/pos, pull requests merged in 2019-11, with the labels that each got.

#402 [FIX] pos_order_mgmt: Xml receipt renders different values
  pos_order_mgmt/static/src/js/widgets.js
Labels: approved, ready to merge

#390 [FIX][8.0] hw_telium_payment_terminal - python3 syntax to prepare migration
  hw_telium_payment_terminal/controllers/main.py
  hw_telium_payment_terminal/test-scripts/telium-test.py
Labels: approved, needs review

#324 [FIX] Bug on pos_access_right: black screen when opening POS
  pos_access_right/static/src/js/pos_access_right.js
Labels: 9.0, needs review

#345 [FIX] pos_product_template was incombatible with the pos_cache module…
  pos_product_template/static/src/js/ppt.js
Labels: 10.0, needs review

#417 [FIX] pos_order_mgmt: Xml receipt renders different values
  pos_order_mgmt/static/src/js/widgets.js
Labels: approved
