Repository OCA/pos, pull requests merged in 2019-03, with the labels that each got.

#300 [MIG] pos_ticket_logo: Migration to 11.0
  pos_ticket_logo/README.rst
  pos_ticket_logo/__init__.py
  pos_ticket_logo/__manifest__.py
  pos_ticket_logo/readme/CONFIGURE.rst
  pos_ticket_logo/readme/CONTRIBUTORS.rst
  pos_ticket_logo/readme/DESCRIPTION.rst
  pos_ticket_logo/readme/USAGE.rst
  pos_ticket_logo/static/description/icon.png
  pos_ticket_logo/static/src/js/models.js
  pos_ticket_logo/static/src/xml/pos.xml
  pos_ticket_logo/templates/assets.xml
Labels: approved, needs review

#325 [MIG] pos_payment_entries_globalization: Migration to 11.0
  pos_payment_entries_globalization/README.rst
  pos_payment_entries_globalization/__init__.py
  pos_payment_entries_globalization/__manifest__.py
  pos_payment_entries_globalization/i18n/es.po
  pos_payment_entries_globalization/i18n/pos_payment_entries_globalization.pot
  pos_payment_entries_globalization/models/__init__.py
  pos_payment_entries_globalization/models/account_journal.py
  pos_payment_entries_globalization/models/pos_session.py
  pos_payment_entries_globalization/readme/CONFIGURE.rst
  pos_payment_entries_globalization/readme/CONTRIBUTORS.rst
  pos_payment_entries_globalization/readme/DESCRIPTION.rst
  pos_payment_entries_globalization/readme/USAGE.rst
  pos_payment_entries_globalization/static/description/icon.png
  pos_payment_entries_globalization/tests/__init__.py
  pos_payment_entries_globalization/tests/test_pos_payment_entries_globalization.py
  pos_payment_entries_globalization/views/account_journal_view.xml
Labels: approved, needs review, ready to merge

#335 [MIG] 12.0 pos_ticket_logo
  pos_ticket_logo/README.rst
  pos_ticket_logo/__init__.py
  pos_ticket_logo/__manifest__.py
  pos_ticket_logo/i18n/pos_ticket_logo.pot
  pos_ticket_logo/readme/CONFIGURE.rst
  pos_ticket_logo/readme/CONTRIBUTORS.rst
  pos_ticket_logo/readme/DESCRIPTION.rst
  pos_ticket_logo/readme/USAGE.rst
  pos_ticket_logo/static/description/icon.png
  pos_ticket_logo/static/description/index.html
  pos_ticket_logo/static/src/js/models.js
  pos_ticket_logo/static/src/xml/pos.xml
  pos_ticket_logo/templates/assets.xml
Labels: approved
