Repository OCA/pos, pull requests merged in 2020-02, with the labels that each got.

#459 [12.0][ADD] pos_ticket_partner_firstname
  pos_ticket_salesman_firstname/__init__.py
  pos_ticket_salesman_firstname/__manifest__.py
  pos_ticket_salesman_firstname/models/__init__.py
  pos_ticket_salesman_firstname/models/pos_config.py
  pos_ticket_salesman_firstname/readme/CONFIGURE.rst
  pos_ticket_salesman_firstname/readme/CONTRIBUTORS.rst
  pos_ticket_salesman_firstname/readme/DESCRIPTION.rst
  pos_ticket_salesman_firstname/readme/USAGE.rst
  pos_ticket_salesman_firstname/static/description/icon.png
  pos_ticket_salesman_firstname/static/description/receipt.png
  pos_ticket_salesman_firstname/static/src/js/models.js
  pos_ticket_salesman_firstname/static/src/xml/pos.xml
  pos_ticket_salesman_firstname/views/assets.xml
  pos_ticket_salesman_firstname/views/pos_config.xml
Labels: approved

#453 [MIG][12.0] pos_empty_home
  pos_empty_home/__init__.py
  pos_empty_home/__manifest__.py
  pos_empty_home/i18n/ca.po
  pos_empty_home/i18n/fr.po
  pos_empty_home/i18n/pos_empty_home.pot
  pos_empty_home/readme/CONTRIBUTORS.rst
  pos_empty_home/readme/DESCRIPTION.rst
  pos_empty_home/static/description/icon.png
  pos_empty_home/static/description/pos_empty_home.png
  pos_empty_home/static/src/css/pos_empty_home.css
  pos_empty_home/static/src/js/db.js
  pos_empty_home/static/src/js/screens.js
  pos_empty_home/static/src/xml/pos_empty_home.xml
  pos_empty_home/views/assets.xml
Labels: approved, ready to merge

#460 [12.0][FIX] pos_fix_search_limit: priority asset view change
  pos_fix_search_limit/README.rst
  pos_fix_search_limit/readme/CONTRIBUTORS.rst
  pos_fix_search_limit/static/description/index.html
  pos_fix_search_limit/views/pos_fix_limit.xml
Labels: approved

#409 12.0 mig pos journal image
  pos_journal_image/README.rst
  pos_journal_image/__init__.py
  pos_journal_image/__manifest__.py
  pos_journal_image/i18n/fr.po
  pos_journal_image/models/__init__.py
  pos_journal_image/models/account_journal.py
  pos_journal_image/readme/CONFIGURE.rst
  pos_journal_image/readme/CONTRIBUTORS.rst
  pos_journal_image/readme/DESCRIPTION.rst
  pos_journal_image/static/description/account_journal_form.png
  pos_journal_image/static/description/pos_payment.png
  pos_journal_image/static/src/css/pos_journal_image.css
  pos_journal_image/static/src/js/pos_journal_image.js
  pos_journal_image/static/src/xml/pos_journal_image.xml
  pos_journal_image/views/templates.xml
  pos_journal_image/views/view_account_journal.xml
Labels: approved, needs review, ready to merge
