Repository OCA/pos, pull requests merged in 2020-09, with the labels that each got.

#528 [13.0][MIG] pos_timeout
  pos_timeout/README.rst
  pos_timeout/__init__.py
  pos_timeout/__manifest__.py
  pos_timeout/i18n/es.po
  pos_timeout/i18n/fr.po
  pos_timeout/i18n/hr_HR.po
  pos_timeout/i18n/it.po
  pos_timeout/i18n/nl_NL.po
  pos_timeout/i18n/pos_timeout.pot
  pos_timeout/models/__init__.py
  pos_timeout/models/pos_config.py
  pos_timeout/readme/CONFIGURE.rst
  pos_timeout/readme/CONTRIBUTORS.rst
  pos_timeout/readme/CREDITS.rst
  pos_timeout/readme/DESCRIPTION.rst
  pos_timeout/static/description/icon.png
  pos_timeout/static/description/index.html
  pos_timeout/static/description/pos_config.png
  pos_timeout/static/src/js/pos_timeout.js
  pos_timeout/views/templates.xml
  pos_timeout/views/view_pos_config.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/pos_timeout/odoo/addons/pos_timeout
  setup/pos_timeout/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#363 [12.0][MIG] pos_session_pay_invoice
  oca_dependencies.txt
  pos_session_pay_invoice/README.rst
  pos_session_pay_invoice/__init__.py
  pos_session_pay_invoice/__manifest__.py
  pos_session_pay_invoice/i18n/pos_session_pay_invoice.pot
  pos_session_pay_invoice/readme/CONFIGURE.rst
  pos_session_pay_invoice/readme/CONTRIBUTORS.rst
  pos_session_pay_invoice/readme/DESCRIPTION.rst
  pos_session_pay_invoice/readme/ROADMAP.rst
  pos_session_pay_invoice/readme/USAGE.rst
  pos_session_pay_invoice/static/description/icon.png
  pos_session_pay_invoice/tests/__init__.py
  pos_session_pay_invoice/tests/test_pay_invoice.py
  pos_session_pay_invoice/views/pos_session.xml
  pos_session_pay_invoice/wizard/__init__.py
  pos_session_pay_invoice/wizard/cash_invoice_in.py
  pos_session_pay_invoice/wizard/cash_invoice_in.xml
  pos_session_pay_invoice/wizard/cash_invoice_out.py
  pos_session_pay_invoice/wizard/cash_invoice_out.xml
Labels: bot is merging ⏳

#178 [10.0][MIG] pos_sequence_ref_number
  pos_sequence_ref_number/README.rst
  pos_sequence_ref_number/__init__.py
  pos_sequence_ref_number/__manifest__.py
  pos_sequence_ref_number/i18n/ca.po
  pos_sequence_ref_number/i18n/de.po
  pos_sequence_ref_number/i18n/es.po
  pos_sequence_ref_number/i18n/fr.po
  pos_sequence_ref_number/i18n/gl.po
  pos_sequence_ref_number/i18n/it.po
  pos_sequence_ref_number/i18n/nl_NL.po
  pos_sequence_ref_number/i18n/sl.po
  pos_sequence_ref_number/i18n/zh_CN.po
  pos_sequence_ref_number/models/__init__.py
  pos_sequence_ref_number/models/pos_order.py
  pos_sequence_ref_number/static/lib/moment.js
  pos_sequence_ref_number/static/src/js/main.js
  pos_sequence_ref_number/static/src/xml/pos.xml
  pos_sequence_ref_number/tests/__init__.py
  pos_sequence_ref_number/tests/test_pos_order.py
  pos_sequence_ref_number/views/pos_template.xml
  setup/pos_sequence_ref_number/odoo/__init__.py
  setup/pos_sequence_ref_number/odoo/addons/__init__.py
  setup/pos_sequence_ref_number/odoo/addons/pos_sequence_ref_number
  setup/pos_sequence_ref_number/setup.py
Labels: bot is merging ⏳, needs review

#533 [ADD] pos_disable_change_cashier
  pos_disable_change_cashier/README.rst
  pos_disable_change_cashier/__init__.py
  pos_disable_change_cashier/__manifest__.py
  pos_disable_change_cashier/i18n/fr.po
  pos_disable_change_cashier/models/__init__.py
  pos_disable_change_cashier/models/pos_config.py
  pos_disable_change_cashier/readme/CONFIGURE.rst
  pos_disable_change_cashier/readme/CONTRIBUTORS.rst
  pos_disable_change_cashier/readme/DESCRIPTION.rst
  pos_disable_change_cashier/static/description/pos_config_form.png
  pos_disable_change_cashier/static/src/js/chrome.js
  pos_disable_change_cashier/views/assets.xml
  pos_disable_change_cashier/views/pos_config.xml
Labels: approved, bot is merging ⏳, ready to merge

#532 [10.0][FIX] .travis: Update to latest template
  .travis.yml
Labels: bot is merging ⏳

#534 [ADD] pos_report_order_payment
  pos_report_order_payment/__init__.py
  pos_report_order_payment/__manifest__.py
  pos_report_order_payment/i18n/fr.po
  pos_report_order_payment/i18n/pos_report_order_payment.pot
  pos_report_order_payment/readme/CONTRIBUTORS.rst
  pos_report_order_payment/readme/DESCRIPTION.rst
  pos_report_order_payment/readme/USAGE.rst
  pos_report_order_payment/report/__init__.py
  pos_report_order_payment/report/pos_order_payment_report.py
  pos_report_order_payment/report/pos_order_payment_report.xml
  pos_report_order_payment/security/ir.model.access.csv
  pos_report_order_payment/static/description/graph.png
  pos_report_order_payment/static/description/pivot.png
Labels: approved, bot is merging ⏳, ready to merge

#531 [FIX][12.0] pos_cash_move_reason : date of statement line depends now on the context timezone
  pos_cash_move_reason/wizard/wizard_pos_move_reason.py
Labels: approved, bot is merging ⏳, ready to merge

#535 [12.0] [IMP] pos_picking_load: returning widgets so they can be inherited
  pos_picking_load/static/src/js/widget.js
Labels: approved, bot is merging ⏳

#519 FIX pos change payment bad rounding compute
  pos_payment_change/wizards/pos_payment_change_wizard_new_line.py
  pos_payment_change/wizards/pos_payment_change_wizard_old_line.py
Labels: bot is merging ⏳

#537 pos_order_to_sale_order: Make JS extendable
  pos_order_to_sale_order/static/src/js/screens.js
Labels: approved, bot is merging ⏳
