Repository OCA/pos, pull requests merged in 2020-12, with the labels that each got.

#566 [FIX] pos_tare : raise an error if the gross weight is not correct
  pos_tare/static/src/js/screens.js
Labels: approved, bot is merging ⏳, ready to merge

#547 12.0 mig pos remove pos category
  pos_remove_pos_category/README.rst
  pos_remove_pos_category/__init__.py
  pos_remove_pos_category/__manifest__.py
  pos_remove_pos_category/i18n/es.po
  pos_remove_pos_category/i18n/fr.po
  pos_remove_pos_category/i18n/it.po
  pos_remove_pos_category/i18n/nl_NL.po
  pos_remove_pos_category/i18n/pos_remove_pos_category.pot
  pos_remove_pos_category/models/__init__.py
  pos_remove_pos_category/models/module.py
  pos_remove_pos_category/models/product.py
  pos_remove_pos_category/static/description/icon.png
  pos_remove_pos_category/static/src/js/pos_remove_pos_category.js
  pos_remove_pos_category/views/assets.xml
  pos_remove_pos_category/views/pos_category_view.xml
  pos_remove_pos_category/views/pos_view.xml
Labels: approved, bot is merging ⏳

#582 [FIX] pos_user_restriction: disable test that are failing if pos_restaurant module is installed
  pos_user_restriction/tests/test_pos_user_restriction.py
Labels: bot is merging ⏳
