Repository OCA/pos, pull requests merged in 2020-10, with the labels that each got.

#540 [FIX] pos_customer_display: compatibility with pos_restaurant
  pos_customer_display/static/src/js/screens.js
Labels: bot is merging ⏳

#538 [IMP] the font size of the displayed product name depends on the length of the product name
  pos_default_empty_image/__manifest__.py
  pos_default_empty_image/models/__init__.py
  pos_default_empty_image/models/pos_config.py
  pos_default_empty_image/readme/CONFIGURATION.rst
  pos_default_empty_image/static/description/pos_config_form.png
  pos_default_empty_image/static/src/css/pos_default_empty_image.css
  pos_default_empty_image/static/src/xml/pos_default_empty_image.xml
  pos_default_empty_image/views/pos_config.xml
Labels: approved, bot is merging ⏳, ready to merge

#476 [12.0][ADD] POS Multiple Control
  pos_multiple_control/README.rst
  pos_multiple_control/__init__.py
  pos_multiple_control/__manifest__.py
  pos_multiple_control/demo/account_account.xml
  pos_multiple_control/demo/account_journal.xml
  pos_multiple_control/demo/pos_config.xml
  pos_multiple_control/demo/pos_move_reason.xml
  pos_multiple_control/demo/res_groups.xml
  pos_multiple_control/i18n/fr.po
  pos_multiple_control/models/__init__.py
  pos_multiple_control/models/account_bank_statement.py
  pos_multiple_control/models/account_journal.py
  pos_multiple_control/models/pos_config.py
  pos_multiple_control/models/pos_session.py
  pos_multiple_control/readme/CONFIGURE.rst
  pos_multiple_control/readme/CONTRIBUTORS.rst
  pos_multiple_control/readme/DESCRIPTION.rst
  pos_multiple_control/static/description/account_journal_config.png
  pos_multiple_control/static/description/change_starting_balance.gif
  pos_multiple_control/static/description/end_session_balance_automatic_solve.gif
  pos_multiple_control/static/description/icon.png
  pos_multiple_control/static/description/index.html
  pos_multiple_control/static/description/open_new_session.png
  pos_multiple_control/static/description/pos_session.png
  pos_multiple_control/static/description/pos_session_config.png
  pos_multiple_control/tests/__init__.py
  pos_multiple_control/tests/test_pos_multiple_control.py
  pos_multiple_control/views/view_account_journal.xml
  pos_multiple_control/views/view_pos_config.xml
  pos_multiple_control/views/view_pos_session.xml
  pos_multiple_control/wizard/__init__.py
  pos_multiple_control/wizard/wizard_pos_update_statement_balance.py
  pos_multiple_control/wizard/wizard_pos_update_statement_balance.xml
Labels: bot is merging ⏳

#546 [12.0] [MIG] pos_stock_picking_invoice_link: Migration to v12
  oca_dependencies.txt
  pos_stock_picking_invoice_link/README.rst
  pos_stock_picking_invoice_link/__init__.py
  pos_stock_picking_invoice_link/__manifest__.py
  pos_stock_picking_invoice_link/i18n/pos_stock_picking_invoice_link.pot
  pos_stock_picking_invoice_link/models/__init__.py
  pos_stock_picking_invoice_link/models/pos_order.py
  pos_stock_picking_invoice_link/models/stock_move.py
  pos_stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  pos_stock_picking_invoice_link/readme/DESCRIPTION.rst
  pos_stock_picking_invoice_link/readme/USAGE.rst
  pos_stock_picking_invoice_link/static/description/icon.png
  pos_stock_picking_invoice_link/static/description/index.html
  pos_stock_picking_invoice_link/tests/__init__.py
  pos_stock_picking_invoice_link/tests/test_point_of_sale_stock_invoice_link.py
Labels: approved, bot is merging ⏳, ready to merge

#530 [ADD][12.0] pos_meal_voucher
  pos_meal_voucher/README.rst
  pos_meal_voucher/__init__.py
  pos_meal_voucher/__manifest__.py
  pos_meal_voucher/data/barcode_rule.xml
  pos_meal_voucher/demo/product_category.xml
  pos_meal_voucher/demo/product_product.xml
  pos_meal_voucher/i18n/fr.po
  pos_meal_voucher/models/__init__.py
  pos_meal_voucher/models/account_journal.py
  pos_meal_voucher/models/barcode_rule.py
  pos_meal_voucher/models/pos_config.py
  pos_meal_voucher/models/pos_order.py
  pos_meal_voucher/models/product_category.py
  pos_meal_voucher/models/product_template.py
  pos_meal_voucher/readme/CONFIGURE.rst
  pos_meal_voucher/readme/CONTRIBUTORS.rst
  pos_meal_voucher/readme/CREDITS.rst
  pos_meal_voucher/readme/DESCRIPTION.rst
  pos_meal_voucher/readme/ROADMAP.rst
  pos_meal_voucher/readme/USAGE.rst
  pos_meal_voucher/static/description/account_journal_form.png
  pos_meal_voucher/static/description/front_ui_pos_order_screen.png
  pos_meal_voucher/static/description/front_ui_pos_payment_screen.png
  pos_meal_voucher/static/description/front_ui_pos_payment_screen_summary.png
  pos_meal_voucher/static/description/front_ui_pos_payment_screen_warning.png
  pos_meal_voucher/static/description/issuer_1_up_dejeuner.jpg
  pos_meal_voucher/static/description/issuer_2_ticket_restaurant.jpeg
  pos_meal_voucher/static/description/issuer_3_apetiz.png
  pos_meal_voucher/static/description/issuer_4_pass_restaurant.png
  pos_meal_voucher/static/description/pos_config_form.png
  pos_meal_voucher/static/description/product_category_form.png
  pos_meal_voucher/static/description/product_product_form.png
  pos_meal_voucher/static/src/css/pos_meal_voucher.css
  pos_meal_voucher/static/src/js/models.js
  pos_meal_voucher/static/src/js/screens.js
  pos_meal_voucher/static/src/xml/pos_meal_voucher.xml
  pos_meal_voucher/views/templates.xml
  pos_meal_voucher/views/view_account_journal.xml
  pos_meal_voucher/views/view_pos_config.xml
  pos_meal_voucher/views/view_product_category.xml
  pos_meal_voucher/views/view_product_template.xml
Labels: approved, bot is merging ⏳
