Repository OCA/pos, pull requests merged in 2020-06, with the labels that each got.

#500 12.0 fix pos order return
  pos_order_return/models/pos_order.py
  pos_order_return/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#488 [12.0][MIG] pos_accented_search
  pos_accented_search/README.rst
  pos_accented_search/__init__.py
  pos_accented_search/__manifest__.py
  pos_accented_search/i18n/pos_accented_search.pot
  pos_accented_search/readme/CONTRIBUTORS.rst
  pos_accented_search/readme/DESCRIPTION.rst
  pos_accented_search/readme/USAGE.rst
  pos_accented_search/static/description/icon.png
  pos_accented_search/static/description/index.html
  pos_accented_search/static/src/js/db.js
  pos_accented_search/views/templates.xml
Labels: bot is merging ⏳

#504 [FIX] Fixed @api.constrains issue
  pos_customer_required/models/pos_order.py
Labels: approved, bot is merging ⏳

#505 [FIX] typo in pos_customer_display
  pos_customer_display/static/src/js/gui.js
Labels: bot is merging ⏳

#509 [FIX] pos_order_return is not computing correctly substotals on return
  pos_order_return/models/pos_order.py
Labels: approved, bot is merging ⏳

#480 [12.0][ADD] pos_payment_change
  pos_payment_change/README.rst
  pos_payment_change/__init__.py
  pos_payment_change/__manifest__.py
  pos_payment_change/i18n/fr.po
  pos_payment_change/i18n/pos_payment_change.pot
  pos_payment_change/models/__init__.py
  pos_payment_change/models/pos_config.py
  pos_payment_change/models/pos_order.py
  pos_payment_change/readme/CONFIGURE.rst
  pos_payment_change/readme/CONTRIBUTORS.rst
  pos_payment_change/readme/CREDITS.rst
  pos_payment_change/readme/DESCRIPTION.rst
  pos_payment_change/readme/USAGE.rst
  pos_payment_change/static/description/pos_config_form.png
  pos_payment_change/static/description/pos_order_form.png
  pos_payment_change/static/description/pos_order_tree.png
  pos_payment_change/static/description/pos_payment_change_wizard_form.png
  pos_payment_change/tests/__init__.py
  pos_payment_change/tests/test_module.py
  pos_payment_change/views/view_pos_config.xml
  pos_payment_change/views/view_pos_order.xml
  pos_payment_change/wizards/__init__.py
  pos_payment_change/wizards/pos_payment_change_wizard.py
  pos_payment_change/wizards/pos_payment_change_wizard_new_line.py
  pos_payment_change/wizards/pos_payment_change_wizard_old_line.py
  pos_payment_change/wizards/view_pos_payment_change_wizard.xml
Labels: approved, bot is merging ⏳, ready to merge

#511 [12.0] ADD pos_multi_ean
  pos_multi_ean/__init__.py
  pos_multi_ean/__manifest__.py
  pos_multi_ean/models/__init__.py
  pos_multi_ean/models/product.py
  pos_multi_ean/readme/CONFIGURE.rst
  pos_multi_ean/readme/CONTRIBUTORS.rst
  pos_multi_ean/readme/DESCRIPTION.rst
  pos_multi_ean/readme/USAGE.rst
  pos_multi_ean/static/src/js/db.js
  pos_multi_ean/views/assets.xml
  setup/pos_multi_ean/odoo/addons/pos_multi_ean
  setup/pos_multi_ean/setup.py
Labels: approved, bot is merging ⏳
