Repository OCA/pos, pull requests merged in 2020-05, with the labels that each got.

#484 [FIX] avoid error if user is not in the group group_pos_place_user
  pos_place/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#486 [FIX][12.0] pos_picking_delayed
  pos_picking_delayed/demo/pos_config.xml
  pos_picking_delayed/i18n/fr.po
  pos_picking_delayed/i18n/pos_picking_delayed.pot
  pos_picking_delayed/views/view_pos_config.xml
Labels: bot is merging ⏳

#485 [12.0][IMP] pos_price_to_weight: choose price field
  pos_price_to_weight/__manifest__.py
  pos_price_to_weight/demo/product_product.xml
  pos_price_to_weight/models/__init__.py
  pos_price_to_weight/models/pos_config.py
  pos_price_to_weight/readme/CONFIGURE.rst
  pos_price_to_weight/static/description/pos_config_form.png
  pos_price_to_weight/static/src/js/models.js
  pos_price_to_weight/views/view_pos_config.xml
Labels: approved, bot is merging ⏳

#489 [12.0][MIG] pos_reset_search
  pos_reset_search/README.rst
  pos_reset_search/__init__.py
  pos_reset_search/__manifest__.py
  pos_reset_search/i18n/pos_reset_search.pot
  pos_reset_search/readme/CONTRIBUTORS.rst
  pos_reset_search/readme/DESCRIPTION.rst
  pos_reset_search/readme/USAGE.rst
  pos_reset_search/static/description/icon.png
  pos_reset_search/static/description/index.html
  pos_reset_search/static/src/js/reset.js
  pos_reset_search/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#490 [12.0][ADD] pos_require_product_quantity
  pos_require_product_quantity/README.rst
  pos_require_product_quantity/__init__.py
  pos_require_product_quantity/__manifest__.py
  pos_require_product_quantity/models/__init__.py
  pos_require_product_quantity/models/pos_config.py
  pos_require_product_quantity/readme/CONTRIBUTORS.rst
  pos_require_product_quantity/readme/DESCRIPTION.rst
  pos_require_product_quantity/static/description/index.html
  pos_require_product_quantity/static/src/js/pos.js
  pos_require_product_quantity/views/assets.xml
  pos_require_product_quantity/views/pos_config.xml
Labels: approved, bot is merging ⏳, ready to merge

#463 [12.0] ADD pos_supplierinfo_barcode: Search products by supplier barcode
  oca_dependencies.txt
  pos_supplierinfo_barcode/__init__.py
  pos_supplierinfo_barcode/__manifest__.py
  pos_supplierinfo_barcode/models/__init__.py
  pos_supplierinfo_barcode/models/product.py
  pos_supplierinfo_barcode/readme/CONFIGURE.rst
  pos_supplierinfo_barcode/readme/CONTRIBUTORS.rst
  pos_supplierinfo_barcode/readme/DESCRIPTION.rst
  pos_supplierinfo_barcode/readme/USAGE.rst
  pos_supplierinfo_barcode/static/src/js/db.js
  pos_supplierinfo_barcode/views/assets.xml
  setup/pos_supplierinfo_barcode/odoo/addons/pos_supplierinfo_barcode
  setup/pos_supplierinfo_barcode/setup.py
Labels: approved, bot is merging ⏳

#493 [12.0][FIX] Telium test script
  hw_telium_payment_terminal/test-scripts/telium-test.py
Labels: approved

#437 [MIG][12.0] mig pos_customer_display
  pos_customer_display/README.rst
  pos_customer_display/__init__.py
  pos_customer_display/__manifest__.py
  pos_customer_display/demo/pos_config.xml
  pos_customer_display/i18n/de.po
  pos_customer_display/i18n/es.po
  pos_customer_display/i18n/fr.po
  pos_customer_display/i18n/hr_HR.po
  pos_customer_display/i18n/it.po
  pos_customer_display/i18n/nl.po
  pos_customer_display/i18n/nl_NL.po
  pos_customer_display/i18n/pos_customer_display.pot
  pos_customer_display/models/__init__.py
  pos_customer_display/models/pos_config.py
  pos_customer_display/readme/CONFIGURE.rst
  pos_customer_display/readme/CONTRIBUTORS.rst
  pos_customer_display/readme/DESCRIPTION.rst
  pos_customer_display/readme/INSTALL.rst
  pos_customer_display/readme/ROADMAP.rst
  pos_customer_display/readme/USAGE.rst
  pos_customer_display/static/description/icon.png
  pos_customer_display/static/src/js/customer_display_2_20.js
  pos_customer_display/static/src/js/devices.js
  pos_customer_display/static/src/js/gui.js
  pos_customer_display/static/src/js/models.js
  pos_customer_display/static/src/js/screens.js
  pos_customer_display/views/assets.xml
  pos_customer_display/views/view_pos_config.xml
Labels: approved

#497 [META] update repository readme file
  README.md
Labels: bot is merging ⏳
