Repository OCA/pos, pull requests merged in 2020-07, with the labels that each got.

#441 [MIG][12.0] pos_order_to_sale_order (from 8.0)
  pos_order_to_sale_order/README.rst
  pos_order_to_sale_order/__init__.py
  pos_order_to_sale_order/__manifest__.py
  pos_order_to_sale_order/i18n/fr.po
  pos_order_to_sale_order/i18n/pos_order_to_sale_order.pot
  pos_order_to_sale_order/models/__init__.py
  pos_order_to_sale_order/models/pos_config.py
  pos_order_to_sale_order/models/sale_order.py
  pos_order_to_sale_order/models/sale_order_line.py
  pos_order_to_sale_order/readme/CONFIGURE.rst
  pos_order_to_sale_order/readme/CONTRIBUTORS.rst
  pos_order_to_sale_order/readme/DESCRIPTION.rst
  pos_order_to_sale_order/readme/USAGE.rst
  pos_order_to_sale_order/static/description/icon.png
  pos_order_to_sale_order/static/description/index.html
  pos_order_to_sale_order/static/description/pos_config_form.png
  pos_order_to_sale_order/static/description/pos_frontend_buttons.png
  pos_order_to_sale_order/static/description/pos_frontend_order.png
  pos_order_to_sale_order/static/src/js/screens.js
  pos_order_to_sale_order/static/src/xml/pos_order_to_sale_order.xml
  pos_order_to_sale_order/views/assets.xml
  pos_order_to_sale_order/views/view_pos_config.xml
Labels: bot is merging ⏳, needs review

#515 [ADD] default_partner_pos
  pos_default_partner/README.rst
  pos_default_partner/__init__.py
  pos_default_partner/__manifest__.py
  pos_default_partner/models/__init__.py
  pos_default_partner/models/pos_config.py
  pos_default_partner/models/pos_order.py
  pos_default_partner/readme/CONFIGURE.rst
  pos_default_partner/readme/CONTRIBUTORS.rst
  pos_default_partner/readme/DESCRIPTION.rst
  pos_default_partner/readme/ROADMAP.rst
  pos_default_partner/static/description/index.html
  pos_default_partner/views/pos_config.xml
Labels: approved, bot is merging ⏳

#514 [12.0] ADD pos_user_restriction
  pos_user_restriction/__init__.py
  pos_user_restriction/__manifest__.py
  pos_user_restriction/i18n/it.po
  pos_user_restriction/models/__init__.py
  pos_user_restriction/models/pos_config.py
  pos_user_restriction/readme/CONFIGURE.rst
  pos_user_restriction/readme/CONTRIBUTORS.rst
  pos_user_restriction/readme/DESCRIPTION.rst
  pos_user_restriction/security/ir.model.access.csv
  pos_user_restriction/security/pos_security.xml
  pos_user_restriction/tests/__init__.py
  pos_user_restriction/tests/test_pos_user_restriction.py
  pos_user_restriction/views/pos_config_views.xml
  setup/pos_user_restriction/odoo/addons/pos_user_restriction
  setup/pos_user_restriction/setup.py
Labels: bot is merging ⏳

#491 [12.0][MIG] pos_tare w/ barcode
  pos_tare/README.rst
  pos_tare/__init__.py
  pos_tare/__manifest__.py
  pos_tare/data/barcode_rule.xml
  pos_tare/models/__init__.py
  pos_tare/models/barcode_rule.py
  pos_tare/models/pos_config.py
  pos_tare/models/pos_order_line.py
  pos_tare/readme/CONTRIBUTORS.rst
  pos_tare/readme/DESCRIPTION.rst
  pos_tare/readme/USAGE.rst
  pos_tare/static/description/icon.png
  pos_tare/static/description/index.html
  pos_tare/static/description/order.png
  pos_tare/static/description/pos_tare.png
  pos_tare/static/description/pos_ticket.png
  pos_tare/static/src/css/pos_tare.css
  pos_tare/static/src/js/models.js
  pos_tare/static/src/js/screens.js
  pos_tare/static/src/js/tools.js
  pos_tare/static/src/xml/pos_tare.xml
  pos_tare/views/templates.xml
  pos_tare/views/view_pos_config.xml
  pos_tare/views/view_pos_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#516 [12.0] ADD pos_supplierinfo_search
  pos_supplierinfo_search/__init__.py
  pos_supplierinfo_search/__manifest__.py
  pos_supplierinfo_search/models/__init__.py
  pos_supplierinfo_search/models/product.py
  pos_supplierinfo_search/readme/CONTRIBUTORS.rst
  pos_supplierinfo_search/readme/DESCRIPTION.rst
  pos_supplierinfo_search/readme/USAGE.rst
  pos_supplierinfo_search/static/src/js/db.js
  pos_supplierinfo_search/views/assets.xml
  setup/pos_supplierinfo_search/odoo/addons/pos_supplierinfo_search
  setup/pos_supplierinfo_search/setup.py
Labels: approved, bot is merging ⏳

#520 [12.0] FIX pos_user_restriction allowing "User: Assigned POS Only" to see point of sale menu
  pos_user_restriction/__manifest__.py
  pos_user_restriction/views/point_of_sale_views.xml
Labels: approved, bot is merging ⏳
