Repository OCA/pos, pull requests merged in 2020-04, with the labels that each got.

#477 [FIX] pos_order_return: bad image paths in readme segments
  pos_order_return/readme/CONFIGURE.rst
  pos_order_return/readme/USAGE.rst
Labels: bot is merging ⏳

#471 [MIG] 12.0 mig hw telium payment terminal
  hw_telium_payment_terminal/README.rst
  hw_telium_payment_terminal/__init__.py
  hw_telium_payment_terminal/__manifest__.py
  hw_telium_payment_terminal/controllers/__init__.py
  hw_telium_payment_terminal/controllers/main.py
  hw_telium_payment_terminal/static/description/icon.png
  hw_telium_payment_terminal/test-scripts/telium-test.py
Labels: approved

#381 [ADD][12.0] New module pos_place (to handle roaming sale)
  pos_place/README.rst
  pos_place/__init__.py
  pos_place/__manifest__.py
  pos_place/demo/pos_place.xml
  pos_place/demo/res_groups.xml
  pos_place/i18n/fr.po
  pos_place/models/__init__.py
  pos_place/models/pos_config.py
  pos_place/models/pos_order.py
  pos_place/models/pos_place.py
  pos_place/readme/CONFIGURE.rst
  pos_place/readme/CONTRIBUTORS.rst
  pos_place/readme/DESCRIPTION.rst
  pos_place/readme/USAGE.rst
  pos_place/report/__init__.py
  pos_place/report/report_pos_order.py
  pos_place/security/ir.model.access.csv
  pos_place/security/ir_module_category.xml
  pos_place/security/ir_rule.xml
  pos_place/security/res_groups.xml
  pos_place/static/description/pos_front_end_ui.png
  pos_place/static/description/pos_order_tree.png
  pos_place/static/description/pos_place_tree.png
  pos_place/static/description/report_pos_order_graph.png
  pos_place/static/src/js/chrome.js
  pos_place/static/src/js/gui.js
  pos_place/static/src/js/models.js
  pos_place/static/src/js/widget.js
  pos_place/static/src/xml/pos_place.xml
  pos_place/views/templates.xml
  pos_place/views/view_pos_config.xml
  pos_place/views/view_pos_order.xml
  pos_place/views/view_pos_place.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#467 [IMP] Set lot/serial number when returning orders
  pos_order_mgmt/models/pos_order.py
  pos_order_mgmt/static/src/js/widgets.js
Labels: approved, bot is merging ⏳, ready to merge

#482 [FIX] pos_pricelist: external_dependencies_override
  setup/pos_pricelist/setup.py
Labels: approved, bot is merging ⏳
