Repository OCA/pos, pull requests merged in 2020-08, with the labels that each got.

#521 [12.0][ADD] pos_session_closing_stock_error
  pos_session_closing_stock_error/__init__.py
  pos_session_closing_stock_error/__manifest__.py
  pos_session_closing_stock_error/models/__init__.py
  pos_session_closing_stock_error/models/pos_config.py
  pos_session_closing_stock_error/models/pos_session.py
  pos_session_closing_stock_error/readme/CONFIGURE.rst
  pos_session_closing_stock_error/readme/CONTRIBUTORS.rst
  pos_session_closing_stock_error/readme/DESCRIPTION.rst
  pos_session_closing_stock_error/static/description/error_msg.png
  pos_session_closing_stock_error/static/description/session_with_errors.png
  pos_session_closing_stock_error/tests/__init__.py
  pos_session_closing_stock_error/tests/test_pos.py
  pos_session_closing_stock_error/views/pos_config_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#492 [10.0][FIX] - handle the case where product is a dict
  pos_pricelist/static/src/js/models.js
  pos_pricelist/static/src/js/screens.js
  pos_pricelist/static/src/xml/pos.xml
Labels: bot is merging ⏳

#518 [12.0] ADD pos_fixed_discount
  pos_fixed_discount/__init__.py
  pos_fixed_discount/__manifest__.py
  pos_fixed_discount/i18n/it.po
  pos_fixed_discount/readme/CONTRIBUTORS.rst
  pos_fixed_discount/readme/DESCRIPTION.rst
  pos_fixed_discount/readme/USAGE.rst
  pos_fixed_discount/static/src/js/discount.js
  pos_fixed_discount/static/src/xml/discount_templates.xml
  pos_fixed_discount/views/pos_templates.xml
  setup/pos_fixed_discount/odoo/addons/pos_fixed_discount
  setup/pos_fixed_discount/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#97 [MIG][9.0]Updated pos_product_template addon to 9.0
  pos_product_template/__openerp__.py
  pos_product_template/i18n/es.po
  pos_product_template/static/src/js/ppt.js
  pos_product_template/view/view.xml
Labels: bot is merging ⏳, needs review

#479 [10.0][ADD] product_brand_pos_report
  product_brand_pos_report/__init__.py
  product_brand_pos_report/__manifest__.py
  product_brand_pos_report/i18n/es.po
  product_brand_pos_report/i18n/product_brand_sale_report.pot
  product_brand_pos_report/readme/CONTRIBUTORS.rst
  product_brand_pos_report/readme/DESCRIPTION.rst
  product_brand_pos_report/readme/ROADMAP.rst
  product_brand_pos_report/reports/__init__.py
  product_brand_pos_report/reports/pos_order_report.py
  product_brand_pos_report/reports/pos_order_report_view.xml
  product_brand_pos_report/static/description/icon.png
Labels: bot is merging ⏳

#524 [FIX] pos_order_mgmt: don't relay on demo data
  pos_order_mgmt/tests/test_module.py
Labels: bot is merging ⏳

#525 [FIX] pos_order_mgmt: test pricelist
  pos_order_mgmt/tests/test_module.py
Labels: bot is merging ⏳

#526 [FIX] pos_order_mgmt test
  pos_order_mgmt/tests/test_module.py
Labels: bot is merging ⏳
