Repository OCA/pos, pull requests merged in 2021-01, with the labels that each got.

#585 [12.0] IMP pos_partner_firstname allowing to use tab to move from firstname to lastname
  pos_partner_firstname/static/src/xml/pos.xml
Labels: bot is merging ⏳

#579 [ADD] pos_order_line_note : store pos.order.line note field in database
  pos_order_line_note/README.rst
  pos_order_line_note/__init__.py
  pos_order_line_note/__manifest__.py
  pos_order_line_note/i18n/fr.po
  pos_order_line_note/models/__init__.py
  pos_order_line_note/models/pos_order_line.py
  pos_order_line_note/readme/CONTRIBUTORS.rst
  pos_order_line_note/readme/DESCRIPTION.rst
  pos_order_line_note/readme/ROADMAP.rst
  pos_order_line_note/readme/USAGE.rst
  pos_order_line_note/static/description/point_of_sale.png
  pos_order_line_note/static/description/pos_order_form.png
  pos_order_line_note/views/view_pos_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#593 [14.0] [ADD] pos_show_config_name
  pos_show_config_name/README.rst
  pos_show_config_name/__init__.py
  pos_show_config_name/__manifest__.py
  pos_show_config_name/readme/DESCRIPTION.rst
  pos_show_config_name/static/description/index.html
  pos_show_config_name/static/src/xml/CashierName.xml
  setup/pos_show_config_name/odoo/addons/pos_show_config_name
  setup/pos_show_config_name/setup.py
Labels: approved, bot is merging ⏳
