Repository OCA/pos, pull requests merged in 2021-08, with the labels that each got.

#586 [FIX] pos_payment_change: use original date_order for the new orders and the payments
  pos_payment_change/models/pos_order.py
  pos_payment_change/wizards/pos_payment_change_wizard.py
Labels: bot is merging ⏳, needs review

#678 [FIX] pos_payment_terminal : order is undefined in the table screen
  pos_payment_terminal/static/src/js/devices.js
Labels: bot is merging ⏳

#557 [12.0][FIX] pos_payment_change Add missing unlink access for Point Of Sale:User
  pos_payment_change/models/pos_order.py
Labels: bot is merging ⏳

#694 [14.0][mig]pos_empty_home
  pos_empty_home/README.rst
  pos_empty_home/__init__.py
  pos_empty_home/__manifest__.py
  pos_empty_home/demo/pos_empty_home.xml
  pos_empty_home/i18n/ca.po
  pos_empty_home/i18n/es.po
  pos_empty_home/i18n/fr.po
  pos_empty_home/i18n/pos_empty_home.pot
  pos_empty_home/models/__init__.py
  pos_empty_home/models/pos_config.py
  pos_empty_home/readme/CONTRIBUTORS.rst
  pos_empty_home/readme/DESCRIPTION.rst
  pos_empty_home/static/description/icon.png
  pos_empty_home/static/description/index.html
  pos_empty_home/static/description/pos_empty_home.png
  pos_empty_home/static/src/js/db.js
  pos_empty_home/static/src/xml/pos_empty_home.xml
  pos_empty_home/views/assets.xml
  pos_empty_home/views/pos_config.xml
  setup/pos_empty_home/odoo/addons/pos_empty_home
  setup/pos_empty_home/setup.py
Labels: approved, bot is merging ⏳

#695 [UPD] Update from copier template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
  README.md
Labels: approved

#697 [fix]pos_fixed_discount
  pos_fixed_discount/__manifest__.py
  pos_fixed_discount/views/pos_templates.xml
Labels: bot is merging ⏳

#693 [12.0][ADD] pos_cache_user_restriction
  pos_cache_user_restriction/README.rst
  pos_cache_user_restriction/__init__.py
  pos_cache_user_restriction/__manifest__.py
  pos_cache_user_restriction/i18n/pos_cache_user_restriction.pot
  pos_cache_user_restriction/readme/CONFIGURE.rst
  pos_cache_user_restriction/readme/CONTRIBUTORS.rst
  pos_cache_user_restriction/readme/DESCRIPTION.rst
  pos_cache_user_restriction/security/ir.model.access.csv
  pos_cache_user_restriction/static/description/icon.png
  pos_cache_user_restriction/static/description/index.html
Labels: approved, bot is merging ⏳

#700 [REF] adopt several modules
  pos_hide_banknote_button/__manifest__.py
  pos_hide_empty_category/__manifest__.py
  pos_invoicing/__manifest__.py
  pos_journal_image/__manifest__.py
  pos_meal_voucher/__manifest__.py
  pos_order_line_no_unlink/__manifest__.py
  pos_order_line_note/__manifest__.py
  pos_picking_delayed/__manifest__.py
  pos_place/__manifest__.py
  pos_product_sort/__manifest__.py
  pos_to_weight_by_product_uom/__manifest__.py
  pos_warning_exiting/__manifest__.py
Labels: bot is merging ⏳

#577 [ADD] pos_escpos_status module
  pos_escpos_status/README.rst
  pos_escpos_status/__init__.py
  pos_escpos_status/__manifest__.py
  pos_escpos_status/readme/DESCRIPTION.rst
  pos_escpos_status/static/description/index.html
  pos_escpos_status/static/src/js/ProxyStatus.js
  pos_escpos_status/views/assets.xml
  setup/pos_escpos_status/odoo/addons/pos_escpos_status
  setup/pos_escpos_status/setup.py
Labels: bot is merging ⏳, stale

#684 [ADD] pos_payment_method_cashdro: New module
  pos_payment_method_cashdro/README.rst
  pos_payment_method_cashdro/__init__.py
  pos_payment_method_cashdro/__manifest__.py
  pos_payment_method_cashdro/models/__init__.py
  pos_payment_method_cashdro/models/account_journal.py
  pos_payment_method_cashdro/readme/CONFIGURE.rst
  pos_payment_method_cashdro/readme/CONTRIBUTORS.rst
  pos_payment_method_cashdro/readme/DESCRIPTION.rst
  pos_payment_method_cashdro/readme/ROADMAP.rst
  pos_payment_method_cashdro/readme/USAGE.rst
  pos_payment_method_cashdro/static/description/index.html
  pos_payment_method_cashdro/static/description/logo.png
  pos_payment_method_cashdro/static/src/js/models.js
  pos_payment_method_cashdro/static/src/js/screens.js
  pos_payment_method_cashdro/static/src/scss/pos_cashdro_terminal.scss
  pos_payment_method_cashdro/static/src/xml/pos_cashdro_terminal.xml
  pos_payment_method_cashdro/views/account_journal.xml
  pos_payment_method_cashdro/views/assets.xml
Labels: bot is merging ⏳

#702 [13.0][MIG] pos_report_session_summary: Migration to 13.0
  pos_report_session_summary/README.rst
  pos_report_session_summary/__init__.py
  pos_report_session_summary/__manifest__.py
  pos_report_session_summary/i18n/ca.po
  pos_report_session_summary/i18n/ca_ES.po
  pos_report_session_summary/i18n/de.po
  pos_report_session_summary/i18n/es.po
  pos_report_session_summary/i18n/fr.po
  pos_report_session_summary/i18n/pos_report_session_summary.pot
  pos_report_session_summary/i18n/pt.po
  pos_report_session_summary/readme/DESCRIPTION.rst
  pos_report_session_summary/readme/USAGE.rst
  pos_report_session_summary/static/description/icon.png
  pos_report_session_summary/static/description/index.html
  pos_report_session_summary/views/report_session_summary.xml
  pos_report_session_summary/views/session_summary_report.xml
  setup/pos_report_session_summary/odoo/addons/pos_report_session_summary
  setup/pos_report_session_summary/setup.py
Labels: approved, bot is merging ⏳
