Repository OCA/pos, pull requests merged in 2021-12, with the labels that each got.

#731 [MIG][14.0] pos_report_session_summary
  pos_report_session_summary/README.rst
  pos_report_session_summary/__init__.py
  pos_report_session_summary/__manifest__.py
  pos_report_session_summary/i18n/ca.po
  pos_report_session_summary/i18n/ca_ES.po
  pos_report_session_summary/i18n/de.po
  pos_report_session_summary/i18n/es.po
  pos_report_session_summary/i18n/fr.po
  pos_report_session_summary/i18n/pos_report_session_summary.pot
  pos_report_session_summary/i18n/pt.po
  pos_report_session_summary/readme/DESCRIPTION.rst
  pos_report_session_summary/readme/USAGE.rst
  pos_report_session_summary/static/description/icon.png
  pos_report_session_summary/static/description/index.html
  pos_report_session_summary/views/report_session_summary.xml
  pos_report_session_summary/views/session_summary_report.xml
  setup/pos_report_session_summary/odoo/addons/pos_report_session_summary
  setup/pos_report_session_summary/setup.py
Labels: approved, bot is merging ⏳

#658 [MIG][12.0][NEW] pos_order_picking_link
  pos_order_picking_link/README.rst
  pos_order_picking_link/__init__.py
  pos_order_picking_link/__manifest__.py
  pos_order_picking_link/models/__init__.py
  pos_order_picking_link/models/stock_picking.py
  pos_order_picking_link/readme/CONTRIBUTORS.rst
  pos_order_picking_link/readme/CREDITS.rst
  pos_order_picking_link/readme/DESCRIPTION.rst
  pos_order_picking_link/readme/USAGE.rst
  pos_order_picking_link/static/description/icon.png
  pos_order_picking_link/static/description/index.html
  pos_order_picking_link/views/stock_view.xml
Labels: bot is merging ⏳

#736 [ADD] 14.0 pos_reuse_pricelist module
  pos_reuse_pricelist/__manifest__.py
  pos_reuse_pricelist/readme/DESCRIPTION.rst
  pos_reuse_pricelist/static/src/js/models.js
  pos_reuse_pricelist/views/pos_assets.xml
  setup/pos_reuse_pricelist/odoo/addons/pos_reuse_pricelist
  setup/pos_reuse_pricelist/setup.py
Labels: approved, bot is merging ⏳

#738 [12.0] ADD pos_product_default_code
  pos_product_default_code/__init__.py
  pos_product_default_code/__manifest__.py
  pos_product_default_code/readme/CONTRIBUTORS.rst
  pos_product_default_code/readme/DESCRIPTION.rst
  pos_product_default_code/static/src/css/pos.css
  pos_product_default_code/static/src/xml/pos.xml
  pos_product_default_code/views/templates.xml
  setup/pos_product_default_code/odoo/addons/pos_product_default_code
  setup/pos_product_default_code/setup.py
Labels: approved, bot is merging ⏳

#387 [ADD] pos_check_session_state
  pos_check_session_state/README.rst
  pos_check_session_state/__init__.py
  pos_check_session_state/__manifest__.py
  pos_check_session_state/i18n/fr.po
  pos_check_session_state/models/__init__.py
  pos_check_session_state/models/pos_config.py
  pos_check_session_state/models/pos_order.py
  pos_check_session_state/readme/CONFIGURE.rst
  pos_check_session_state/readme/CONTRIBUTORS.rst
  pos_check_session_state/readme/DESCRIPTION.rst
  pos_check_session_state/static/description/create_from_ui_error.png
  pos_check_session_state/static/description/error_message.png
  pos_check_session_state/static/description/icon.png
  pos_check_session_state/static/description/pos_config_form.png
  pos_check_session_state/static/src/js/chrome.js
  pos_check_session_state/views/templates.xml
  pos_check_session_state/views/view_pos_config.xml
Labels: approved, bot is merging ⏳, stale

#739 [14.0][FIX] pos_report_session_summary
  pos_report_session_summary/views/session_summary_report.xml
Labels: approved, bot is merging ⏳

#743 [FIX] pos_payment_change: fix test
  pos_payment_change/tests/test_module.py
Labels: bot is merging ⏳

#597 [14.0] Add module pos_no_cash_bank_statement
  pos_no_cash_bank_statement/__init__.py
  pos_no_cash_bank_statement/__manifest__.py
  pos_no_cash_bank_statement/models/__init__.py
  pos_no_cash_bank_statement/models/pos_payment_method.py
  pos_no_cash_bank_statement/models/pos_session.py
  pos_no_cash_bank_statement/readme/CONTRIBUTORS.rst
  pos_no_cash_bank_statement/readme/DESCRIPTION.rst
  pos_no_cash_bank_statement/views/pos_payment_method.xml
  setup/pos_no_cash_bank_statement/odoo/addons/pos_no_cash_bank_statement
  setup/pos_no_cash_bank_statement/setup.py
Labels: needs fixing, ready to merge, bot is merging ⏳

#411 12.0 migrate pos_product_template
  pos_product_template/README.rst
  pos_product_template/__init__.py
  pos_product_template/__manifest__.py
  pos_product_template/demo/product_attribute_value.xml
  pos_product_template/demo/product_product.xml
  pos_product_template/i18n/es.po
  pos_product_template/i18n/fr.po
  pos_product_template/i18n/pos_product_template.pot
  pos_product_template/readme/CONTRIBUTORS.rst
  pos_product_template/readme/CREDITS.rst
  pos_product_template/readme/DESCRIPTION.rst
  pos_product_template/readme/ROADMAP.rst
  pos_product_template/readme/USAGE.rst
  pos_product_template/static/description/icon.png
  pos_product_template/static/src/css/ppt.css
  pos_product_template/static/src/img/screenshots/pos_product_template.png
  pos_product_template/static/src/js/ppt.js
  pos_product_template/static/src/xml/ppt.xml
  pos_product_template/view/view.xml
Labels: bot is merging ⏳, stale
