Repository OCA/pos, pull requests merged in 2021-09, with the labels that each got.

#651 [14.0] [mig] pos_reset_search
  pos_reset_search/README.rst
  pos_reset_search/__init__.py
  pos_reset_search/__manifest__.py
  pos_reset_search/i18n/es.po
  pos_reset_search/i18n/pos_reset_search.pot
  pos_reset_search/readme/CONTRIBUTORS.rst
  pos_reset_search/readme/DESCRIPTION.rst
  pos_reset_search/readme/USAGE.rst
  pos_reset_search/static/description/icon.png
  pos_reset_search/static/description/index.html
  pos_reset_search/static/src/js/ProductScreen.js
  pos_reset_search/views/templates.xml
  setup/pos_reset_search/odoo/addons/pos_reset_search
  setup/pos_reset_search/setup.py
Labels: approved, bot is merging ⏳

#706 [12.0][FIX] Use scss stylesheet instead of less
  pos_order_remove_line/readme/CONTRIBUTORS.rst
  pos_order_remove_line/static/src/css/order_line.scss
  pos_order_remove_line/views/assets.xml
Labels: bot is merging ⏳

#657 [13.0][ADD] pos_partner_lang
  pos_partner_lang/README.rst
  pos_partner_lang/__init__.py
  pos_partner_lang/__manifest__.py
  pos_partner_lang/models/__init__.py
  pos_partner_lang/models/res_partner.py
  pos_partner_lang/readme/CONTRIBUTORS.rst
  pos_partner_lang/readme/DESCRIPTION.rst
  pos_partner_lang/static/description/pos_partner_lang.png
  pos_partner_lang/static/src/js/models.js
  pos_partner_lang/static/src/xml/screens.xml
  pos_partner_lang/tests/__init__.py
  pos_partner_lang/tests/test_pos_partner_lang.py
  pos_partner_lang/views/assets.xml
  setup/pos_partner_lang/odoo/addons/pos_partner_lang
  setup/pos_partner_lang/setup.py
Labels: approved, needs review, bot is merging ⏳

#709 [14] pos_backend_communication: add maintainers in manifest
  pos_backend_communication/__manifest__.py
Labels: bot is merging ⏳
