Repository OCA/pos, pull requests merged in 2021-04, with the labels that each got.

#614 [13.0][MIG]pos_product_sort: standard migration
  pos_product_sort/README.rst
  pos_product_sort/__init__.py
  pos_product_sort/__manifest__.py
  pos_product_sort/i18n/fr.po
  pos_product_sort/i18n/pos_product_sort.pot
  pos_product_sort/readme/CONTRIBUTORS.rst
  pos_product_sort/readme/CREDITS.rst
  pos_product_sort/readme/DESCRIPTION.rst
  pos_product_sort/readme/ROADMAP.rst
  pos_product_sort/static/description/icon.png
  pos_product_sort/static/description/index.html
  pos_product_sort/static/description/point_of_sale_name_order.png
  pos_product_sort/static/description/point_of_sale_sequence_order.png
  pos_product_sort/static/src/js/models.js
  pos_product_sort/views/assets.xml
Labels: approved, bot is merging ⏳

#608 [MIG] pos_default_partner: Migration to 13.0
  pos_default_partner/README.rst
  pos_default_partner/__init__.py
  pos_default_partner/__manifest__.py
  pos_default_partner/i18n/es.po
  pos_default_partner/i18n/pos_default_partner.pot
  pos_default_partner/models/__init__.py
  pos_default_partner/models/pos_config.py
  pos_default_partner/models/pos_order.py
  pos_default_partner/readme/CONFIGURE.rst
  pos_default_partner/readme/CONTRIBUTORS.rst
  pos_default_partner/readme/DESCRIPTION.rst
  pos_default_partner/readme/ROADMAP.rst
  pos_default_partner/static/description/icon.png
  pos_default_partner/static/description/index.html
  pos_default_partner/tests/__init__.py
  pos_default_partner/tests/test_pos_default_partner.py
  pos_default_partner/views/pos_config.xml
  setup/pos_default_partner/odoo/addons/pos_default_partner
  setup/pos_default_partner/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#618 [UPD] README file
  pos_product_sort/readme/ROADMAP.rst
Labels: bot is merging ⏳

#617 [FIX] pos_multiple_control : fix compatibility with pos_session_pay_invoice. hide buttons instead of removing them
  pos_multiple_control/views/view_pos_session.xml
Labels: approved, bot is merging ⏳, ready to merge

#570 [12.0][IMP] Pos_multiple_control : Improve wizard update balance [FIX] automatic solve
  pos_multiple_control/README.rst
  pos_multiple_control/__manifest__.py
  pos_multiple_control/demo/account_bank_statement_cashbox.xml
  pos_multiple_control/demo/account_journal.xml
  pos_multiple_control/i18n/fr.po
  pos_multiple_control/i18n/pos_multiple_control.pot
  pos_multiple_control/models/account_bank_statement.py
  pos_multiple_control/models/account_journal.py
  pos_multiple_control/readme/CONFIGURE.rst
  pos_multiple_control/readme/DESCRIPTION.rst
  pos_multiple_control/static/description/change_starting_balance.gif
  pos_multiple_control/static/description/configure_cashbox_in_journal.gif
  pos_multiple_control/static/description/end_session_balance_automatic_solve.gif
  pos_multiple_control/static/description/end_session_set_balance.gif
  pos_multiple_control/views/view_account_bank_statement_cashbox.xml
  pos_multiple_control/views/view_account_journal.xml
  pos_multiple_control/wizard/wizard_pos_update_statement_balance.py
  pos_multiple_control/wizard/wizard_pos_update_statement_balance.xml
Labels: bot is merging ⏳

#611 [ADD] pos_order_line_no_unlink: new module to prevent unlinking order lines
  pos_order_line_no_unlink/README.rst
  pos_order_line_no_unlink/__init__.py
  pos_order_line_no_unlink/__manifest__.py
  pos_order_line_no_unlink/i18n/fr.po
  pos_order_line_no_unlink/models/__init__.py
  pos_order_line_no_unlink/models/pos_order_line.py
  pos_order_line_no_unlink/readme/CONTRIBUTORS.rst
  pos_order_line_no_unlink/readme/DESCRIPTION.rst
  pos_order_line_no_unlink/tests/__init__.py
  pos_order_line_no_unlink/tests/test_module.py
Labels: approved, bot is merging ⏳, ready to merge

#626 [13.0] [mig] pos_fixed_discount
  pos_fixed_discount/README.rst
  pos_fixed_discount/__init__.py
  pos_fixed_discount/__manifest__.py
  pos_fixed_discount/i18n/es.po
  pos_fixed_discount/i18n/it.po
  pos_fixed_discount/i18n/pos_fixed_discount.pot
  pos_fixed_discount/readme/CONTRIBUTORS.rst
  pos_fixed_discount/readme/DESCRIPTION.rst
  pos_fixed_discount/readme/USAGE.rst
  pos_fixed_discount/static/description/icon.png
  pos_fixed_discount/static/description/index.html
  pos_fixed_discount/static/src/js/discount.js
  pos_fixed_discount/static/src/xml/discount_templates.xml
  pos_fixed_discount/views/pos_templates.xml
  setup/pos_fixed_discount/odoo/addons/pos_fixed_discount
  setup/pos_fixed_discount/setup.py
Labels: approved, bot is merging ⏳, ready to merge
