Repository OCA/pos, pull requests merged in 2021-07, with the labels that each got.

#632 [14.0] [mig] pos_supplierinfo_search
  pos_supplierinfo_search/README.rst
  pos_supplierinfo_search/__init__.py
  pos_supplierinfo_search/__manifest__.py
  pos_supplierinfo_search/i18n/es.po
  pos_supplierinfo_search/i18n/pos_supplierinfo_search.pot
  pos_supplierinfo_search/models/__init__.py
  pos_supplierinfo_search/models/product.py
  pos_supplierinfo_search/readme/CONTRIBUTORS.rst
  pos_supplierinfo_search/readme/DESCRIPTION.rst
  pos_supplierinfo_search/readme/USAGE.rst
  pos_supplierinfo_search/static/description/icon.png
  pos_supplierinfo_search/static/description/index.html
  pos_supplierinfo_search/static/src/js/db.js
  pos_supplierinfo_search/views/assets.xml
  setup/pos_supplierinfo_search/odoo/addons/pos_supplierinfo_search
  setup/pos_supplierinfo_search/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#672 [13.0][IMP]pos_default_partner: Show default partner
  pos_default_partner/__manifest__.py
  pos_default_partner/readme/CONTRIBUTORS.rst
  pos_default_partner/static/src/js/models.js
  pos_default_partner/views/point_of_sale.xml
Labels: approved, bot is merging ⏳

#631 [14.0] [mig] pos_hide_banknote_button
  pos_hide_banknote_button/README.rst
  pos_hide_banknote_button/__init__.py
  pos_hide_banknote_button/__manifest__.py
  pos_hide_banknote_button/i18n/es.po
  pos_hide_banknote_button/i18n/fr.po
  pos_hide_banknote_button/i18n/pos_hide_banknote_button.pot
  pos_hide_banknote_button/readme/CONTRIBUTORS.rst
  pos_hide_banknote_button/readme/DESCRIPTION.rst
  pos_hide_banknote_button/static/description/after.png
  pos_hide_banknote_button/static/description/before.png
  pos_hide_banknote_button/static/description/icon.png
  pos_hide_banknote_button/static/description/index.html
  pos_hide_banknote_button/static/src/css/pos_hide_banknote_button.css
  pos_hide_banknote_button/views/assets.xml
  setup/pos_hide_banknote_button/odoo/addons/pos_hide_banknote_button
  setup/pos_hide_banknote_button/setup.py
Labels: bot is merging ⏳, needs review

#683 [13.0][MIG]pos_order_to_sale_order, standard migration
  pos_order_to_sale_order/README.rst
  pos_order_to_sale_order/__init__.py
  pos_order_to_sale_order/__manifest__.py
  pos_order_to_sale_order/i18n/es.po
  pos_order_to_sale_order/i18n/fr.po
  pos_order_to_sale_order/i18n/pos_order_to_sale_order.pot
  pos_order_to_sale_order/i18n/pt_BR.po
  pos_order_to_sale_order/models/__init__.py
  pos_order_to_sale_order/models/pos_config.py
  pos_order_to_sale_order/models/sale_order.py
  pos_order_to_sale_order/models/sale_order_line.py
  pos_order_to_sale_order/readme/CONFIGURE.rst
  pos_order_to_sale_order/readme/CONTRIBUTORS.rst
  pos_order_to_sale_order/readme/DESCRIPTION.rst
  pos_order_to_sale_order/readme/USAGE.rst
  pos_order_to_sale_order/static/description/icon.png
  pos_order_to_sale_order/static/description/index.html
  pos_order_to_sale_order/static/description/pos_config_form.png
  pos_order_to_sale_order/static/description/pos_frontend_buttons.png
  pos_order_to_sale_order/static/description/pos_frontend_order.png
  pos_order_to_sale_order/static/src/js/screens.js
  pos_order_to_sale_order/static/src/xml/pos_order_to_sale_order.xml
  pos_order_to_sale_order/views/assets.xml
  pos_order_to_sale_order/views/view_pos_config.xml
  setup/pos_order_to_sale_order/odoo/addons/pos_order_to_sale_order
  setup/pos_order_to_sale_order/setup.py
Labels: approved, bot is merging ⏳

#685 [FIX] pos_order_mgmt : conserve pricelist of the previous order, when loading the order
  pos_order_mgmt/models/pos_order.py
  pos_order_mgmt/static/src/js/widgets.js
Labels: approved, bot is merging ⏳

#671 [14.0] [mig] pos_order_return
  pos_order_return/README.rst
  pos_order_return/__init__.py
  pos_order_return/__manifest__.py
  pos_order_return/demo/product_product.xml
  pos_order_return/i18n/ca.po
  pos_order_return/i18n/es.po
  pos_order_return/i18n/fr.po
  pos_order_return/i18n/pos_order_return.pot
  pos_order_return/models/__init__.py
  pos_order_return/models/pos_order.py
  pos_order_return/models/product_template.py
  pos_order_return/readme/CONFIGURE.rst
  pos_order_return/readme/CONTRIBUTORS.rst
  pos_order_return/readme/CREDITS.rst
  pos_order_return/readme/DESCRIPTION.rst
  pos_order_return/readme/ROADMAP.rst
  pos_order_return/readme/USAGE.rst
  pos_order_return/security/ir.model.access.csv
  pos_order_return/static/description/icon.png
  pos_order_return/static/description/index.html
  pos_order_return/static/description/initial_pos_order_required.png
  pos_order_return/static/description/partial_return_wizard.png
  pos_order_return/static/description/product_returnable_bottle.png
  pos_order_return/static/description/returned_qty_over_initial.png
  pos_order_return/static/description/sum_returned_qty_over_initial.png
  pos_order_return/static/img/product_returnable_bottle-image.jpg
  pos_order_return/tests/__init__.py
  pos_order_return/tests/test_pos_order_return.py
  pos_order_return/views/pos_order_view.xml
  pos_order_return/views/product_product_view.xml
  pos_order_return/wizard/__init__.py
  pos_order_return/wizard/pos_partial_return_wizard.py
  pos_order_return/wizard/pos_partial_return_wizard_view.xml
  setup/pos_order_return/odoo/addons/pos_order_return
  setup/pos_order_return/setup.py
Labels: approved, bot is merging ⏳

#687 [12.0][REF] pos_picking_delayed : refactor module, due to queue_job refactoring. + Add idempotent test
  pos_picking_delayed/__manifest__.py
  pos_picking_delayed/data/queue_job_channel.xml
  pos_picking_delayed/data/queue_job_function.xml
  pos_picking_delayed/models/pos_order.py
  pos_picking_delayed/readme/CONFIGURE.rst
Labels: approved, bot is merging ⏳

#663 [14.0] [mig] pos_margin
  pos_margin/README.rst
  pos_margin/__init__.py
  pos_margin/__manifest__.py
  pos_margin/i18n/es.po
  pos_margin/i18n/fr.po
  pos_margin/i18n/it.po
  pos_margin/i18n/nl_NL.po
  pos_margin/i18n/pos_margin.pot
  pos_margin/migrations/12.0.2.0.0/pre-migration.py
  pos_margin/models/__init__.py
  pos_margin/models/pos_config.py
  pos_margin/models/pos_order.py
  pos_margin/models/pos_order_line.py
  pos_margin/readme/CONFIGURE.rst
  pos_margin/readme/CONTRIBUTORS.rst
  pos_margin/readme/DESCRIPTION.rst
  pos_margin/readme/HISTORY.rst
  pos_margin/readme/ROADMAP.rst
  pos_margin/readme/USAGE.rst
  pos_margin/report/__init__.py
  pos_margin/report/pos_order_report.py
  pos_margin/static/description/icon.png
  pos_margin/static/description/index.html
  pos_margin/static/description/pos_config_form.png
  pos_margin/static/description/pos_front_end.png
  pos_margin/static/description/pos_order_form.png
  pos_margin/static/src/css/pos_margin.css
  pos_margin/static/src/js/OrderSummaryMargin.js
  pos_margin/static/src/js/OrderWidget.js
  pos_margin/static/src/js/models.js
  pos_margin/static/src/xml/pos_margin.xml
  pos_margin/tests/__init__.py
  pos_margin/tests/test_module.py
  pos_margin/views/templates.xml
  pos_margin/views/view_pos_config.xml
  pos_margin/views/view_pos_order.xml
  setup/pos_margin/odoo/addons/pos_margin
  setup/pos_margin/setup.py
Labels: bot is merging ⏳

#653 [14.0] pos_payment_change
  pos_payment_change/README.rst
  pos_payment_change/__init__.py
  pos_payment_change/__manifest__.py
  pos_payment_change/i18n/de.po
  pos_payment_change/i18n/es.po
  pos_payment_change/i18n/fr.po
  pos_payment_change/i18n/pos_payment_change.pot
  pos_payment_change/models/__init__.py
  pos_payment_change/models/pos_config.py
  pos_payment_change/models/pos_order.py
  pos_payment_change/readme/CONFIGURE.rst
  pos_payment_change/readme/CONTRIBUTORS.rst
  pos_payment_change/readme/CREDITS.rst
  pos_payment_change/readme/DESCRIPTION.rst
  pos_payment_change/readme/USAGE.rst
  pos_payment_change/security/ir.model.access.csv
  pos_payment_change/static/description/icon.png
  pos_payment_change/static/description/index.html
  pos_payment_change/static/description/pos_config_form.png
  pos_payment_change/static/description/pos_order_form.png
  pos_payment_change/static/description/pos_order_tree.png
  pos_payment_change/static/description/pos_payment_change_wizard_form.png
  pos_payment_change/tests/__init__.py
  pos_payment_change/tests/test_module.py
  pos_payment_change/views/view_pos_config.xml
  pos_payment_change/views/view_pos_order.xml
  pos_payment_change/wizards/__init__.py
  pos_payment_change/wizards/pos_payment_change_wizard.py
  pos_payment_change/wizards/pos_payment_change_wizard_new_line.py
  pos_payment_change/wizards/pos_payment_change_wizard_old_line.py
  pos_payment_change/wizards/view_pos_payment_change_wizard.xml
  setup/pos_payment_change/odoo/addons/pos_payment_change
  setup/pos_payment_change/setup.py
Labels: approved, bot is merging ⏳

#643 [IMP] 12.0 pos_customer_display correct proxy status display if it is the only device
  pos_customer_display/static/src/js/chrome.js
  pos_customer_display/static/src/js/models.js
  pos_customer_display/views/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#574 14.0 mig pos backend communication rebased
  pos_backend_communication/README.rst
  pos_backend_communication/__init__.py
  pos_backend_communication/__manifest__.py
  pos_backend_communication/i18n/es.po
  pos_backend_communication/i18n/it.po
  pos_backend_communication/i18n/pos_backend_communication.pot
  pos_backend_communication/models/__init__.py
  pos_backend_communication/models/ir_action.py
  pos_backend_communication/security/ir.model.access.csv
  pos_backend_communication/static/description/icon.png
  pos_backend_communication/static/src/css/pos_backend_communication.css
  pos_backend_communication/static/src/js/back.js
  pos_backend_communication/static/src/js/common.js
  pos_backend_communication/views/assets.xml
  setup/pos_backend_communication/odoo/addons/pos_backend_communication
  setup/pos_backend_communication/setup.py
Labels: approved, bot is merging ⏳

#688 [14.0] [mig] pos_order_remove_line
  pos_order_remove_line/README.rst
  pos_order_remove_line/__init__.py
  pos_order_remove_line/__manifest__.py
  pos_order_remove_line/i18n/pos_order_remove_line.pot
  pos_order_remove_line/readme/CONTRIBUTORS.rst
  pos_order_remove_line/readme/DESCRIPTION.rst
  pos_order_remove_line/static/description/icon.png
  pos_order_remove_line/static/description/index.html
  pos_order_remove_line/static/src/css/orderline.scss
  pos_order_remove_line/static/src/js/orderline.js
  pos_order_remove_line/static/src/xml/orderline.xml
  pos_order_remove_line/views/assets.xml
  setup/pos_order_remove_line/odoo/addons/pos_order_remove_line
  setup/pos_order_remove_line/setup.py
Labels: approved, bot is merging ⏳

#669 [13.0][MIG]pos_margin
  pos_margin/README.rst
  pos_margin/__init__.py
  pos_margin/__manifest__.py
  pos_margin/i18n/es.po
  pos_margin/i18n/fr.po
  pos_margin/i18n/it.po
  pos_margin/i18n/nl_NL.po
  pos_margin/i18n/pos_margin.pot
  pos_margin/i18n/pt.po
  pos_margin/migrations/12.0.2.0.0/pre-migration.py
  pos_margin/models/__init__.py
  pos_margin/models/pos_config.py
  pos_margin/models/pos_order.py
  pos_margin/models/pos_order_line.py
  pos_margin/readme/CONFIGURE.rst
  pos_margin/readme/CONTRIBUTORS.rst
  pos_margin/readme/DESCRIPTION.rst
  pos_margin/readme/HISTORY.rst
  pos_margin/readme/ROADMAP.rst
  pos_margin/readme/USAGE.rst
  pos_margin/report/__init__.py
  pos_margin/report/pos_order_report.py
  pos_margin/static/description/icon.png
  pos_margin/static/description/index.html
  pos_margin/static/description/pos_config_form.png
  pos_margin/static/description/pos_front_end.png
  pos_margin/static/description/pos_order_form.png
  pos_margin/static/description/pos_order_tree.png
  pos_margin/static/src/css/pos_margin.css
  pos_margin/static/src/js/models.js
  pos_margin/static/src/js/screens.js
  pos_margin/static/src/xml/pos_margin.xml
  pos_margin/tests/__init__.py
  pos_margin/tests/test_module.py
  pos_margin/views/templates.xml
  pos_margin/views/view_pos_config.xml
  pos_margin/views/view_pos_order.xml
  setup/pos_margin/odoo/addons/pos_margin
  setup/pos_margin/setup.py
Labels: approved, bot is merging ⏳, ready to merge
