Repository OCA/pos, pull requests merged in 2021-06, with the labels that each got.

#642 [IMP][13.0] pos_empty_home : Make it configurable and simplify code
  pos_empty_home/__init__.py
  pos_empty_home/__manifest__.py
  pos_empty_home/demo/pos_empty_home.xml
  pos_empty_home/models/__init__.py
  pos_empty_home/models/pos_config.py
  pos_empty_home/readme/CONTRIBUTORS.rst
  pos_empty_home/static/src/css/pos_empty_home.css
  pos_empty_home/static/src/js/db.js
  pos_empty_home/static/src/js/screens.js
  pos_empty_home/static/src/xml/pos_empty_home.xml
  pos_empty_home/views/assets.xml
  pos_empty_home/views/pos_config.xml
Labels: approved, bot is merging ⏳, ready to merge

#627 [14.0] [mig] pos_default_partner
  pos_default_partner/README.rst
  pos_default_partner/__init__.py
  pos_default_partner/__manifest__.py
  pos_default_partner/i18n/es.po
  pos_default_partner/i18n/pos_default_partner.pot
  pos_default_partner/models/__init__.py
  pos_default_partner/models/pos_config.py
  pos_default_partner/models/pos_order.py
  pos_default_partner/readme/CONFIGURE.rst
  pos_default_partner/readme/CONTRIBUTORS.rst
  pos_default_partner/readme/DESCRIPTION.rst
  pos_default_partner/readme/ROADMAP.rst
  pos_default_partner/static/description/icon.png
  pos_default_partner/static/description/index.html
  pos_default_partner/tests/__init__.py
  pos_default_partner/tests/test_pos_default_partner.py
  pos_default_partner/views/pos_config.xml
  setup/pos_default_partner/odoo/addons/pos_default_partner
  setup/pos_default_partner/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#668 13.0 mig pos payment method image
  pos_payment_method_image/README.rst
  pos_payment_method_image/__init__.py
  pos_payment_method_image/__manifest__.py
  pos_payment_method_image/i18n/ca.po
  pos_payment_method_image/i18n/ca_ES.po
  pos_payment_method_image/i18n/es.po
  pos_payment_method_image/i18n/fr.po
  pos_payment_method_image/i18n/pos_journal_image.pot
  pos_payment_method_image/models/__init__.py
  pos_payment_method_image/models/pos_payment_method.py
  pos_payment_method_image/readme/CONFIGURE.rst
  pos_payment_method_image/readme/CONTRIBUTORS.rst
  pos_payment_method_image/readme/DESCRIPTION.rst
  pos_payment_method_image/readme/ROADMAP.rst
  pos_payment_method_image/static/description/icon.png
  pos_payment_method_image/static/description/index.html
  pos_payment_method_image/static/description/pos_payment.png
  pos_payment_method_image/static/description/pos_payment_method_form.png
  pos_payment_method_image/static/src/css/pos_payment_method_image.css
  pos_payment_method_image/static/src/js/pos_payment_method_image.js
  pos_payment_method_image/static/src/xml/pos_payment_method_image.xml
  pos_payment_method_image/views/templates.xml
  pos_payment_method_image/views/view_pos_payment_method.xml
  setup/pos_payment_method_image/odoo/addons/pos_payment_method_image
  setup/pos_payment_method_image/setup.py
Labels: bot is merging ⏳

#673 [IMP][12.0] pos_margin: display margin on front end
  pos_margin/__manifest__.py
  pos_margin/i18n/fr.po
  pos_margin/i18n/pos_margin.pot
  pos_margin/migrations/12.0.2.0.0/pre-migration.py
  pos_margin/models/__init__.py
  pos_margin/models/pos_config.py
  pos_margin/readme/CONFIGURE.rst
  pos_margin/readme/USAGE.rst
  pos_margin/static/description/pos_config_form.png
  pos_margin/static/description/pos_front_end.png
  pos_margin/static/src/css/pos_margin.css
  pos_margin/static/src/js/models.js
  pos_margin/static/src/js/screens.js
  pos_margin/static/src/xml/pos_margin.xml
  pos_margin/views/templates.xml
  pos_margin/views/view_pos_config.xml
  pos_meal_voucher/static/src/css/pos_meal_voucher.css
  pos_meal_voucher/static/src/xml/pos_meal_voucher.xml
  pos_order_mgmt/static/src/css/pos.css
  pos_order_mgmt/static/src/xml/pos.xml
Labels: approved, bot is merging ⏳, ready to merge

#646 [ADD] pos_hide_empty_category (12.0)
  pos_hide_empty_category/README.rst
  pos_hide_empty_category/__init__.py
  pos_hide_empty_category/__manifest__.py
  pos_hide_empty_category/demo/pos_category.xml
  pos_hide_empty_category/i18n/fr.po
  pos_hide_empty_category/readme/CONTRIBUTORS.rst
  pos_hide_empty_category/readme/DESCRIPTION.rst
  pos_hide_empty_category/static/description/pos_category_tree_view.png
  pos_hide_empty_category/static/description/pos_front_ui.png
  pos_hide_empty_category/static/src/js/db.js
  pos_hide_empty_category/views/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#600 [13.0][MIG] pos quick logout
  pos_quick_logout/README.rst
  pos_quick_logout/__init__.py
  pos_quick_logout/__manifest__.py
  pos_quick_logout/i18n/ca.po
  pos_quick_logout/i18n/es.po
  pos_quick_logout/i18n/fr.po
  pos_quick_logout/i18n/hr_HR.po
  pos_quick_logout/i18n/it.po
  pos_quick_logout/i18n/nl_NL.po
  pos_quick_logout/i18n/pos_quick_logout.pot
  pos_quick_logout/models/__init__.py
  pos_quick_logout/models/pos_config.py
  pos_quick_logout/readme/CONTRIBUTORS.rst
  pos_quick_logout/readme/DESCRIPTION.rst
  pos_quick_logout/static/description/cashier_user_different.png
  pos_quick_logout/static/description/cashier_user_identical.png
  pos_quick_logout/static/description/icon.png
  pos_quick_logout/static/description/index.html
  pos_quick_logout/static/src/css/pos_quick_logout.css
  pos_quick_logout/static/src/js/pos_quick_logout.js
  pos_quick_logout/static/src/xml/pos_quick_logout.xml
  pos_quick_logout/views/assets.xml
  pos_quick_logout/views/pos_config_view.xml
  setup/pos_quick_logout/odoo/addons/pos_quick_logout
  setup/pos_quick_logout/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#676 [FIX] pos_margin : do not raise JS error if iface_display_margin is disabled, when loading point of sale
  pos_margin/static/src/js/screens.js
Labels: bot is merging ⏳

#664 [14.0][mig]pos_warning_exiting
  pos_warning_exiting/README.rst
  pos_warning_exiting/__init__.py
  pos_warning_exiting/__manifest__.py
  pos_warning_exiting/i18n/fr.po
  pos_warning_exiting/i18n/pos_warning_exiting.pot
  pos_warning_exiting/readme/CONTRIBUTORS.rst
  pos_warning_exiting/readme/DESCRIPTION.rst
  pos_warning_exiting/static/description/icon.png
  pos_warning_exiting/static/description/index.html
  pos_warning_exiting/static/description/pos_warning_connection_lost.png
  pos_warning_exiting/static/description/pos_warning_unpaid_draft_orders.png
  pos_warning_exiting/static/src/js/chrome.js
  pos_warning_exiting/views/templates.xml
  setup/pos_warning_exiting/odoo/addons/pos_warning_exiting
  setup/pos_warning_exiting/setup.py
Labels: bot is merging ⏳

#649 [14.0] [mig] pos_user_restriction
  pos_user_restriction/README.rst
  pos_user_restriction/__init__.py
  pos_user_restriction/__manifest__.py
  pos_user_restriction/i18n/es.po
  pos_user_restriction/i18n/it.po
  pos_user_restriction/i18n/pos_user_restriction.pot
  pos_user_restriction/models/__init__.py
  pos_user_restriction/models/pos_config.py
  pos_user_restriction/readme/CONFIGURE.rst
  pos_user_restriction/readme/CONTRIBUTORS.rst
  pos_user_restriction/readme/DESCRIPTION.rst
  pos_user_restriction/security/ir.model.access.csv
  pos_user_restriction/security/pos_security.xml
  pos_user_restriction/static/description/icon.png
  pos_user_restriction/static/description/index.html
  pos_user_restriction/tests/__init__.py
  pos_user_restriction/tests/test_pos_user_restriction.py
  pos_user_restriction/views/point_of_sale_views.xml
  pos_user_restriction/views/pos_config_views.xml
  setup/pos_user_restriction/odoo/addons/pos_user_restriction
  setup/pos_user_restriction/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#679 [FIX][12.0] pos_multiple_control : remove numeric_step widget for the field coin_value
  pos_multiple_control/wizard/wizard_pos_update_statement_balance.xml
Labels: approved, bot is merging ⏳
