Repository OCA/pos, pull requests merged in 2021-05, with the labels that each got.

#568 [12.0][backport] pos_timeout (from 13.0)
  pos_timeout/README.rst
  pos_timeout/__init__.py
  pos_timeout/__manifest__.py
  pos_timeout/i18n/es.po
  pos_timeout/i18n/fr.po
  pos_timeout/i18n/hr_HR.po
  pos_timeout/i18n/it.po
  pos_timeout/i18n/nl_NL.po
  pos_timeout/i18n/pos_timeout.pot
  pos_timeout/models/__init__.py
  pos_timeout/models/pos_config.py
  pos_timeout/readme/CONFIGURE.rst
  pos_timeout/readme/CONTRIBUTORS.rst
  pos_timeout/readme/CREDITS.rst
  pos_timeout/readme/DESCRIPTION.rst
  pos_timeout/static/description/icon.png
  pos_timeout/static/description/index.html
  pos_timeout/static/description/pos_config.png
  pos_timeout/static/src/js/pos_timeout.js
  pos_timeout/views/templates.xml
  pos_timeout/views/view_pos_config.xml
Labels: approved, bot is merging ⏳, ready to merge

#545 [FIX] pos_payment_change : use float_is_zero to avoid rounding error
  pos_payment_change/wizards/pos_payment_change_wizard.py
Labels: approved, bot is merging ⏳, ready to merge

#621 [14.0] [mig] pos_product_sort
  pos_product_sort/README.rst
  pos_product_sort/__init__.py
  pos_product_sort/__manifest__.py
  pos_product_sort/i18n/fr.po
  pos_product_sort/i18n/pos_product_sort.pot
  pos_product_sort/readme/CONTRIBUTORS.rst
  pos_product_sort/readme/CREDITS.rst
  pos_product_sort/readme/DESCRIPTION.rst
  pos_product_sort/readme/ROADMAP.rst
  pos_product_sort/static/description/icon.png
  pos_product_sort/static/description/index.html
  pos_product_sort/static/description/point_of_sale_name_order.png
  pos_product_sort/static/description/point_of_sale_sequence_order.png
  pos_product_sort/static/src/js/models.js
  pos_product_sort/views/assets.xml
  setup/pos_product_sort/odoo/addons/pos_product_sort
  setup/pos_product_sort/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#628 [13.0] [mig] pos_empty_home
  pos_empty_home/README.rst
  pos_empty_home/__init__.py
  pos_empty_home/__manifest__.py
  pos_empty_home/i18n/ca.po
  pos_empty_home/i18n/es.po
  pos_empty_home/i18n/fr.po
  pos_empty_home/i18n/pos_empty_home.pot
  pos_empty_home/readme/CONTRIBUTORS.rst
  pos_empty_home/readme/DESCRIPTION.rst
  pos_empty_home/static/description/icon.png
  pos_empty_home/static/description/index.html
  pos_empty_home/static/description/pos_empty_home.png
  pos_empty_home/static/src/css/pos_empty_home.css
  pos_empty_home/static/src/js/db.js
  pos_empty_home/static/src/js/screens.js
  pos_empty_home/static/src/xml/pos_empty_home.xml
  pos_empty_home/views/assets.xml
  setup/pos_empty_home/odoo/addons/pos_empty_home
  setup/pos_empty_home/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#633 [14.0] [mig] pos_require_product_quantity
  pos_require_product_quantity/README.rst
  pos_require_product_quantity/__init__.py
  pos_require_product_quantity/__manifest__.py
  pos_require_product_quantity/i18n/es.po
  pos_require_product_quantity/i18n/pos_require_product_quantity.pot
  pos_require_product_quantity/models/__init__.py
  pos_require_product_quantity/models/pos_config.py
  pos_require_product_quantity/readme/CONTRIBUTORS.rst
  pos_require_product_quantity/readme/DESCRIPTION.rst
  pos_require_product_quantity/static/description/icon.png
  pos_require_product_quantity/static/description/index.html
  pos_require_product_quantity/static/src/js/screens.js
  pos_require_product_quantity/views/assets.xml
  pos_require_product_quantity/views/pos_config.xml
  setup/pos_require_product_quantity/odoo/addons/pos_require_product_quantity
  setup/pos_require_product_quantity/setup.py
Labels: bot is merging ⏳, needs review

#625 [13.0] [mig] pos_fix_search_limit
  pos_fix_search_limit/README.rst
  pos_fix_search_limit/__init__.py
  pos_fix_search_limit/__manifest__.py
  pos_fix_search_limit/i18n/es.po
  pos_fix_search_limit/i18n/pos_fix_search_limit.pot
  pos_fix_search_limit/readme/CONTRIBUTORS.rst
  pos_fix_search_limit/readme/CREDITS.rst
  pos_fix_search_limit/readme/DESCRIPTION.rst
  pos_fix_search_limit/readme/HISTORY.rst
  pos_fix_search_limit/readme/ROADMAP.rst
  pos_fix_search_limit/readme/USAGE.rst
  pos_fix_search_limit/static/description/icon.png
  pos_fix_search_limit/static/description/index.html
  pos_fix_search_limit/static/src/js/pos_fix_search_limit.js
  pos_fix_search_limit/views/pos_fix_limit.xml
  setup/pos_fix_search_limit/odoo/addons/pos_fix_search_limit
  setup/pos_fix_search_limit/setup.py
Labels: bot is merging ⏳, needs review

#640 [FIX][13.0][pos_order_remove_line] Use scss stylesheet instead of less
  pos_order_remove_line/readme/CONTRIBUTORS.rst
  pos_order_remove_line/static/src/css/order_line.scss
  pos_order_remove_line/views/assets.xml
Labels: approved, bot is merging ⏳

#620 [14.0] [mig] pos_timeout
  pos_timeout/README.rst
  pos_timeout/__init__.py
  pos_timeout/__manifest__.py
  pos_timeout/i18n/ca.po
  pos_timeout/i18n/es.po
  pos_timeout/i18n/fr.po
  pos_timeout/i18n/hr_HR.po
  pos_timeout/i18n/it.po
  pos_timeout/i18n/nl_NL.po
  pos_timeout/i18n/pos_timeout.pot
  pos_timeout/models/__init__.py
  pos_timeout/models/pos_config.py
  pos_timeout/readme/CONFIGURE.rst
  pos_timeout/readme/CONTRIBUTORS.rst
  pos_timeout/readme/CREDITS.rst
  pos_timeout/readme/DESCRIPTION.rst
  pos_timeout/static/description/icon.png
  pos_timeout/static/description/index.html
  pos_timeout/static/description/pos_config.png
  pos_timeout/static/src/js/pos_timeout.js
  pos_timeout/views/templates.xml
  pos_timeout/views/view_pos_config.xml
  setup/pos_timeout/odoo/addons/pos_timeout
  setup/pos_timeout/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#551 [FIX] pos_invoicing: set copy=False ; do not raise an error if name is not defined
  pos_invoicing/models/account_invoice.py
Labels: approved, bot is merging ⏳

#607 [13.0] pos_payment_terminal: backport from 14.0
  .prettierrc.yml
  pos_payment_terminal/README.rst
  pos_payment_terminal/__init__.py
  pos_payment_terminal/__manifest__.py
  pos_payment_terminal/i18n/es.po
  pos_payment_terminal/i18n/fr.po
  pos_payment_terminal/i18n/hr_HR.po
  pos_payment_terminal/i18n/it.po
  pos_payment_terminal/i18n/nl_NL.po
  pos_payment_terminal/i18n/pos_payment_terminal.pot
  pos_payment_terminal/models/__init__.py
  pos_payment_terminal/models/pos_payment_method.py
  pos_payment_terminal/readme/CONFIGURE.rst
  pos_payment_terminal/readme/CONTRIBUTORS.rst
  pos_payment_terminal/readme/DESCRIPTION.rst
  pos_payment_terminal/readme/INSTALL.rst
  pos_payment_terminal/readme/USAGE.rst
  pos_payment_terminal/static/description/icon.png
  pos_payment_terminal/static/description/index.html
  pos_payment_terminal/static/description/pos_payment_method_form.png
  pos_payment_terminal/static/src/js/models.js
  pos_payment_terminal/static/src/js/payment_terminal.js
  pos_payment_terminal/views/assets.xml
  pos_payment_terminal/views/pos_payment_method.xml
  setup/pos_payment_terminal/odoo/addons/pos_payment_terminal
  setup/pos_payment_terminal/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#548 [ADD] migration script
  pos_journal_image/migrations/12.0.1.0.1/post-migration.py
  pos_journal_image/migrations/12.0.1.0.1/pre-migration.py
Labels: bot is merging ⏳

#565 [FIX] pos_meal_voucher: remove unoverloadable function.
  pos_meal_voucher/static/src/js/screens.js
Labels: bot is merging ⏳

#581 [FIX] pos_payment_change : Add ondelete cascade to avoid error when cleaning transient model tables
  pos_payment_change/wizards/pos_payment_change_wizard_new_line.py
  pos_payment_change/wizards/pos_payment_change_wizard_old_line.py
Labels: bot is merging ⏳

#569 [ADD] new module pos_cash_control_multiple_config to handle correctly cash control in a multi point of sale context
  pos_cash_control_multiple_config/README.rst
  pos_cash_control_multiple_config/__init__.py
  pos_cash_control_multiple_config/__manifest__.py
  pos_cash_control_multiple_config/models/__init__.py
  pos_cash_control_multiple_config/models/account_bank_statement.py
  pos_cash_control_multiple_config/models/pos_session.py
  pos_cash_control_multiple_config/readme/CONTRIBUTORS.rst
  pos_cash_control_multiple_config/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#539 [12.0][FIX] pos order to sale order : dependencies and compatibility with pos_restaurant
  pos_order_to_sale_order/__manifest__.py
  pos_order_to_sale_order/static/src/js/screens.js
Labels: bot is merging ⏳

#591 [ADD] pos_warning_exiting : new module to add extra checks before exiting from Point of sale Front office UI
  pos_warning_exiting/README.rst
  pos_warning_exiting/__init__.py
  pos_warning_exiting/__manifest__.py
  pos_warning_exiting/i18n/fr.po
  pos_warning_exiting/readme/CONTRIBUTORS.rst
  pos_warning_exiting/readme/DESCRIPTION.rst
  pos_warning_exiting/static/description/pos_warning_connection_lost.png
  pos_warning_exiting/static/description/pos_warning_unpaid_draft_orders.png
  pos_warning_exiting/static/src/js/gui.js
  pos_warning_exiting/views/templates.xml
Labels: bot is merging ⏳, needs review

#567 [IMP] pos_meal_voucher : do not display meal voucher features, if there are no meal voucher journal
  pos_meal_voucher/models/pos_config.py
  pos_meal_voucher/static/src/js/screens.js
  pos_meal_voucher/static/src/xml/pos_meal_voucher.xml
Labels: bot is merging ⏳

#645 [FIX] pos_meal_voucher: 2 fixes & improve code coverage.
  pos_meal_voucher/models/__init__.py
  pos_meal_voucher/models/product_product.py
  pos_meal_voucher/models/product_template.py
  pos_meal_voucher/tests/__init__.py
  pos_meal_voucher/tests/test_module.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#630 [14.0] [mig] pos_access_right
  pos_access_right/README.rst
  pos_access_right/__init__.py
  pos_access_right/__manifest__.py
  pos_access_right/demo/res_groups.xml
  pos_access_right/i18n/ar.po
  pos_access_right/i18n/ca.po
  pos_access_right/i18n/es.po
  pos_access_right/i18n/fr.po
  pos_access_right/i18n/pos_access_right.pot
  pos_access_right/i18n/ru.po
  pos_access_right/models/__init__.py
  pos_access_right/models/pos_config.py
  pos_access_right/readme/CONFIGURE.rst
  pos_access_right/readme/CONTRIBUTORS.rst
  pos_access_right/readme/DESCRIPTION.rst
  pos_access_right/readme/USAGE.rst
  pos_access_right/security/res_groups.xml
  pos_access_right/static/description/admin_numpad.png
  pos_access_right/static/description/demo_error.png
  pos_access_right/static/description/demo_numpad.png
  pos_access_right/static/description/icon.png
  pos_access_right/static/description/new_groups.png
  pos_access_right/static/src/css/pos.css
  pos_access_right/static/src/js/ActionpadWidget.js
  pos_access_right/static/src/js/NumpadWidget.js
  pos_access_right/static/src/js/TicketScreen.js
  pos_access_right/static/src/js/models.js
  pos_access_right/static/src/xml/ActionpadWidget.xml
  pos_access_right/static/src/xml/NumpadWidget.xml
  pos_access_right/static/src/xml/TicketScreen.xml
  pos_access_right/tests/__init__.py
  pos_access_right/tests/test_pos_access_right.py
  pos_access_right/views/templates.xml
  setup/pos_access_right/odoo/addons/pos_access_right
  setup/pos_access_right/setup.py
Labels: bot is merging ⏳, needs review
