Repository OCA/pos, pull requests merged in 2021-11, with the labels that each got.

#667 [13.0][ADD] pos_event_sale
  pos_event_sale/__init__.py
  pos_event_sale/__manifest__.py
  pos_event_sale/models/__init__.py
  pos_event_sale/models/event_registration.py
  pos_event_sale/models/pos_config.py
  pos_event_sale/models/pos_order.py
  pos_event_sale/models/pos_order_line.py
  pos_event_sale/readme/CONFIGURE.rst
  pos_event_sale/readme/CONTRIBUTORS.rst
  pos_event_sale/readme/DESCRIPTION.rst
  pos_event_sale/readme/ROADMAP.rst
  pos_event_sale/readme/USAGE.rst
  pos_event_sale/report/__init__.py
  pos_event_sale/report/pos_order_report.py
  pos_event_sale/security/security.xml
  pos_event_sale/static/description/add_event_button.png
  pos_event_sale/static/description/event_calendar.png
  pos_event_sale/static/description/ticket_selector.png
  pos_event_sale/static/src/css/pos_event_sale.scss
  pos_event_sale/static/src/js/db.js
  pos_event_sale/static/src/js/models.js
  pos_event_sale/static/src/js/models/Order.js
  pos_event_sale/static/src/js/models/Orderline.js
  pos_event_sale/static/src/js/models/PosModel.js
  pos_event_sale/static/src/js/popups/EventSelectorPopup.js
  pos_event_sale/static/src/js/popups/EventTicketsPopup.js
  pos_event_sale/static/src/js/screens.js
  pos_event_sale/static/src/js/tours/TourBasic.js
  pos_event_sale/static/src/js/tours/tour.utils.js
  pos_event_sale/static/src/xml/EventSelectorPopup.xml
  pos_event_sale/static/src/xml/EventTicketsPopup.xml
  pos_event_sale/static/src/xml/popups.xml
  pos_event_sale/static/src/xml/pos.xml
  pos_event_sale/static/src/xml/screens.xml
  pos_event_sale/tests/__init__.py
  pos_event_sale/tests/test_frontend.py
  pos_event_sale/views/assets.xml
  pos_event_sale/views/event_registration.xml
  pos_event_sale/views/pos_config.xml
  pos_event_sale/views/pos_order.xml
  setup/pos_event_sale/odoo/addons/pos_event_sale
  setup/pos_event_sale/setup.py
Labels: approved, needs review, bot is merging ⏳

#316 11.0 mig pos default payment method
  pos_default_payment_method/README.rst
  pos_default_payment_method/__init__.py
  pos_default_payment_method/__manifest__.py
  pos_default_payment_method/i18n/es.po
  pos_default_payment_method/i18n/fr.po
  pos_default_payment_method/i18n/hr_HR.po
  pos_default_payment_method/i18n/it.po
  pos_default_payment_method/i18n/nl_NL.po
  pos_default_payment_method/i18n/pos_default_payment_method.pot
  pos_default_payment_method/images/module_installed.png
  pos_default_payment_method/images/standard.png
  pos_default_payment_method/models/__init__.py
  pos_default_payment_method/models/pos_config.py
  pos_default_payment_method/static/src/js/pos_default_payment_method.js
  pos_default_payment_method/tests/__init__.py
  pos_default_payment_method/tests/test_constrain.py
  pos_default_payment_method/views/assets.xml
  pos_default_payment_method/views/pos_config_view.xml
  pos_session_pay_invoice/__init__.py
  pos_session_pay_invoice/__manifest__.py
  pos_session_pay_invoice/tests/__init__.py
  pos_session_pay_invoice/tests/test_pay_invoice.py
  pos_session_pay_invoice/wizard/__init__.py
  pos_session_pay_invoice/wizard/cash_invoice_in.py
  pos_session_pay_invoice/wizard/cash_invoice_out.py
Labels: bot is merging ⏳, stale

#717 [14.0] [mig] pos_supplierinfo_barcode
  pos_supplierinfo_barcode/README.rst
  pos_supplierinfo_barcode/__init__.py
  pos_supplierinfo_barcode/__manifest__.py
  pos_supplierinfo_barcode/i18n/es.po
  pos_supplierinfo_barcode/i18n/pos_supplierinfo_barcode.pot
  pos_supplierinfo_barcode/models/__init__.py
  pos_supplierinfo_barcode/models/product.py
  pos_supplierinfo_barcode/readme/CONFIGURE.rst
  pos_supplierinfo_barcode/readme/CONTRIBUTORS.rst
  pos_supplierinfo_barcode/readme/DESCRIPTION.rst
  pos_supplierinfo_barcode/readme/USAGE.rst
  pos_supplierinfo_barcode/static/description/icon.png
  pos_supplierinfo_barcode/static/description/index.html
  pos_supplierinfo_barcode/static/src/js/db.js
  pos_supplierinfo_barcode/views/assets.xml
  setup/pos_supplierinfo_barcode/odoo/addons/pos_supplierinfo_barcode
  setup/pos_supplierinfo_barcode/setup.py
Labels: approved, bot is merging ⏳

#727 [UPD] Update copier template answers
  .copier-answers.yml
  README.md
Labels: bot is merging ⏳

#674 [MIG] pos_session_pay_invoice: Migration to 13.0
  oca_dependencies.txt
  pos_session_pay_invoice/README.rst
  pos_session_pay_invoice/__init__.py
  pos_session_pay_invoice/__manifest__.py
  pos_session_pay_invoice/i18n/es.po
  pos_session_pay_invoice/i18n/fr.po
  pos_session_pay_invoice/i18n/pos_session_pay_invoice.pot
  pos_session_pay_invoice/readme/CONFIGURE.rst
  pos_session_pay_invoice/readme/CONTRIBUTORS.rst
  pos_session_pay_invoice/readme/DESCRIPTION.rst
  pos_session_pay_invoice/readme/ROADMAP.rst
  pos_session_pay_invoice/readme/USAGE.rst
  pos_session_pay_invoice/static/description/icon.png
  pos_session_pay_invoice/static/description/index.html
  pos_session_pay_invoice/tests/__init__.py
  pos_session_pay_invoice/tests/test_pay_invoice.py
  pos_session_pay_invoice/views/pos_session.xml
  pos_session_pay_invoice/wizard/__init__.py
  pos_session_pay_invoice/wizard/cash_invoice_in.py
  pos_session_pay_invoice/wizard/cash_invoice_in.xml
  pos_session_pay_invoice/wizard/pos_box_cash_invoice_in.py
  pos_session_pay_invoice/wizard/pos_box_cash_invoice_in.xml
  pos_session_pay_invoice/wizard/pos_box_cash_invoice_out.py
  pos_session_pay_invoice/wizard/pos_box_cash_invoice_out.xml
  setup/pos_session_pay_invoice/odoo/addons/pos_session_pay_invoice
  setup/pos_session_pay_invoice/setup.py
Labels: approved, bot is merging ⏳
