Repository OCA/pos, pull requests merged in 2022-03, with the labels that each got.

#761 [13.0][MIG] pos_picking_delayed: Migration to 13.0
  oca_dependencies.txt
  pos_picking_delayed/README.rst
  pos_picking_delayed/__init__.py
  pos_picking_delayed/__manifest__.py
  pos_picking_delayed/data/queue_job_channel.xml
  pos_picking_delayed/data/queue_job_function.xml
  pos_picking_delayed/demo/pos_config.xml
  pos_picking_delayed/i18n/es.po
  pos_picking_delayed/i18n/fr.po
  pos_picking_delayed/i18n/pos_picking_delayed.pot
  pos_picking_delayed/models/__init__.py
  pos_picking_delayed/models/pos_config.py
  pos_picking_delayed/models/pos_order.py
  pos_picking_delayed/readme/CONFIGURE.rst
  pos_picking_delayed/readme/CONTRIBUTORS.rst
  pos_picking_delayed/readme/CREDITS.rst
  pos_picking_delayed/readme/DESCRIPTION.rst
  pos_picking_delayed/readme/USAGE.rst
  pos_picking_delayed/static/description/icon.png
  pos_picking_delayed/static/description/index.html
  pos_picking_delayed/static/description/pos_config_form.png
  pos_picking_delayed/static/description/pos_order_tree.png
  pos_picking_delayed/tests/__init__.py
  pos_picking_delayed/tests/test_module.py
  pos_picking_delayed/views/view_pos_config.xml
  pos_picking_delayed/views/view_pos_order.xml
  setup/pos_picking_delayed/odoo/addons/pos_picking_delayed
  setup/pos_picking_delayed/setup.py
Labels: approved, bot is merging ⏳

#760 [13.0] [MIG] pos_stock_picking_invoice_link: Migration to 13.0
  oca_dependencies.txt
  pos_stock_picking_invoice_link/README.rst
  pos_stock_picking_invoice_link/__init__.py
  pos_stock_picking_invoice_link/__manifest__.py
  pos_stock_picking_invoice_link/i18n/es.po
  pos_stock_picking_invoice_link/i18n/pos_stock_picking_invoice_link.pot
  pos_stock_picking_invoice_link/models/__init__.py
  pos_stock_picking_invoice_link/models/pos_order.py
  pos_stock_picking_invoice_link/models/stock_move.py
  pos_stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  pos_stock_picking_invoice_link/readme/DESCRIPTION.rst
  pos_stock_picking_invoice_link/readme/USAGE.rst
  pos_stock_picking_invoice_link/static/description/icon.png
  pos_stock_picking_invoice_link/static/description/index.html
  pos_stock_picking_invoice_link/tests/__init__.py
  pos_stock_picking_invoice_link/tests/test_point_of_sale_stock_invoice_link.py
  setup/pos_stock_picking_invoice_link/odoo/addons/pos_stock_picking_invoice_link
  setup/pos_stock_picking_invoice_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#740 [ADD][12.0] pos_cash_move_reason_multiple_control
  pos_cash_move_reason/wizard/wizard_pos_move_reason.xml
  pos_cash_move_reason_multiple_control/README.rst
  pos_cash_move_reason_multiple_control/__init__.py
  pos_cash_move_reason_multiple_control/__manifest__.py
  pos_cash_move_reason_multiple_control/i18n/fr.po
  pos_cash_move_reason_multiple_control/readme/CONTRIBUTORS.rst
  pos_cash_move_reason_multiple_control/readme/DESCRIPTION.rst
  pos_cash_move_reason_multiple_control/static/description/wizard_pos_move_reason_form.png
  pos_cash_move_reason_multiple_control/wizard/__init__.py
  pos_cash_move_reason_multiple_control/wizard/wizard_pos_move_reason.py
  pos_cash_move_reason_multiple_control/wizard/wizard_pos_move_reason.xml
Labels: bot is merging ⏳
