Repository OCA/pos, pull requests merged in 2022-05, with the labels that each got.

#788 [14.0][ADD] pos_disable_pricelist_selection
  pos_disable_pricelist_selection/README.rst
  pos_disable_pricelist_selection/__init__.py
  pos_disable_pricelist_selection/__manifest__.py
  pos_disable_pricelist_selection/models/__init__.py
  pos_disable_pricelist_selection/models/pos_config.py
  pos_disable_pricelist_selection/readme/CONFIGURE.rst
  pos_disable_pricelist_selection/readme/CONTRIBUTORS.rst
  pos_disable_pricelist_selection/readme/DESCRIPTION.rst
  pos_disable_pricelist_selection/readme/HISTORY.rst
  pos_disable_pricelist_selection/readme/USAGE.rst
  pos_disable_pricelist_selection/static/description/icon.png
  pos_disable_pricelist_selection/static/src/js/ProductScreen.js
  pos_disable_pricelist_selection/static/src/xml/ClientDetailsEdit.xml
  pos_disable_pricelist_selection/views/assets.xml
  pos_disable_pricelist_selection/views/pos_config_view.xml
  setup/pos_disable_pricelist_selection/odoo/addons/pos_disable_pricelist_selection
  setup/pos_disable_pricelist_selection/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#783 [ADD] new pos_margin_account_invoice_margin glue module
  oca_dependencies.txt
  pos_margin_account_invoice_margin/README.rst
  pos_margin_account_invoice_margin/__init__.py
  pos_margin_account_invoice_margin/__manifest__.py
  pos_margin_account_invoice_margin/models/__init__.py
  pos_margin_account_invoice_margin/models/pos_order.py
  pos_margin_account_invoice_margin/post_install.py
  pos_margin_account_invoice_margin/readme/CONTRIBUTORS.rst
  pos_margin_account_invoice_margin/readme/DESCRIPTION.rst
  pos_margin_account_invoice_margin/tests/__init__.py
  pos_margin_account_invoice_margin/tests/test_module.py
Labels: approved, bot is merging ⏳

#794 [14.0] Copier update and fix pre-commit build
  .copier-answers.yml
  .pylintrc
  .pylintrc-mandatory
  pos_disable_pricelist_selection/README.rst
  pos_disable_pricelist_selection/readme/CONFIGURE.rst
  pos_disable_pricelist_selection/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#741 [14.0][IMP] pos_payment_terminal: Graceful cancel handling
  pos_payment_terminal/static/src/js/payment_terminal.js
Labels: approved, bot is merging ⏳

#795 [13.0] [UPD] Use copier template and Github Actions
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  pos_event_sale/__manifest__.py
  pos_fix_search_limit/__manifest__.py
  pos_fixed_discount/__manifest__.py
  pos_order_remove_line/__manifest__.py
  pos_payment_method_image/__manifest__.py
  pos_picking_delayed/__manifest__.py
  pos_timeout/__manifest__.py
Labels: bot is merging ⏳

#708 [13.0][FIX] pos_payment_terminal: Graceful cancel handling
  pos_payment_terminal/static/src/js/payment_terminal.js
Labels: approved, ready to merge, bot is merging ⏳

#774 [FIX] pos_cash_move_reason
  pos_cash_move_reason/wizard/wizard_pos_move_reason.py
Labels: approved, ready to merge, bot is merging ⏳

#768 [ADD] 14.0 pos_product_multi_barcode
  pos_product_multi_barcode/__init__.py
  pos_product_multi_barcode/__manifest__.py
  pos_product_multi_barcode/models/__init__.py
  pos_product_multi_barcode/models/product.py
  pos_product_multi_barcode/readme/DESCRIPTION.rst
  pos_product_multi_barcode/static/src/js/db.js
  pos_product_multi_barcode/templates/assets.xml
  setup/pos_product_multi_barcode/odoo/addons/pos_product_multi_barcode
  setup/pos_product_multi_barcode/setup.py
Labels: approved, bot is merging ⏳
