Repository OCA/pos, pull requests merged in 2022-06, with the labels that each got.

#792 [15.0] [ADD] `pos_event_sale_registration_qr_code`
  pos_event_sale_registration_qr_code/README.rst
  pos_event_sale_registration_qr_code/__init__.py
  pos_event_sale_registration_qr_code/__manifest__.py
  pos_event_sale_registration_qr_code/readme/CONTRIBUTORS.rst
  pos_event_sale_registration_qr_code/readme/DESCRIPTION.rst
  pos_event_sale_registration_qr_code/static/src/xml/EventRegistrationReceipt.xml
  setup/pos_event_sale_registration_qr_code/odoo/addons/pos_event_sale_registration_qr_code
  setup/pos_event_sale_registration_qr_code/setup.py
Labels: needs review, bot is merging ⏳

#801 [14.0][FIX] pos_product_multi_barcode: enable feature to search for p…
  pos_product_multi_barcode/readme/CONTRIBUTORS.rst
  pos_product_multi_barcode/static/src/js/db.js
Labels: approved, bot is merging ⏳

#796 [ADD] add new module: pos_edit_order
  pos_edit_order_line/README.rst
  pos_edit_order_line/__init__.py
  pos_edit_order_line/__manifest__.py
  pos_edit_order_line/models/__init__.py
  pos_edit_order_line/models/pos_config.py
  pos_edit_order_line/readme/CONFIGURE.rst
  pos_edit_order_line/readme/CONTRIBUTORS.rst
  pos_edit_order_line/readme/DESCRIPTION.rst
  pos_edit_order_line/readme/HISTORY.rst
  pos_edit_order_line/static/description/icon.png
  pos_edit_order_line/static/description/pos_edit_order_line.png
  pos_edit_order_line/static/src/css/pos.css
  pos_edit_order_line/static/src/js/EditOrderButton.js
  pos_edit_order_line/static/src/js/EditOrderLineInput.js
  pos_edit_order_line/static/src/js/EditOrderPopup.js
  pos_edit_order_line/static/src/xml/EditOrderButton.xml
  pos_edit_order_line/static/src/xml/EditOrderLineInput.xml
  pos_edit_order_line/static/src/xml/EditOrderPopup.xml
  pos_edit_order_line/views/assets.xml
  pos_edit_order_line/views/pos_config_view.xml
  setup/pos_edit_order_line/odoo/addons/pos_edit_order_line
  setup/pos_edit_order_line/setup.py
Labels: approved, ready to merge, bot is merging ⏳
