Repository OCA/pos, pull requests merged in 2022-04, with the labels that each got.

#771 14.0 meta update copier 2022 03 29
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  pos_order_return/__manifest__.py
  pos_order_return/tests/test_pos_order_return.py
Labels: approved, bot is merging ⏳

#772 [ADD] pos_customer_required_fields
  pos_customer_required_fields/README.rst
  pos_customer_required_fields/__init__.py
  pos_customer_required_fields/__manifest__.py
  pos_customer_required_fields/i18n/fr.po
  pos_customer_required_fields/i18n/pos_customer_required_fields.pot
  pos_customer_required_fields/models/__init__.py
  pos_customer_required_fields/models/pos_config.py
  pos_customer_required_fields/models/res_partner.py
  pos_customer_required_fields/readme/CONFIGURE.rst
  pos_customer_required_fields/readme/CONTRIBUTORS.rst
  pos_customer_required_fields/readme/DESCRIPTION.rst
  pos_customer_required_fields/readme/USAGE.rst
  pos_customer_required_fields/static/description/icon.png
  pos_customer_required_fields/static/description/index.html
  pos_customer_required_fields/static/description/pos_customer_missing_fields.png
  pos_customer_required_fields/static/description/pos_edit_customer.png
  pos_customer_required_fields/static/src/css/pos.css
  pos_customer_required_fields/static/src/js/screens.js
  pos_customer_required_fields/static/src/xml/pos.xml
  pos_customer_required_fields/templates/assets.xml
  pos_customer_required_fields/tests/__init__.py
  pos_customer_required_fields/tests/test_res_partner.py
  pos_customer_required_fields/views/view_pos_config.xml
Labels: approved, bot is merging ⏳

#745 [FIX] 14.0 pos_report_session_summary: do not crash if statement data is missing
  pos_report_session_summary/views/report_session_summary.xml
Labels: approved, ready to merge, bot is merging ⏳

#780 [FIX] #777 pos_customer_required_fields
  pos_customer_required_fields/static/src/js/screens.js
Labels: approved, bot is merging ⏳

#779 [13.0][MIG][pos_customer_required] Migrated to v13.0
  pos_customer_required/README.rst
  pos_customer_required/__init__.py
  pos_customer_required/__manifest__.py
  pos_customer_required/i18n/ca.po
  pos_customer_required/i18n/es.po
  pos_customer_required/i18n/fr.po
  pos_customer_required/i18n/nl_NL.po
  pos_customer_required/i18n/pos_customer_required.pot
  pos_customer_required/models/__init__.py
  pos_customer_required/models/pos_config.py
  pos_customer_required/models/pos_make_payment.py
  pos_customer_required/models/pos_order.py
  pos_customer_required/readme/CONFIGURE.rst
  pos_customer_required/readme/CONTRIBUTORS.rst
  pos_customer_required/readme/DESCRIPTION.rst
  pos_customer_required/readme/USAGE.rst
  pos_customer_required/static/description/frontend_pos_error_message.png
  pos_customer_required/static/description/icon.png
  pos_customer_required/static/description/index.html
  pos_customer_required/static/src/js/gui.js
  pos_customer_required/static/src/js/screens.js
  pos_customer_required/tests/__init__.py
  pos_customer_required/tests/test_pos.py
  pos_customer_required/views/assets.xml
  pos_customer_required/views/pos_config_view.xml
  pos_customer_required/views/pos_order_view.xml
Labels: approved, bot is merging ⏳

#775 [14.0] [mig] pos_partner_firstname
  oca_dependencies.txt
  pos_partner_firstname/README.rst
  pos_partner_firstname/__init__.py
  pos_partner_firstname/__manifest__.py
  pos_partner_firstname/i18n/ca.po
  pos_partner_firstname/i18n/ca_ES.po
  pos_partner_firstname/i18n/es.po
  pos_partner_firstname/i18n/fr_CH.po
  pos_partner_firstname/i18n/it.po
  pos_partner_firstname/i18n/pos_partner_firstname.pot
  pos_partner_firstname/models/__init__.py
  pos_partner_firstname/models/res_partner.py
  pos_partner_firstname/readme/CONTRIBUTORS.rst
  pos_partner_firstname/readme/DESCRIPTION.rst
  pos_partner_firstname/readme/ROADMAP.rst
  pos_partner_firstname/static/description/icon.png
  pos_partner_firstname/static/description/index.html
  pos_partner_firstname/static/src/js/ClientDetailsEdit.js
  pos_partner_firstname/static/src/js/ClientScreen.js
  pos_partner_firstname/static/src/js/models.js
  pos_partner_firstname/static/src/xml/pos.xml
  pos_partner_firstname/views/assets.xml
  setup/pos_partner_firstname/odoo/addons/pos_partner_firstname
  setup/pos_partner_firstname/setup.py
Labels: bot is merging ⏳

#763 [FIX] pos_customer_display and pos_payment_terminal : disable use_proxy on demo data
  pos_customer_display/__manifest__.py
  pos_customer_display/demo/pos_config.xml
  pos_payment_terminal/__manifest__.py
  pos_payment_terminal/demo/pos_config.xml
Labels: approved, ready to merge, bot is merging ⏳

#749 [14.0][FIX] pos_reset_search: Iterate on owl children
  pos_reset_search/static/src/js/ProductScreen.js
Labels: approved, bot is merging ⏳

#776 [ADD] pos_hide_cost_price_and_margin: Add to 15.0
  pos_hide_cost_price_and_margin/README.rst
  pos_hide_cost_price_and_margin/__manifest__.py
  pos_hide_cost_price_and_margin/readme/CONTRIBUTORS.rst
  pos_hide_cost_price_and_margin/readme/CREDITS.rst
  pos_hide_cost_price_and_margin/readme/DESCRIPTION.rst
  pos_hide_cost_price_and_margin/readme/HISTORY.rst
  pos_hide_cost_price_and_margin/static/description/icon.png
  pos_hide_cost_price_and_margin/static/description/index.html
  pos_hide_cost_price_and_margin/static/src/xml/pos_margin.xml
  setup/pos_hide_cost_price_and_margin/odoo/addons/pos_hide_cost_price_and_margin
  setup/pos_hide_cost_price_and_margin/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#726 [ADD] new module pos_prevent_double_closing
  pos_prevent_double_closing/README.rst
  pos_prevent_double_closing/__init__.py
  pos_prevent_double_closing/__manifest__.py
  pos_prevent_double_closing/i18n/fr.po
  pos_prevent_double_closing/models/__init__.py
  pos_prevent_double_closing/models/pos_session.py
  pos_prevent_double_closing/readme/CONTRIBUTORS.rst
  pos_prevent_double_closing/readme/DESCRIPTION.rst
  pos_prevent_double_closing/static/description/duplicated_entries.png
  pos_prevent_double_closing/tests/__init__.py
  pos_prevent_double_closing/tests/test_module.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#742 [IMP] pos_cash_move_reason : display cash moves on PoS session summary
  pos_cash_move_reason/i18n/fr.po
  pos_cash_move_reason/i18n/pos_cash_move_reason.pot
  pos_cash_move_reason/models/pos_session.py
  pos_cash_move_reason/readme/USAGE.rst
  pos_cash_move_reason/static/description/pos_session_move_list_form.png
  pos_cash_move_reason/tests/test_pos_cash_move_reason.py
  pos_cash_move_reason/views/view_pos_session.xml
  pos_multiple_control/views/view_pos_session.xml
Labels: bot is merging ⏳
