Repository OCA/pos, pull requests merged in 2022-10, with the labels that each got.

#848 [15.0] [FIX] `pos_event_sale`: `event_barcode` compatibility (enterprise)
  pos_event_sale/static/src/xml/ReceiptScreen/EventRegistrationReceipt.xml
Labels: bot is merging ⏳

#854 16.0 mig pos order to sale order
  pos_order_to_sale_order/README.rst
  pos_order_to_sale_order/__init__.py
  pos_order_to_sale_order/__manifest__.py
  pos_order_to_sale_order/i18n/es.po
  pos_order_to_sale_order/i18n/fr.po
  pos_order_to_sale_order/i18n/pos_order_to_sale_order.pot
  pos_order_to_sale_order/i18n/pt_BR.po
  pos_order_to_sale_order/models/__init__.py
  pos_order_to_sale_order/models/pos_config.py
  pos_order_to_sale_order/models/res_config_settings.py
  pos_order_to_sale_order/models/sale_order.py
  pos_order_to_sale_order/models/sale_order_line.py
  pos_order_to_sale_order/readme/CONFIGURE.rst
  pos_order_to_sale_order/readme/CONTRIBUTORS.rst
  pos_order_to_sale_order/readme/DESCRIPTION.rst
  pos_order_to_sale_order/readme/DEVELOP.rst
  pos_order_to_sale_order/readme/USAGE.rst
  pos_order_to_sale_order/static/description/icon.png
  pos_order_to_sale_order/static/description/index.html
  pos_order_to_sale_order/static/description/pos_frontend_button.png
  pos_order_to_sale_order/static/description/pos_frontend_popup.png
  pos_order_to_sale_order/static/description/res_config_settings_form.png
  pos_order_to_sale_order/static/src/css/pos.css
  pos_order_to_sale_order/static/src/js/CreateOrderButton.js
  pos_order_to_sale_order/static/src/js/CreateOrderPopup.js
  pos_order_to_sale_order/static/src/xml/CreateOrderButton.xml
  pos_order_to_sale_order/static/src/xml/CreateOrderPopup.xml
  pos_order_to_sale_order/tests/__init__.py
  pos_order_to_sale_order/tests/test_module.py
  pos_order_to_sale_order/tests/tours/PosOrderToSaleOrderTour.tour.js
  pos_order_to_sale_order/views/view_res_config_settings.xml
  setup/pos_order_to_sale_order/odoo/addons/pos_order_to_sale_order
  setup/pos_order_to_sale_order/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#828 [14.0][ADD] pos_product_template_configurator: Add new module
  pos_product_template_configurator/README.rst
  pos_product_template_configurator/__init__.py
  pos_product_template_configurator/__manifest__.py
  pos_product_template_configurator/readme/CONFIGURE.rst
  pos_product_template_configurator/readme/CONTRIBUTORS.rst
  pos_product_template_configurator/readme/DESCRIPTION.rst
  pos_product_template_configurator/readme/ROADMAP.rst
  pos_product_template_configurator/static/description/icon.png
  pos_product_template_configurator/static/img/configurator.png
  pos_product_template_configurator/static/src/js/ProductConfiguratorPopup.js
  pos_product_template_configurator/static/src/js/SelectVariantPopup.js
  pos_product_template_configurator/static/src/js/models.js
  pos_product_template_configurator/static/src/js/ppt.js
  pos_product_template_configurator/static/src/xml/SelectVariantPopup.xml
  pos_product_template_configurator/views/assets.xml
  setup/pos_product_template_configurator/odoo/addons/pos_product_template_configurator
  setup/pos_product_template_configurator/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#826 [15.0] Add module pos_lot_barcode
  pos_lot_barcode/README.rst
  pos_lot_barcode/__init__.py
  pos_lot_barcode/__manifest__.py
  pos_lot_barcode/readme/CONFIGURATION.rst
  pos_lot_barcode/readme/CONTRIBUTORS.rst
  pos_lot_barcode/readme/DESCRIPTION.rst
  pos_lot_barcode/static/src/js/Popups/EditListPopup.js
  pos_lot_barcode/static/src/js/Popups/ErrorMultiLotBarcodePopup.js
  pos_lot_barcode/static/src/js/Screens/ProductScreen.js
  pos_lot_barcode/static/src/xml/Popups/ErrorMultiLotBarcodePopup.xml
  setup/pos_lot_barcode/odoo/addons/pos_lot_barcode
  setup/pos_lot_barcode/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#855 [IMP][14.0] pos_user_restriction
  pos_user_restriction/readme/ROADMAP.rst
Labels: approved, ready to merge, bot is merging ⏳

#862 [12.0][FIX] pos_payment_method_cashdro: floating point quirks
  pos_payment_method_cashdro/static/src/js/screens.js
Labels: approved, bot is merging ⏳
