Repository OCA/pos, pull requests merged in 2022-07, with the labels that each got.

#800 [14.0][MIG] pos_product_template: Migration to 14.0
  pos_product_template/README.rst
  pos_product_template/__init__.py
  pos_product_template/__manifest__.py
  pos_product_template/demo/product_attribute_value.xml
  pos_product_template/demo/product_product.xml
  pos_product_template/i18n/es.po
  pos_product_template/i18n/fr.po
  pos_product_template/i18n/pos_product_template.pot
  pos_product_template/static/description/icon.png
  pos_product_template/static/src/css/ppt.css
  pos_product_template/static/src/img/screenshots/pos_product_template.png
  pos_product_template/static/src/js/SelectVariantPopup.js
  pos_product_template/static/src/js/models.js
  pos_product_template/static/src/js/ppt.js
  pos_product_template/static/src/xml/SelectVariantPopup.xml
  pos_product_template/static/src/xml/ppt.xml
  pos_product_template/view/view.xml
  setup/pos_product_template/odoo/addons/pos_product_template
  setup/pos_product_template/setup.py
Labels: approved, bot is merging ⏳

#769 [ADD] pos_ticket_static_qrcode
  pos_ticket_static_qrcode/README.rst
  pos_ticket_static_qrcode/__init__.py
  pos_ticket_static_qrcode/__manifest__.py
  pos_ticket_static_qrcode/i18n/fr.po
  pos_ticket_static_qrcode/i18n/pos_ticket_qrcode.pot
  pos_ticket_static_qrcode/models/__init__.py
  pos_ticket_static_qrcode/models/pos_config.py
  pos_ticket_static_qrcode/readme/CONFIGURE.rst
  pos_ticket_static_qrcode/readme/CONTRIBUTORS.rst
  pos_ticket_static_qrcode/readme/DESCRIPTION.rst
  pos_ticket_static_qrcode/readme/USAGE.rst
  pos_ticket_static_qrcode/static/description/icon.png
  pos_ticket_static_qrcode/static/description/index.html
  pos_ticket_static_qrcode/static/description/pos_ticket.png
  pos_ticket_static_qrcode/static/src/xml/pos.xml
  pos_ticket_static_qrcode/tests/__init__.py
  pos_ticket_static_qrcode/tests/test_pos_config.py
  pos_ticket_static_qrcode/views/pos_config.xml
Labels: approved, ready to merge, bot is merging ⏳

#804 [15.0] [IMP] `pos_event_sale`: Create only the missing `event.registrations`
  pos_event_sale/models/pos_order_line.py
Labels: bot is merging ⏳

#767 [ADD] new module pos_unavailable_product_friendly_error
  pos_unavailable_product_friendly_error/README.rst
  pos_unavailable_product_friendly_error/__init__.py
  pos_unavailable_product_friendly_error/__manifest__.py
  pos_unavailable_product_friendly_error/i18n/fr.po
  pos_unavailable_product_friendly_error/readme/CONTRIBUTORS.rst
  pos_unavailable_product_friendly_error/readme/DESCRIPTION.rst
  pos_unavailable_product_friendly_error/static/description/pos_front_end_popup.png
  pos_unavailable_product_friendly_error/static/src/js/models.js
  pos_unavailable_product_friendly_error/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#806 [14.0][FIX] pos_product_template, check variant product_template_attribute_value_ids exists
  pos_product_template/readme/CONTRIBUTORS.rst
  pos_product_template/readme/DESCRIPTION.rst
  pos_product_template/readme/ROADMAP.rst
  pos_product_template/readme/USAGE.rst
  pos_product_template/static/src/js/models.js
Labels: approved, bot is merging ⏳

#807 [14.0][ADD] pos_order_product_search
  pos_order_product_search/README.rst
  pos_order_product_search/__init__.py
  pos_order_product_search/__manifest__.py
  pos_order_product_search/readme/CONTRIBUTORS.rst
  pos_order_product_search/readme/DESCRIPTION.rst
  pos_order_product_search/readme/ROADMAP.rst
  pos_order_product_search/readme/USAGE.rst
  pos_order_product_search/static/description/icon.png
  pos_order_product_search/views/pos.xml
  setup/pos_order_product_search/odoo/addons/pos_order_product_search
  setup/pos_order_product_search/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#805 [15.0] [ADD] `pos_sale_pos_event_sale`: Glue module between `pos_sale` and `pos_event_sale`
  pos_sale_pos_event_sale/README.rst
  pos_sale_pos_event_sale/__init__.py
  pos_sale_pos_event_sale/__manifest__.py
  pos_sale_pos_event_sale/models/__init__.py
  pos_sale_pos_event_sale/models/pos_order_line.py
  pos_sale_pos_event_sale/models/sale_order_line.py
  pos_sale_pos_event_sale/readme/CONTRIBUTORS.rst
  pos_sale_pos_event_sale/readme/DESCRIPTION.rst
  pos_sale_pos_event_sale/static/src/js/SaleOrderManagementScreen.js
  pos_sale_pos_event_sale/static/src/js/models.js
  pos_sale_pos_event_sale/static/tests/tours/PosEventSaleImport.tour.js
  pos_sale_pos_event_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  pos_sale_pos_event_sale/static/tests/tours/helpers/SaleOrderScreenTourMethods.js
  pos_sale_pos_event_sale/tests/__init__.py
  pos_sale_pos_event_sale/tests/test_frontend.py
  setup/pos_sale_pos_event_sale/odoo/addons/pos_sale_pos_event_sale
  setup/pos_sale_pos_event_sale/setup.py
Labels: bot is merging ⏳

#819 [FIX][DOC] pos_edit_order_line : correct reference to description image
  pos_edit_order_line/readme/DESCRIPTION.rst
Labels: needs review, bot is merging ⏳

#818 [14.0][FIX] pos_cash_move_reason: Admin access issue for pos actions
  pos_cash_move_reason/models/pos_session.py
Labels: approved, bot is merging ⏳

#820 [14.0][FIX][pos_margin] Hide margin in Front End if config is false
  pos_margin/static/src/xml/pos_margin.xml
Labels: bot is merging ⏳
