Repository OCA/pos, pull requests merged in 2022-12, with the labels that each got.

#901 [13][REF] Update From Copier Template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: approved

#902 [14][REF] Update From Copier Template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#903 [15.0][REF] Update From Copier Template
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#905 [10.0][ADD] copier 2022 12 05
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  pos_backend_communication/__manifest__.py
  pos_backend_partner/__manifest__.py
  pos_customer_display/__manifest__.py
  pos_default_empty_image/__manifest__.py
  pos_fix_search_limit/__manifest__.py
  pos_gift_ticket/__manifest__.py
  pos_loyalty/__manifest__.py
  pos_margin/__manifest__.py
  pos_order_load/__manifest__.py
  pos_order_remove_line/__manifest__.py
  pos_order_return/__manifest__.py
  pos_payment_entries_globalization/__manifest__.py
  pos_payment_terminal/__manifest__.py
  pos_picking_delayed/__manifest__.py
  pos_price_to_weight/__manifest__.py
  pos_pricelist/__manifest__.py
  pos_product_template/__manifest__.py
  pos_quick_logout/__manifest__.py
  pos_remove_pos_category/__manifest__.py
  pos_timeout/__manifest__.py
  product_brand_pos_report/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#904 [11.0][ADD] ADD Copier Template
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  pos_cashier_login/__manifest__.py
  pos_fix_search_limit/__manifest__.py
  pos_loyalty/__manifest__.py
  pos_margin/__manifest__.py
  pos_order_return/__manifest__.py
  pos_payment_entries_globalization/__manifest__.py
  pos_picking_delayed/__manifest__.py
  pos_price_to_weight/__manifest__.py
Labels: bot is merging ⏳

#858 [16.0][ADD] new module ``pos_customer_comment``
  pos_customer_comment/README.rst
  pos_customer_comment/__init__.py
  pos_customer_comment/__manifest__.py
  pos_customer_comment/demo/res_partner.xml
  pos_customer_comment/models/__init__.py
  pos_customer_comment/models/pos_session.py
  pos_customer_comment/models/res_partner.py
  pos_customer_comment/readme/CONTRIBUTORS.rst
  pos_customer_comment/readme/CREDITS.rst
  pos_customer_comment/readme/DESCRIPTION.rst
  pos_customer_comment/readme/ROADMAP.rst
  pos_customer_comment/readme/USAGE.rst
  pos_customer_comment/static/description/pos_customer_form.png
  pos_customer_comment/static/description/pos_customer_tree.png
  pos_customer_comment/static/description/res_partner_form.png
  pos_customer_comment/static/src/css/pos_customer_comment.scss
  pos_customer_comment/static/src/xml/PartnerDetailsEdit.xml
  pos_customer_comment/static/src/xml/PartnerLine.xml
  pos_customer_comment/tests/__init__.py
  pos_customer_comment/tests/test_module.py
  pos_customer_comment/tests/tours/PosCustomerComment.tour.js
  pos_customer_comment/views/view_res_partner.xml
  setup/pos_customer_comment/odoo/addons/pos_customer_comment
  setup/pos_customer_comment/setup.py
Labels: approved, bot is merging ⏳

#894 [16.0][NEW] pos_order_reorder: new module to create new order from order history
  pos_order_reorder/README.rst
  pos_order_reorder/__init__.py
  pos_order_reorder/__manifest__.py
  pos_order_reorder/models/__init__.py
  pos_order_reorder/models/pos_config.py
  pos_order_reorder/models/res_config_settings.py
  pos_order_reorder/readme/CONFIGURE.rst
  pos_order_reorder/readme/CONTRIBUTORS.rst
  pos_order_reorder/readme/DESCRIPTION.rst
  pos_order_reorder/static/description/icon.png
  pos_order_reorder/static/img/reorder_button.png
  pos_order_reorder/static/src/js/Screens/TicketScreen/ControlButtons/ReorderButton.esm.js
  pos_order_reorder/static/src/xml/Screens/TicketScreen/ControlButtons/ReorderButton.xml
  pos_order_reorder/static/src/xml/Screens/TicketScreen/TicketScreen.xml
  pos_order_reorder/views/res_config_settings_view.xml
  setup/pos_order_reorder/odoo/addons/pos_order_reorder
  setup/pos_order_reorder/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#853 16.0 mig pos default partner
  pos_default_partner/README.rst
  pos_default_partner/__init__.py
  pos_default_partner/__manifest__.py
  pos_default_partner/i18n/es.po
  pos_default_partner/i18n/fr.po
  pos_default_partner/i18n/pos_default_partner.pot
  pos_default_partner/models/__init__.py
  pos_default_partner/models/pos_config.py
  pos_default_partner/models/pos_order.py
  pos_default_partner/models/res_config_settings.py
  pos_default_partner/readme/CONFIGURE.rst
  pos_default_partner/readme/CONTRIBUTORS.rst
  pos_default_partner/readme/DESCRIPTION.rst
  pos_default_partner/readme/ROADMAP.rst
  pos_default_partner/static/description/icon.png
  pos_default_partner/static/description/index.html
  pos_default_partner/tests/__init__.py
  pos_default_partner/tests/test_pos_default_partner.py
  pos_default_partner/views/res_config_settings_view.xml
  setup/pos_default_partner/odoo/addons/pos_default_partner
  setup/pos_default_partner/setup.py
Labels: approved, bot is merging ⏳

#814 [IMP] 14.0: pos_product_template no variant display
  pos_product_template/__init__.py
  pos_product_template/__manifest__.py
  pos_product_template/models/__init__.py
  pos_product_template/models/pos_config.py
  pos_product_template/static/src/css/ppt.css
  pos_product_template/static/src/js/SelectVariantPopup.js
  pos_product_template/static/src/xml/SelectVariantPopup.xml
  pos_product_template/views/assets.xml
  pos_product_template/views/pos_config_view.xml
Labels: approved, bot is merging ⏳

#833 [14.0][NEW] pos_customer_tree_view_vat
  pos_customer_tree_view_vat/README.rst
  pos_customer_tree_view_vat/__init__.py
  pos_customer_tree_view_vat/__manifest__.py
  pos_customer_tree_view_vat/readme/CONTRIBUTORS.rst
  pos_customer_tree_view_vat/readme/CREDITS.rst
  pos_customer_tree_view_vat/readme/DESCRIPTION.rst
  pos_customer_tree_view_vat/static/description/icon.png
  pos_customer_tree_view_vat/static/description/index.html
  pos_customer_tree_view_vat/static/description/printscreen.png
  pos_customer_tree_view_vat/static/src/xml/pos.xml
  setup/pos_customer_tree_view_vat/odoo/addons/pos_customer_tree_view_vat
  setup/pos_customer_tree_view_vat/setup.py
Labels: bot is merging ⏳

#882 [MIG] pos_receipt_hide_price: Migration to 15.0
  pos_receipt_hide_price/README.rst
  pos_receipt_hide_price/__init__.py
  pos_receipt_hide_price/__manifest__.py
  pos_receipt_hide_price/i18n/es.po
  pos_receipt_hide_price/i18n/pos_receipt_hide_price.pot
  pos_receipt_hide_price/readme/CONTRIBUTORS.rst
  pos_receipt_hide_price/readme/DESCRIPTION.rst
  pos_receipt_hide_price/readme/USAGE.rst
  pos_receipt_hide_price/static/description/icon.png
  pos_receipt_hide_price/static/description/index.html
  pos_receipt_hide_price/static/description/price-hidden.png
  pos_receipt_hide_price/static/description/price-shown.png
  pos_receipt_hide_price/static/src/js/OrderReceipt.js
  pos_receipt_hide_price/static/src/js/ReceiptScreen.js
  pos_receipt_hide_price/static/src/js/ReprintReceiptScreen.js
  pos_receipt_hide_price/static/src/xml/HidePrice.xml
  pos_receipt_hide_price/static/src/xml/OrderReceipt.xml
  pos_receipt_hide_price/static/src/xml/ReceiptScreen.xml
  pos_receipt_hide_price/static/src/xml/ReprintReceiptScreen.xml
  setup/pos_receipt_hide_price/odoo/addons/pos_receipt_hide_price
  setup/pos_receipt_hide_price/setup.py
Labels: needs review, bot is merging ⏳

#909 [REF] apply copier update v1.14.0
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
Labels: bot is merging ⏳

#887 [ADD] pos_receipt_xml_header_footer
  pos_receipt_xml_header_footer/__init__.py
  pos_receipt_xml_header_footer/__manifest__.py
  pos_receipt_xml_header_footer/readme/CONTRIBUTORS.rst
  pos_receipt_xml_header_footer/readme/DESCRIPTION.rst
  pos_receipt_xml_header_footer/readme/USAGE.rst
  pos_receipt_xml_header_footer/static/src/xml/pos.xml
  setup/pos_receipt_xml_header_footer/odoo/addons/pos_receipt_xml_header_footer
  setup/pos_receipt_xml_header_footer/setup.py
Labels: needs review, bot is merging ⏳

#851 [MIG] pos_receipt_hide_price: Migration to 16.0
  pos_receipt_hide_price/README.rst
  pos_receipt_hide_price/__init__.py
  pos_receipt_hide_price/__manifest__.py
  pos_receipt_hide_price/i18n/es.po
  pos_receipt_hide_price/i18n/pos_receipt_hide_price.pot
  pos_receipt_hide_price/readme/CONTRIBUTORS.rst
  pos_receipt_hide_price/readme/DESCRIPTION.rst
  pos_receipt_hide_price/readme/USAGE.rst
  pos_receipt_hide_price/static/description/icon.png
  pos_receipt_hide_price/static/description/index.html
  pos_receipt_hide_price/static/description/price-hidden.png
  pos_receipt_hide_price/static/description/price-shown.png
  pos_receipt_hide_price/static/src/js/OrderReceipt.js
  pos_receipt_hide_price/static/src/js/ReceiptScreen.js
  pos_receipt_hide_price/static/src/js/ReprintReceiptScreen.js
  pos_receipt_hide_price/static/src/xml/HidePrice.xml
  pos_receipt_hide_price/static/src/xml/OrderReceipt.xml
  pos_receipt_hide_price/static/src/xml/ReceiptScreen.xml
  pos_receipt_hide_price/static/src/xml/ReprintReceiptScreen.xml
  setup/pos_receipt_hide_price/odoo/addons/pos_receipt_hide_price
  setup/pos_receipt_hide_price/setup.py
Labels: needs review, bot is merging ⏳

#911 [FIX] pos_order_to_sale_order
  pos_order_to_sale_order/readme/CONFIGURE.rst
Labels: needs review, bot is merging ⏳

#908 [MIG][16.0] pos_payment_terminal
  pos_payment_terminal/README.rst
  pos_payment_terminal/__init__.py
  pos_payment_terminal/__manifest__.py
  pos_payment_terminal/i18n/es.po
  pos_payment_terminal/i18n/fr.po
  pos_payment_terminal/i18n/hr_HR.po
  pos_payment_terminal/i18n/it.po
  pos_payment_terminal/i18n/nl_NL.po
  pos_payment_terminal/i18n/pos_payment_terminal.pot
  pos_payment_terminal/models/__init__.py
  pos_payment_terminal/models/pos_payment_method.py
  pos_payment_terminal/models/pos_session.py
  pos_payment_terminal/readme/CONFIGURE.rst
  pos_payment_terminal/readme/CONTRIBUTORS.rst
  pos_payment_terminal/readme/DESCRIPTION.rst
  pos_payment_terminal/readme/INSTALL.rst
  pos_payment_terminal/readme/USAGE.rst
  pos_payment_terminal/static/description/icon.png
  pos_payment_terminal/static/description/index.html
  pos_payment_terminal/static/description/pos_payment_method_form.png
  pos_payment_terminal/static/src/js/models.js
  pos_payment_terminal/static/src/js/payment_terminal.js
  pos_payment_terminal/views/pos_payment_method.xml
  setup/pos_payment_terminal/odoo/addons/pos_payment_terminal
  setup/pos_payment_terminal/setup.py
Labels: approved, needs review, ready to merge, bot is merging ⏳

#907 [FIX][12.0] pos_order_to_sale_order : allow to create sale order from PoS when the products are only services
  pos_order_to_sale_order/models/sale_order.py
Labels: approved, needs review, bot is merging ⏳

#889 [15.0][MIG] pos_supplierinfo_barcode
  pos_supplierinfo_barcode/README.rst
  pos_supplierinfo_barcode/__init__.py
  pos_supplierinfo_barcode/__manifest__.py
  pos_supplierinfo_barcode/i18n/es.po
  pos_supplierinfo_barcode/i18n/pos_supplierinfo_barcode.pot
  pos_supplierinfo_barcode/models/__init__.py
  pos_supplierinfo_barcode/models/product.py
  pos_supplierinfo_barcode/readme/CONFIGURE.rst
  pos_supplierinfo_barcode/readme/CONTRIBUTORS.rst
  pos_supplierinfo_barcode/readme/DESCRIPTION.rst
  pos_supplierinfo_barcode/readme/USAGE.rst
  pos_supplierinfo_barcode/static/description/icon.png
  pos_supplierinfo_barcode/static/description/index.html
  pos_supplierinfo_barcode/static/src/js/db.js
  setup/pos_supplierinfo_barcode/odoo/addons/pos_supplierinfo_barcode
  setup/pos_supplierinfo_barcode/setup.py
Labels: approved, needs review, migration, ready to merge, bot is merging ⏳

#890 [15.0][MIG] pos_supplierinfo_search
  pos_supplierinfo_search/README.rst
  pos_supplierinfo_search/__init__.py
  pos_supplierinfo_search/__manifest__.py
  pos_supplierinfo_search/i18n/es.po
  pos_supplierinfo_search/i18n/pos_supplierinfo_search.pot
  pos_supplierinfo_search/models/__init__.py
  pos_supplierinfo_search/models/product.py
  pos_supplierinfo_search/readme/CONTRIBUTORS.rst
  pos_supplierinfo_search/readme/DESCRIPTION.rst
  pos_supplierinfo_search/readme/USAGE.rst
  pos_supplierinfo_search/static/description/icon.png
  pos_supplierinfo_search/static/description/index.html
  pos_supplierinfo_search/static/src/js/db.js
  setup/pos_supplierinfo_search/odoo/addons/pos_supplierinfo_search
  setup/pos_supplierinfo_search/setup.py
Labels: approved, needs review, migration, ready to merge, bot is merging ⏳

#899 [15.0][MIG]pos_payment_change
  pos_payment_change/README.rst
  pos_payment_change/__init__.py
  pos_payment_change/__manifest__.py
  pos_payment_change/i18n/de.po
  pos_payment_change/i18n/es.po
  pos_payment_change/i18n/fr.po
  pos_payment_change/i18n/pos_payment_change.pot
  pos_payment_change/models/__init__.py
  pos_payment_change/models/pos_config.py
  pos_payment_change/models/pos_order.py
  pos_payment_change/readme/CONFIGURE.rst
  pos_payment_change/readme/CONTRIBUTORS.rst
  pos_payment_change/readme/CREDITS.rst
  pos_payment_change/readme/DESCRIPTION.rst
  pos_payment_change/readme/USAGE.rst
  pos_payment_change/security/ir.model.access.csv
  pos_payment_change/static/description/icon.png
  pos_payment_change/static/description/index.html
  pos_payment_change/static/description/pos_config_form.png
  pos_payment_change/static/description/pos_order_form.png
  pos_payment_change/static/description/pos_order_tree.png
  pos_payment_change/static/description/pos_payment_change_wizard_form.png
  pos_payment_change/tests/__init__.py
  pos_payment_change/tests/test_module.py
  pos_payment_change/views/view_pos_config.xml
  pos_payment_change/views/view_pos_order.xml
  pos_payment_change/wizards/__init__.py
  pos_payment_change/wizards/pos_payment_change_wizard.py
  pos_payment_change/wizards/pos_payment_change_wizard_new_line.py
  pos_payment_change/wizards/pos_payment_change_wizard_old_line.py
  pos_payment_change/wizards/view_pos_payment_change_wizard.xml
  setup/pos_payment_change/odoo/addons/pos_payment_change
  setup/pos_payment_change/setup.py
Labels: approved, needs review, migration, bot is merging ⏳

#878 [14.0][IMP] `pos_product_template`: Sort product attribute
  pos_product_template/static/src/js/SelectVariantPopup.js
  pos_product_template/static/src/js/models.js
Labels: approved, needs fixing, ready to merge, bot is merging ⏳

#816 [14.0][MIG] pos_payment_method_cashdro: Migration to version 14.0
  pos_payment_method_cashdro/README.rst
  pos_payment_method_cashdro/__init__.py
  pos_payment_method_cashdro/__manifest__.py
  pos_payment_method_cashdro/i18n/pos_payment_method_cashdro.pot
  pos_payment_method_cashdro/migrations/14.0.1.0.0/pre-migration.py
  pos_payment_method_cashdro/models/__init__.py
  pos_payment_method_cashdro/models/pos_payment_method.py
  pos_payment_method_cashdro/readme/CONFIGURE.rst
  pos_payment_method_cashdro/readme/CONTRIBUTORS.rst
  pos_payment_method_cashdro/readme/DESCRIPTION.rst
  pos_payment_method_cashdro/readme/ROADMAP.rst
  pos_payment_method_cashdro/readme/USAGE.rst
  pos_payment_method_cashdro/static/description/icon.png
  pos_payment_method_cashdro/static/description/index.html
  pos_payment_method_cashdro/static/description/logo.png
  pos_payment_method_cashdro/static/src/js/models.js
  pos_payment_method_cashdro/static/src/js/payment_cashdro.js
  pos_payment_method_cashdro/views/assets.xml
  pos_payment_method_cashdro/views/pos_payment_method_views.xml
  setup/pos_payment_method_cashdro/odoo/addons/pos_payment_method_cashdro
  setup/pos_payment_method_cashdro/setup.py
Labels: approved, bot is merging ⏳

#910 [MIG][16.0] pos_escpos_status
  pos_escpos_status/README.rst
  pos_escpos_status/__init__.py
  pos_escpos_status/__manifest__.py
  pos_escpos_status/i18n/pos_escpos_status.pot
  pos_escpos_status/readme/DESCRIPTION.rst
  pos_escpos_status/static/description/icon.png
  pos_escpos_status/static/description/index.html
  pos_escpos_status/static/src/js/ProxyStatus.js
  setup/pos_escpos_status/odoo/addons/pos_escpos_status
  setup/pos_escpos_status/setup.py
Labels: approved, ready to merge, bot is merging ⏳
