Repository OCA/pos, pull requests merged in 2023-01, with the labels that each got.

#428 [ADD] 12.0 pos_mail_receipt module
  pos_mail_receipt/README.rst
  pos_mail_receipt/__init__.py
  pos_mail_receipt/__manifest__.py
  pos_mail_receipt/data/email.xml
  pos_mail_receipt/i18n/fr.po
  pos_mail_receipt/i18n/pos_mail_receipt.pot
  pos_mail_receipt/models/__init__.py
  pos_mail_receipt/models/pos_order.py
  pos_mail_receipt/readme/CONTRIBUTORS.rst
  pos_mail_receipt/readme/DESCRIPTION.rst
  pos_mail_receipt/readme/USAGE.rst
  pos_mail_receipt/static/description/icon.png
  pos_mail_receipt/static/description/index.html
  pos_mail_receipt/static/src/css/pos.css
  pos_mail_receipt/static/src/css/print.css
  pos_mail_receipt/static/src/js/screens.js
  pos_mail_receipt/static/src/xml/pos.xml
  pos_mail_receipt/templates/assets.xml
  pos_mail_receipt/tests/__init__.py
  pos_mail_receipt/tests/test_module.py
  pos_mail_receipt/views/pos_order_form_mail_receipt_sent.xml
  setup/pos_mail_receipt/odoo/addons/pos_mail_receipt
  setup/pos_mail_receipt/setup.py
Labels: bot is merging ⏳

#915 [ADD] pos_product_quick_info: Add new module to display product without add in to card
  pos_product_quick_info/README.rst
  pos_product_quick_info/__init__.py
  pos_product_quick_info/__manifest__.py
  pos_product_quick_info/models/__init__.py
  pos_product_quick_info/models/pos_config.py
  pos_product_quick_info/models/res_config_settings.py
  pos_product_quick_info/readme/CONFIGURE.rst
  pos_product_quick_info/readme/CONTRIBUTORS.rst
  pos_product_quick_info/readme/DESCRIPTION.rst
  pos_product_quick_info/static/description/icon.png
  pos_product_quick_info/static/img/config.png
  pos_product_quick_info/static/img/info.png
  pos_product_quick_info/static/src/css/pos.css
  pos_product_quick_info/static/src/js/Screens/ProductScreen/ProductItem.js
  pos_product_quick_info/static/src/xml/Screens/ProductScreen/ProductItem.xml
  pos_product_quick_info/views/res_config_settings_view.xml
  setup/pos_product_quick_info/odoo/addons/pos_product_quick_info
  setup/pos_product_quick_info/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#881 [IMP] pos_invoicing : confirm invoices that are created in the back-office by the UI, to avoid user to change / delete invoices created and paid from PoS
  pos_invoicing/models/pos_order.py
  pos_invoicing/tests/test_module.py
  pos_order_return/models/pos_order.py
Labels: approved, needs review, ready to merge, bot is merging ⏳
