Repository OCA/pos, pull requests merged in 2023-12, with the labels that each got.

#1103 [FIX] pos_pricelist_show_discount: fix price with nested lists
  pos_pricelist_show_discount/static/src/js/models.js
Labels: approved, bot is merging ⏳

#1104 [17.0][MIG] pos_partner_birthdate
  pos_partner_birthdate/README.rst
  pos_partner_birthdate/__init__.py
  pos_partner_birthdate/__manifest__.py
  pos_partner_birthdate/i18n/es.po
  pos_partner_birthdate/i18n/it.po
  pos_partner_birthdate/i18n/pos_partner_birthdate.pot
  pos_partner_birthdate/models/__init__.py
  pos_partner_birthdate/models/pos_session.py
  pos_partner_birthdate/pyproject.toml
  pos_partner_birthdate/readme/CONTRIBUTORS.md
  pos_partner_birthdate/readme/DESCRIPTION.md
  pos_partner_birthdate/readme/newsfragments/.gitkeep
  pos_partner_birthdate/static/description/icon.png
  pos_partner_birthdate/static/description/index.html
  pos_partner_birthdate/static/src/js/ClientDetailsEdit.esm.js
  pos_partner_birthdate/static/src/xml/ClientDetailsEdit.xml
Labels: approved, ready to merge, bot is merging ⏳

#1099 [16.0] [FIX] pos_stock_available_onine: Fix banner
  pos_stock_available_online/static/description/banner.png
Labels: approved, bot is merging ⏳

#953 [16.0][ADD] pos_sale_order_delivery_carrier: Add new module to select delivery carrier of sale order from POS
  pos_order_to_sale_order_delivery/README.rst
  pos_order_to_sale_order_delivery/__init__.py
  pos_order_to_sale_order_delivery/__manifest__.py
  pos_order_to_sale_order_delivery/models/__init__.py
  pos_order_to_sale_order_delivery/models/delivery_carrier.py
  pos_order_to_sale_order_delivery/models/pos_config.py
  pos_order_to_sale_order_delivery/models/res_config_settings.py
  pos_order_to_sale_order_delivery/models/sale_order.py
  pos_order_to_sale_order_delivery/readme/CONFIGURE.rst
  pos_order_to_sale_order_delivery/readme/CONTRIBUTORS.rst
  pos_order_to_sale_order_delivery/readme/DESCRIPTION.rst
  pos_order_to_sale_order_delivery/readme/USAGE.rst
  pos_order_to_sale_order_delivery/static/description/icon.png
  pos_order_to_sale_order_delivery/static/img/pos_add_shipping.png
  pos_order_to_sale_order_delivery/static/img/pos_config.png
  pos_order_to_sale_order_delivery/static/img/pos_select_shipping.png
  pos_order_to_sale_order_delivery/static/src/css/pos.css
  pos_order_to_sale_order_delivery/static/src/js/Popups/ChooseDeliveryCarrierPopup.esm.js
  pos_order_to_sale_order_delivery/static/src/js/Popups/CreateOrderPopup.esm.js
  pos_order_to_sale_order_delivery/static/src/js/models.esm.js
  pos_order_to_sale_order_delivery/static/src/xml/Popups/ChooseDeliveryCarrierPopup.xml
  pos_order_to_sale_order_delivery/static/src/xml/Popups/CreateOrderPopup.xml
  pos_order_to_sale_order_delivery/views/res_config_settings_view.xml
  setup/pos_order_to_sale_order_delivery/odoo/addons/pos_order_to_sale_order_delivery
  setup/pos_order_to_sale_order_delivery/setup.py
Labels: approved, bot is merging ⏳

#1111 [15.0] [FIX] `pos_sale_pos_event_sale`: keep the event sale description after import
  pos_sale_pos_event_sale/static/src/js/models.js
Labels: bug, Fast Track, bot is merging ⏳

#1051 [15.0] [MIG] pos_fixed_discount
  pos_fixed_discount/README.rst
  pos_fixed_discount/__init__.py
  pos_fixed_discount/__manifest__.py
  pos_fixed_discount/i18n/es.po
  pos_fixed_discount/i18n/it.po
  pos_fixed_discount/i18n/pos_fixed_discount.pot
  pos_fixed_discount/readme/CONTRIBUTORS.rst
  pos_fixed_discount/readme/DESCRIPTION.rst
  pos_fixed_discount/readme/USAGE.rst
  pos_fixed_discount/static/description/icon.png
  pos_fixed_discount/static/description/index.html
  pos_fixed_discount/static/src/js/FixedDiscountButton.js
  pos_fixed_discount/static/src/xml/discount_templates.xml
  setup/pos_fixed_discount/odoo/addons/pos_fixed_discount
  setup/pos_fixed_discount/setup.py
Labels: approved, bot is merging ⏳

#1054 [15.0][MIG] pos_product_template
  pos_product_template/README.rst
  pos_product_template/__init__.py
  pos_product_template/__manifest__.py
  pos_product_template/demo/product_attribute_value.xml
  pos_product_template/demo/product_product.xml
  pos_product_template/i18n/es.po
  pos_product_template/i18n/fr.po
  pos_product_template/i18n/it.po
  pos_product_template/i18n/pos_product_template.pot
  pos_product_template/models/__init__.py
  pos_product_template/models/pos_config.py
  pos_product_template/readme/CONTRIBUTORS.rst
  pos_product_template/readme/DESCRIPTION.rst
  pos_product_template/readme/ROADMAP.rst
  pos_product_template/readme/USAGE.rst
  pos_product_template/static/description/icon.png
  pos_product_template/static/description/index.html
  pos_product_template/static/src/css/ppt.css
  pos_product_template/static/src/img/screenshots/pos_product_template.png
  pos_product_template/static/src/js/SelectVariantPopup.esm.js
  pos_product_template/static/src/js/models.esm.js
  pos_product_template/static/src/js/ppt.esm.js
  pos_product_template/static/src/xml/SelectVariantPopup.xml
  pos_product_template/static/src/xml/ppt.xml
  pos_product_template/views/pos_config_view.xml
  setup/pos_product_template/odoo/addons/pos_product_template
  setup/pos_product_template/setup.py
Labels: approved, bot is merging ⏳

#1093 [15.0][FIX] pos_report_session_summary: fix error when printing
  pos_report_session_summary/views/report_session_summary.xml
Labels: approved, ready to merge, bot is merging ⏳

#1109 [16.0] [ADD] pos_product_label
  pos_product_label/README.rst
  pos_product_label/__init__.py
  pos_product_label/__manifest__.py
  pos_product_label/models/__init__.py
  pos_product_label/models/pos_config.py
  pos_product_label/models/pos_session.py
  pos_product_label/models/res_config_settings.py
  pos_product_label/readme/CONTRIBUTORS.rst
  pos_product_label/readme/DESCRIPTION.rst
  pos_product_label/readme/USAGE.rst
  pos_product_label/static/description/index.html
  pos_product_label/static/description/preview.png
  pos_product_label/static/src/PrintLabelButton.esm.js
  pos_product_label/static/src/PrintLabelButton.xml
  pos_product_label/static/src/PrintLabelPopup.esm.js
  pos_product_label/static/src/PrintLabelPopup.scss
  pos_product_label/static/src/PrintLabelPopup.xml
  pos_product_label/views/res_config_settings.xml
  pos_product_label/wizards/__init__.py
  pos_product_label/wizards/product_label_layout.py
  setup/pos_product_label/odoo/addons/pos_product_label
  setup/pos_product_label/setup.py
Labels: approved, bot is merging ⏳

#1030 [16.0] [MIG] pos_reset_search
  pos_reset_search/README.rst
  pos_reset_search/__init__.py
  pos_reset_search/__manifest__.py
  pos_reset_search/i18n/es.po
  pos_reset_search/i18n/it.po
  pos_reset_search/i18n/pos_reset_search.pot
  pos_reset_search/readme/CONTRIBUTORS.rst
  pos_reset_search/readme/DESCRIPTION.rst
  pos_reset_search/readme/USAGE.rst
  pos_reset_search/static/description/icon.png
  pos_reset_search/static/description/index.html
  pos_reset_search/static/src/js/Screens/ProductScreen/ProductScreen.js
  setup/pos_reset_search/odoo/addons/pos_reset_search
  setup/pos_reset_search/setup.py
Labels: approved, bot is merging ⏳

#1112 [14.0][FIX] pos_*: avoid located CI issues
  pos_cash_move_reason/tests/test_pos_cash_move_reason.py
  pos_margin/tests/test_module.py
  pos_payment_change/tests/test_module.py
Labels: bot is merging ⏳

#1018 [16.0][ADD] pos_financial_risk
  pos_financial_risk/README.rst
  pos_financial_risk/__init__.py
  pos_financial_risk/__manifest__.py
  pos_financial_risk/models/__init__.py
  pos_financial_risk/models/pos_config.py
  pos_financial_risk/models/pos_payment_method.py
  pos_financial_risk/models/pos_session.py
  pos_financial_risk/models/res_config_settings.py
  pos_financial_risk/readme/CONFIGURE.rst
  pos_financial_risk/readme/CONTRIBUTORS.rst
  pos_financial_risk/readme/DESCRIPTION.rst
  pos_financial_risk/readme/USAGE.rst
  pos_financial_risk/static/description/index.html
  pos_financial_risk/static/src/js/PaymentScreen.esm.js
  pos_financial_risk/static/src/scss/pos.scss
  pos_financial_risk/static/src/xml/PaymentScreen.xml
  pos_financial_risk/views/pos_payment_method_views.xml
  pos_financial_risk/views/res_config_settings_views.xml
  setup/pos_financial_risk/odoo/addons/pos_financial_risk
  setup/pos_financial_risk/setup.py
Labels: approved, bot is merging ⏳

#1110 [14.0][IMP] pos_disable_pricelist_selection: selectable pricelists
  pos_disable_pricelist_selection/README.rst
  pos_disable_pricelist_selection/__manifest__.py
  pos_disable_pricelist_selection/models/pos_config.py
  pos_disable_pricelist_selection/readme/CONTEXT.rst
  pos_disable_pricelist_selection/readme/DESCRIPTION.rst
  pos_disable_pricelist_selection/readme/USAGE.rst
  pos_disable_pricelist_selection/static/description/index.html
  pos_disable_pricelist_selection/static/src/js/PosModel.js
  pos_disable_pricelist_selection/static/src/js/SetPricelistButton.js
  pos_disable_pricelist_selection/views/assets.xml
  pos_disable_pricelist_selection/views/pos_config_view.xml
Labels: approved, bot is merging ⏳

#1024 [16.0][ADD] pos_order_to_sale_order_sale_financial_risk: Sale Financial Risk in POS
  pos_order_to_sale_order_sale_financial_risk/README.rst
  pos_order_to_sale_order_sale_financial_risk/__init__.py
  pos_order_to_sale_order_sale_financial_risk/__manifest__.py
  pos_order_to_sale_order_sale_financial_risk/data/demo.xml
  pos_order_to_sale_order_sale_financial_risk/models/__init__.py
  pos_order_to_sale_order_sale_financial_risk/models/pos_session.py
  pos_order_to_sale_order_sale_financial_risk/models/sale_order.py
  pos_order_to_sale_order_sale_financial_risk/readme/DESCRIPTION.rst
  pos_order_to_sale_order_sale_financial_risk/static/description/index.html
  pos_order_to_sale_order_sale_financial_risk/static/img/desktop_table.jpg
  pos_order_to_sale_order_sale_financial_risk/static/src/js/CreateOrderPopup.esm.js
  pos_order_to_sale_order_sale_financial_risk/static/src/js/models.esm.js
  pos_order_to_sale_order_sale_financial_risk/static/src/tests/tours/SaleFinancialRiskPosCompatibility.tour.esm.js
  pos_order_to_sale_order_sale_financial_risk/tests/__init__.py
  pos_order_to_sale_order_sale_financial_risk/tests/test_pos_ui.py
  setup/pos_order_to_sale_order_sale_financial_risk/odoo/addons/pos_order_to_sale_order_sale_financial_risk
  setup/pos_order_to_sale_order_sale_financial_risk/setup.py
Labels: approved, needs fixing, ready to merge, bot is merging ⏳
