Repository OCA/pos, pull requests merged in 2023-11, with the labels that each got.

#1071 [16.0][FIX] pos_partner_birthdate: fixing this.changes state
  pos_partner_birthdate/static/src/js/ClientDetailsEdit.esm.js
Labels: approved, needs review, bot is merging ⏳

#1073 [14.0][FIX] pos_pricelist_show_discount: pricelist based on other pricelist
  pos_pricelist_show_discount/static/src/js/models.js
Labels: approved, bot is merging ⏳

#1075 pos_report_session_summary: fix printing session report
  pos_report_session_summary/views/report_session_summary.xml
Labels: bot is merging ⏳

#1076 [11.0][MIG] pos_payment_change
  pos_payment_change/README.rst
  pos_payment_change/__init__.py
  pos_payment_change/__manifest__.py
  pos_payment_change/i18n/de.po
  pos_payment_change/i18n/es.po
  pos_payment_change/i18n/fr.po
  pos_payment_change/i18n/it.po
  pos_payment_change/i18n/pos_payment_change.pot
  pos_payment_change/models/__init__.py
  pos_payment_change/models/pos_config.py
  pos_payment_change/models/pos_order.py
  pos_payment_change/readme/CONFIGURE.rst
  pos_payment_change/readme/CONTRIBUTORS.rst
  pos_payment_change/readme/CREDITS.rst
  pos_payment_change/readme/DESCRIPTION.rst
  pos_payment_change/readme/USAGE.rst
  pos_payment_change/static/description/icon.png
  pos_payment_change/static/description/index.html
  pos_payment_change/static/description/pos_config_form.png
  pos_payment_change/static/description/pos_order_form.png
  pos_payment_change/static/description/pos_order_tree.png
  pos_payment_change/static/description/pos_payment_change_wizard_form.png
  pos_payment_change/tests/__init__.py
  pos_payment_change/tests/test_module.py
  pos_payment_change/views/view_pos_config.xml
  pos_payment_change/views/view_pos_order.xml
  pos_payment_change/wizards/__init__.py
  pos_payment_change/wizards/pos_payment_change_wizard.py
  pos_payment_change/wizards/pos_payment_change_wizard_new_line.py
  pos_payment_change/wizards/pos_payment_change_wizard_old_line.py
  pos_payment_change/wizards/view_pos_payment_change_wizard.xml
  setup/pos_payment_change/odoo/addons/pos_payment_change
  setup/pos_payment_change/setup.cfg
  setup/pos_payment_change/setup.py
Labels: approved, bot is merging ⏳

#1081 [FIX] pos_loyalty_redeem_payment : bad translation break pre-commit
  pos_loyalty_redeem_payment/i18n/fr.po
Labels: bot is merging ⏳

#1082 [16.0][IMP] pos_sale_order_print
  pos_sale_order_print/static/description/banner.png
  pos_sale_order_print/static/description/index.html
Labels: bot is merging ⏳

#1085 [16.0] [IMP] pos_order_reorder: banner added
  pos_order_reorder/README.rst
  pos_order_reorder/__manifest__.py
  pos_order_reorder/static/description/banner.png
  pos_order_reorder/static/description/index.html
Labels: bot is merging ⏳

#1072 [16.0][FIX] pos_partner_birthdate: Fixing conflict t-model vs t-att-value
  pos_partner_birthdate/static/src/xml/ClientDetailsEdit.xml
Labels: bug, approved, needs review, ready to merge, bot is merging ⏳

#1037 [16.0][MIG] pos_product_multi_barcode: Migration to 16.0
  pos_product_multi_barcode/README.rst
  pos_product_multi_barcode/__init__.py
  pos_product_multi_barcode/__manifest__.py
  pos_product_multi_barcode/i18n/it.po
  pos_product_multi_barcode/i18n/pos_product_multi_barcode.pot
  pos_product_multi_barcode/models/__init__.py
  pos_product_multi_barcode/models/pos_session.py
  pos_product_multi_barcode/models/product.py
  pos_product_multi_barcode/readme/CONTRIBUTORS.rst
  pos_product_multi_barcode/readme/CREDITS.rst
  pos_product_multi_barcode/readme/DESCRIPTION.rst
  pos_product_multi_barcode/static/description/icon.png
  pos_product_multi_barcode/static/description/index.html
  pos_product_multi_barcode/static/src/js/db.js
  setup/pos_product_multi_barcode/odoo/addons/pos_product_multi_barcode
  setup/pos_product_multi_barcode/setup.py
Labels: approved, bot is merging ⏳

#1088 [16.0] [IMP] pos_product_quick_info-banner_added
  pos_product_quick_info/README.rst
  pos_product_quick_info/__manifest__.py
  pos_product_quick_info/static/description/banner.png
  pos_product_quick_info/static/description/index.html
Labels: approved, bot is merging ⏳

#1028 [IMP] add a menu entry in account module to manage pos place for user that use place only on invoices
  pos_place/i18n/fr.po
  pos_place/i18n/pos_place.pot
  pos_place/views/view_pos_place.xml
Labels: bot is merging ⏳

#1033 [ADD] new module 'pos_bank_statement_line_no_change'. prevent to unlink / write on bank statement lines of confirmed PoS Orders
  .copier-answers.yml
  .github/workflows/test.yml
  pos_bank_statement_line_no_change/README.rst
  pos_bank_statement_line_no_change/__init__.py
  pos_bank_statement_line_no_change/__manifest__.py
  pos_bank_statement_line_no_change/i18n/fr.po
  pos_bank_statement_line_no_change/models/__init__.py
  pos_bank_statement_line_no_change/models/account_bank_statement_line.py
  pos_bank_statement_line_no_change/readme/CONTRIBUTORS.rst
  pos_bank_statement_line_no_change/readme/DESCRIPTION.rst
  pos_bank_statement_line_no_change/static/description/icon.png
  pos_bank_statement_line_no_change/static/description/index.html
  pos_bank_statement_line_no_change/tests/__init__.py
  pos_bank_statement_line_no_change/tests/test_module.py
  setup/pos_bank_statement_line_no_change/odoo/addons/pos_bank_statement_line_no_change
  setup/pos_bank_statement_line_no_change/setup.py
Labels: bot is merging ⏳

#1094 [14.0][IMP] pos_pricelist_show_discount: maintainers
  pos_pricelist_show_discount/README.rst
  pos_pricelist_show_discount/__manifest__.py
  pos_pricelist_show_discount/static/description/index.html
Labels: bot is merging ⏳

#1080 [16.0][IMP] pos_order_to_sale_order : use customer note and correctly prepare sale.order.line name fields
  pos_order_to_sale_order/models/sale_order.py
  pos_order_to_sale_order/models/sale_order_line.py
Labels: bot is merging ⏳

#1096 [FIX] pos_payment_change : check installation fo existing modules.
  pos_payment_change/models/pos_config.py
Labels: needs review, bot is merging ⏳

#1098 [16.0][IMP] use right method to access action / remove an obsolete Warning
  pos_payment_change/models/pos_order.py
  pos_payment_change/tests/test_module.py
  pos_payment_change/wizards/pos_payment_change_wizard.py
Labels: bot is merging ⏳

#1095 [16.0][IMP] pos_order_to_sale_order
  pos_order_to_sale_order/models/sale_order.py
  pos_order_to_sale_order/models/sale_order_line.py
  pos_order_to_sale_order/tests/test_module.py
  pos_order_to_sale_order/tests/tours/PosOrderToSaleOrderTour.tour.js
Labels: approved, ready to merge, bot is merging ⏳

#1101 [16.0] [FIX] pos_product_quick_info: Fix banner
  pos_product_quick_info/static/description/banner.png
Labels: approved, bot is merging ⏳

#1102 [16.0] [FIX] pos_sale_order_print: Fix banner
  pos_sale_order_print/static/description/banner.png
Labels: approved, bot is merging ⏳

#1100 [16.0][FIX] pos_order_reorder: Fix banner
  pos_order_reorder/static/description/banner.png
Labels: approved, bot is merging ⏳
