Repository OCA/pos, pull requests merged in 2023-02, with the labels that each got.

#923 [14.0][FIX] pos_payment_change: xmlids
  pos_payment_change/wizards/pos_payment_change_wizard.py
Labels: bot is merging ⏳

#928 [16.0] [UPD] copier
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: Fast Track

#925 [16.0] [MIG] pos_order_remove_line: migration to 16.0
  pos_order_remove_line/README.rst
  pos_order_remove_line/__init__.py
  pos_order_remove_line/__manifest__.py
  pos_order_remove_line/i18n/pos_order_remove_line.pot
  pos_order_remove_line/readme/CONTRIBUTORS.rst
  pos_order_remove_line/readme/DESCRIPTION.rst
  pos_order_remove_line/static/description/icon.png
  pos_order_remove_line/static/description/index.html
  pos_order_remove_line/static/src/css/orderline.scss
  pos_order_remove_line/static/src/js/orderline.esm.js
  pos_order_remove_line/static/src/xml/orderline.xml
  setup/pos_order_remove_line/odoo/addons/pos_order_remove_line
  setup/pos_order_remove_line/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#932 [14.0][UPD] pos_cash_move_reason: chatter record when money in or out.
  pos_cash_move_reason/wizard/wizard_pos_move_reason.py
Labels: approved, bot is merging ⏳

#916 [FIX] pos_partner_no_create
  pos_partner_no_create/static/src/xml/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#935 [16.0][MIG] pos_lot_selection: Migration to 16.0
  pos_lot_selection/README.rst
  pos_lot_selection/__init__.py
  pos_lot_selection/__manifest__.py
  pos_lot_selection/i18n/pos_lot_selection.pot
  pos_lot_selection/models/__init__.py
  pos_lot_selection/models/stock_lot.py
  pos_lot_selection/readme/DESCRIPTION.rst
  pos_lot_selection/readme/USAGE.rst
  pos_lot_selection/static/description/icon.png
  pos_lot_selection/static/description/index.html
  pos_lot_selection/static/src/js/EditListPopup.js
  pos_lot_selection/static/src/js/OrderWidget.js
  pos_lot_selection/static/src/js/ProductScreen.js
  pos_lot_selection/static/src/js/models.js
  pos_lot_selection/static/src/xml/LotSelectorPopup.xml
  setup/pos_lot_selection/odoo/addons/pos_lot_selection
  setup/pos_lot_selection/setup.py
Labels: approved

#934 [16.0][MIG] pos_lot_barcode: Migration to 16.0
  pos_lot_barcode/README.rst
  pos_lot_barcode/__init__.py
  pos_lot_barcode/__manifest__.py
  pos_lot_barcode/i18n/pos_lot_barcode.pot
  pos_lot_barcode/readme/CONFIGURATION.rst
  pos_lot_barcode/readme/CONTRIBUTORS.rst
  pos_lot_barcode/readme/DESCRIPTION.rst
  pos_lot_barcode/static/description/icon.png
  pos_lot_barcode/static/description/index.html
  pos_lot_barcode/static/src/js/Popups/EditListPopup.js
  pos_lot_barcode/static/src/js/Popups/ErrorMultiLotBarcodePopup.js
  pos_lot_barcode/static/src/js/Screens/ProductScreen.js
  pos_lot_barcode/static/src/xml/Popups/ErrorMultiLotBarcodePopup.xml
  setup/pos_lot_barcode/odoo/addons/pos_lot_barcode
  setup/pos_lot_barcode/setup.py
Labels: approved, bot is merging ⏳
