Repository OCA/pos, pull requests merged in 2023-06, with the labels that each got.

#824 [14.0][MIG] pos_customer_display and add support for Epson ePOS for displays
  pos_customer_display/README.rst
  pos_customer_display/__init__.py
  pos_customer_display/__manifest__.py
  pos_customer_display/i18n/de.po
  pos_customer_display/i18n/es.po
  pos_customer_display/i18n/fr.po
  pos_customer_display/i18n/hr_HR.po
  pos_customer_display/i18n/it.po
  pos_customer_display/i18n/nl.po
  pos_customer_display/i18n/nl_NL.po
  pos_customer_display/i18n/pos_customer_display.pot
  pos_customer_display/models/__init__.py
  pos_customer_display/models/pos_config.py
  pos_customer_display/readme/CONFIGURE.rst
  pos_customer_display/readme/CONTRIBUTORS.rst
  pos_customer_display/readme/DESCRIPTION.rst
  pos_customer_display/readme/INSTALL.rst
  pos_customer_display/readme/ROADMAP.rst
  pos_customer_display/readme/USAGE.rst
  pos_customer_display/static/description/icon.png
  pos_customer_display/static/description/index.html
  pos_customer_display/static/src/js/chrome.js
  pos_customer_display/static/src/js/customer_display_2_20.js
  pos_customer_display/static/src/js/devices.js
  pos_customer_display/static/src/js/models.js
  pos_customer_display/static/src/js/payment_screen.js
  pos_customer_display/static/src/js/product_screen.js
  pos_customer_display/views/assets.xml
  pos_customer_display/views/view_pos_config.xml
  setup/pos_customer_display/odoo/addons/pos_customer_display
  setup/pos_customer_display/setup.py
Labels: approved, bot is merging ⏳

#1017 [FIX] bad permission
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pos_cashier_login/__manifest__.py
Labels: bot is merging ⏳

#1011 [ADD] pos_loyalty_redeem_payment
  pos_loyalty_redeem_payment/README.rst
  pos_loyalty_redeem_payment/__init__.py
  pos_loyalty_redeem_payment/__manifest__.py
  pos_loyalty_redeem_payment/i18n/es.po
  pos_loyalty_redeem_payment/models/__init__.py
  pos_loyalty_redeem_payment/models/loyalty_program.py
  pos_loyalty_redeem_payment/models/pos_config.py
  pos_loyalty_redeem_payment/models/pos_order.py
  pos_loyalty_redeem_payment/models/pos_payment.py
  pos_loyalty_redeem_payment/models/pos_payment_method.py
  pos_loyalty_redeem_payment/models/pos_session.py
  pos_loyalty_redeem_payment/readme/CONFIGURE.rst
  pos_loyalty_redeem_payment/readme/CONTRIBUTORS.rst
  pos_loyalty_redeem_payment/readme/DESCRIPTION.rst
  pos_loyalty_redeem_payment/readme/ROADMAP.rst
  pos_loyalty_redeem_payment/readme/USAGE.rst
  pos_loyalty_redeem_payment/static/description/index.html
  pos_loyalty_redeem_payment/static/img/paymentMethod.png
  pos_loyalty_redeem_payment/static/img/paymentMethodCheck.png
  pos_loyalty_redeem_payment/static/img/redeemMethod.png
  pos_loyalty_redeem_payment/static/img/usage_1_code_popup.png
  pos_loyalty_redeem_payment/static/img/usage_2_amount_popup.png
  pos_loyalty_redeem_payment/static/img/usage_3_payment_line.png
  pos_loyalty_redeem_payment/static/src/js/PaymentScreen.esm.js
  pos_loyalty_redeem_payment/static/src/js/ResponsiveNumberPopup.esm.js
  pos_loyalty_redeem_payment/static/src/js/models.esm.js
  pos_loyalty_redeem_payment/static/src/scss/responsive_number_popup.scss
  pos_loyalty_redeem_payment/static/src/xml/Chrome.xml
  pos_loyalty_redeem_payment/static/src/xml/ResponsiveNumberPopup.xml
  pos_loyalty_redeem_payment/static/tests/tours/GiftCardRedeemPayment.tour.esm.js
  pos_loyalty_redeem_payment/static/tests/tours/helpers/ReceiptScreenTourMethods.js
  pos_loyalty_redeem_payment/tests/__init__.py
  pos_loyalty_redeem_payment/tests/test_frontend.py
  pos_loyalty_redeem_payment/views/loyalty_program_views.xml
  pos_loyalty_redeem_payment/views/pos_payment_method_views.xml
  setup/pos_loyalty_redeem_payment/odoo/addons/pos_loyalty_redeem_payment
  setup/pos_loyalty_redeem_payment/setup.py
Labels: approved, bot is merging ⏳

#1016 [14.0][FIX] pos_order_return: Returns and sales are allowed on the same order.
  pos_order_return/models/pos_order.py
  pos_order_return/tests/test_pos_order_return.py
Labels: approved, ready to merge, bot is merging ⏳
