Repository OCA/pos, pull requests merged in 2023-05, with the labels that each got.

#981 [14.0][FIX] pos_order_return: make returns properly
  pos_order_return/README.rst
  pos_order_return/models/pos_order.py
  pos_order_return/readme/ROADMAP.rst
  pos_order_return/static/description/index.html
  pos_order_return/tests/test_pos_order_return.py
Labels: bot is merging ⏳

#860 [16.0][ADD] new module ``pos_membership``
  pos_membership/README.rst
  pos_membership/__init__.py
  pos_membership/__manifest__.py
  pos_membership/demo/res_partner.xml
  pos_membership/i18n/fr.po
  pos_membership/models/__init__.py
  pos_membership/models/pos_session.py
  pos_membership/models/res_partner.py
  pos_membership/readme/CONTRIBUTORS.rst
  pos_membership/readme/CREDITS.rst
  pos_membership/readme/DESCRIPTION.rst
  pos_membership/static/description/pos_ui_partner_form.png
  pos_membership/static/description/pos_ui_partner_tree.png
  pos_membership/static/description/pos_warning_sell_membership_product.png
  pos_membership/static/src/css/pos_membership.css
  pos_membership/static/src/js/PaymentScreen.js
  pos_membership/static/src/xml/PartnerDetailsEdit.xml
  pos_membership/static/src/xml/PartnerLine.xml
  setup/pos_membership/odoo/addons/pos_membership
  setup/pos_membership/setup.py
Labels: approved, needs review, bot is merging ⏳, stale

#976 [14.0][MIG] pos_order_to_sale_order: Migration to 14.0
  pos_order_to_sale_order/README.rst
  pos_order_to_sale_order/__init__.py
  pos_order_to_sale_order/__manifest__.py
  pos_order_to_sale_order/i18n/es.po
  pos_order_to_sale_order/i18n/fr.po
  pos_order_to_sale_order/i18n/it.po
  pos_order_to_sale_order/i18n/pos_order_to_sale_order.pot
  pos_order_to_sale_order/i18n/pt_BR.po
  pos_order_to_sale_order/models/__init__.py
  pos_order_to_sale_order/models/pos_config.py
  pos_order_to_sale_order/models/sale_order.py
  pos_order_to_sale_order/models/sale_order_line.py
  pos_order_to_sale_order/readme/CONFIGURE.rst
  pos_order_to_sale_order/readme/CONTRIBUTORS.rst
  pos_order_to_sale_order/readme/DESCRIPTION.rst
  pos_order_to_sale_order/readme/USAGE.rst
  pos_order_to_sale_order/static/description/icon.png
  pos_order_to_sale_order/static/description/index.html
  pos_order_to_sale_order/static/description/pos_config_form.png
  pos_order_to_sale_order/static/description/pos_frontend_buttons.png
  pos_order_to_sale_order/static/description/pos_frontend_order.png
  pos_order_to_sale_order/static/src/css/pos.css
  pos_order_to_sale_order/static/src/js/CreateOrderButton.js
  pos_order_to_sale_order/static/src/js/CreateOrderPopup.js
  pos_order_to_sale_order/static/src/xml/CreateOrderButton.xml
  pos_order_to_sale_order/static/src/xml/CreateOrderPopup.xml
  pos_order_to_sale_order/views/assets.xml
  pos_order_to_sale_order/views/view_pos_config.xml
  setup/pos_order_to_sale_order/odoo/addons/pos_order_to_sale_order
  setup/pos_order_to_sale_order/setup.py
Labels: approved, bot is merging ⏳

#831 [14.0][NEW] Pos Show Clock
  pos_show_clock/README.rst
  pos_show_clock/__init__.py
  pos_show_clock/__manifest__.py
  pos_show_clock/readme/CONTRIBUTORS.rst
  pos_show_clock/readme/CREDITS.rst
  pos_show_clock/readme/DESCRIPTION.rst
  pos_show_clock/static/description/icon.png
  pos_show_clock/static/description/index.html
  pos_show_clock/static/description/printscreen.png
  pos_show_clock/static/src/css/pos.css
  pos_show_clock/static/src/js/ChromeWidgets/Clock.js
  pos_show_clock/static/src/xml/ChromeWidgets/Clock.xml
  pos_show_clock/views/pos_template.xml
  setup/pos_show_clock/odoo/addons/pos_show_clock
  setup/pos_show_clock/setup.py
Labels: approved, bot is merging ⏳

#998 [16.0][IMP] pos_stock_available_online
  pos_stock_available_online/__manifest__.py
  pos_stock_available_online/static/description/banner.png
  pos_stock_available_online/static/description/icon.png
Labels: bot is merging ⏳

#982 [14.0][BACKPORT] pos_partner_birthdate backport from 16.0 to 14.0
  pos_partner_birthdate/README.rst
  pos_partner_birthdate/__init__.py
  pos_partner_birthdate/__manifest__.py
  pos_partner_birthdate/i18n/pos_partner_birthdate.pot
  pos_partner_birthdate/readme/CONTRIBUTORS.rst
  pos_partner_birthdate/readme/DESCRIPTION.rst
  pos_partner_birthdate/static/description/icon.png
  pos_partner_birthdate/static/description/index.html
  pos_partner_birthdate/static/src/js/models.js
  pos_partner_birthdate/static/src/xml/ClientDetailsEdit.xml
  pos_partner_birthdate/views/assets.xml
  setup/pos_partner_birthdate/odoo/addons/pos_partner_birthdate
  setup/pos_partner_birthdate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#929 [MIG] [16.0] pos_payment_change
  pos_payment_change/README.rst
  pos_payment_change/__init__.py
  pos_payment_change/__manifest__.py
  pos_payment_change/i18n/de.po
  pos_payment_change/i18n/es.po
  pos_payment_change/i18n/fr.po
  pos_payment_change/i18n/pos_payment_change.pot
  pos_payment_change/models/__init__.py
  pos_payment_change/models/pos_config.py
  pos_payment_change/models/pos_order.py
  pos_payment_change/readme/CONFIGURE.rst
  pos_payment_change/readme/CONTRIBUTORS.rst
  pos_payment_change/readme/CREDITS.rst
  pos_payment_change/readme/DESCRIPTION.rst
  pos_payment_change/readme/USAGE.rst
  pos_payment_change/security/ir.model.access.csv
  pos_payment_change/static/description/icon.png
  pos_payment_change/static/description/index.html
  pos_payment_change/static/description/pos_config_form.png
  pos_payment_change/static/description/pos_order_form.png
  pos_payment_change/static/description/pos_order_tree.png
  pos_payment_change/static/description/pos_payment_change_wizard_form.png
  pos_payment_change/tests/__init__.py
  pos_payment_change/tests/test_module.py
  pos_payment_change/views/view_pos_config.xml
  pos_payment_change/views/view_pos_order.xml
  pos_payment_change/wizards/__init__.py
  pos_payment_change/wizards/pos_payment_change_wizard.py
  pos_payment_change/wizards/pos_payment_change_wizard_new_line.py
  pos_payment_change/wizards/pos_payment_change_wizard_old_line.py
  pos_payment_change/wizards/view_pos_payment_change_wizard.xml
  setup/pos_payment_change/odoo/addons/pos_payment_change
  setup/pos_payment_change/setup.py
Labels: approved, ready to merge, bot is merging ⏳
