Repository OCA/pos, pull requests merged in 2023-10, with the labels that each got.

#1062 [14.0][IMP] pos_pricelist_show_discount, rename exported fields
  pos_pricelist_show_discount/static/src/js/models.js
Labels: merged 🎉

#913 [13.0][NEW] pos_invoice_required
  pos_invoice_required/README.rst
  pos_invoice_required/__init__.py
  pos_invoice_required/__manifest__.py
  pos_invoice_required/models/__init__.py
  pos_invoice_required/models/pos_config.py
  pos_invoice_required/models/pos_order.py
  pos_invoice_required/readme/CONFIGURE.rst
  pos_invoice_required/readme/CONTRIBUTORS.rst
  pos_invoice_required/readme/DESCRIPTION.rst
  pos_invoice_required/static/description/icon.png
  pos_invoice_required/static/description/index.html
  pos_invoice_required/static/src/js/models.js
  pos_invoice_required/static/src/js/screens.js
  pos_invoice_required/static/src/xml/templates.xml
  pos_invoice_required/views/pos_config_view.xml
  setup/pos_invoice_required/odoo/addons/pos_invoice_required
  setup/pos_invoice_required/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1040 [16.0][ADD] pos_product_packaging_multi_barcode
  pos_product_packaging_multi_barcode/README.rst
  pos_product_packaging_multi_barcode/__init__.py
  pos_product_packaging_multi_barcode/__manifest__.py
  pos_product_packaging_multi_barcode/i18n/pos_product_packaging_multi_barcode.pot
  pos_product_packaging_multi_barcode/models/__init__.py
  pos_product_packaging_multi_barcode/models/pos_session.py
  pos_product_packaging_multi_barcode/models/product_packaging.py
  pos_product_packaging_multi_barcode/readme/CONTRIBUTORS.rst
  pos_product_packaging_multi_barcode/readme/CREDITS.rst
  pos_product_packaging_multi_barcode/readme/DESCRIPTION.rst
  pos_product_packaging_multi_barcode/readme/USAGE.rst
  pos_product_packaging_multi_barcode/static/description/icon.png
  pos_product_packaging_multi_barcode/static/description/index.html
  pos_product_packaging_multi_barcode/static/src/js/db.js
  setup/pos_product_packaging_multi_barcode/odoo/addons/pos_product_packaging_multi_barcode
  setup/pos_product_packaging_multi_barcode/setup.py
Labels: bot is merging ⏳

#1064 [14.0][FIX] pos_pricelist_show_discount: remove fragile demo data
  pos_pricelist_show_discount/__manifest__.py
  pos_pricelist_show_discount/demo/pos_config_demo.xml
  pos_pricelist_show_discount/demo/product_pricelist_demo.xml
  pos_pricelist_show_discount/tests/common.py
  pos_pricelist_show_discount/tests/test_pos_config_discount_pricelist.py
  pos_pricelist_show_discount/tests/test_pos_pricelist_show_discount.py
Labels: bot is merging ⏳

#1070 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pos_hide_cost_price_and_margin/__init__.py
  pos_report_session_summary/views/report_session_summary.xml
Labels: help wanted, needs review

#1069 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pos_empty_home/demo/pos_empty_home.xml
  pos_report_session_summary/views/report_session_summary.xml
  pos_reuse_pricelist/__init__.py
  pos_show_clock/views/pos_template.xml
Labels: help wanted, needs review
