Repository OCA/pos, pull requests merged in 2023-03, with the labels that each got.

#938 [15.0] [UPD] copier update: dotfiles
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#808 [15.0] [ADD] `pos_event_sale_session` : Sell events with sessions on the PoS
  pos_event_sale_session/README.rst
  pos_event_sale_session/__init__.py
  pos_event_sale_session/__manifest__.py
  pos_event_sale_session/i18n/fr.po
  pos_event_sale_session/models/__init__.py
  pos_event_sale_session/models/event_session.py
  pos_event_sale_session/models/pos_order_line.py
  pos_event_sale_session/readme/CONTRIBUTORS.rst
  pos_event_sale_session/readme/DESCRIPTION.rst
  pos_event_sale_session/reports/__init__.py
  pos_event_sale_session/reports/report_pos_order.py
  pos_event_sale_session/reports/report_pos_order.xml
  pos_event_sale_session/static/src/js/Popups/EventSelectorPopup/EventItem.js
  pos_event_sale_session/static/src/js/Popups/EventSelectorPopup/EventSelectorPopup.js
  pos_event_sale_session/static/src/js/Popups/EventTicketsPopup/EventTicketItem.js
  pos_event_sale_session/static/src/js/Popups/EventTicketsPopup/EventTicketsPopup.js
  pos_event_sale_session/static/src/js/Screens/EventRegistrationReceipt.js
  pos_event_sale_session/static/src/js/Screens/TicketScreen.js
  pos_event_sale_session/static/src/js/db.js
  pos_event_sale_session/static/src/js/models.js
  pos_event_sale_session/static/src/js/models/EventEvent.js
  pos_event_sale_session/static/src/js/models/EventSession.js
  pos_event_sale_session/static/src/js/models/Order.js
  pos_event_sale_session/static/src/js/models/Orderline.js
  pos_event_sale_session/static/src/js/models/PosModel.js
  pos_event_sale_session/static/src/xml/EventSelectorPopup/EventItem.xml
  pos_event_sale_session/static/src/xml/EventSelectorPopup/EventList.xml
  pos_event_sale_session/static/src/xml/EventSelectorPopup/EventSelectorPopup.xml
  pos_event_sale_session/static/src/xml/EventTicketsPopup/EventTicketList.xml
  pos_event_sale_session/static/src/xml/EventTicketsPopup/EventTicketsPopup.xml
  pos_event_sale_session/static/src/xml/ReceiptScreen/EventRegistrationReceipt.xml
  pos_event_sale_session/static/tests/tours/EventSaleSession.tour.js
  pos_event_sale_session/static/tests/tours/helpers/EventSelectorTourMethods.js
  pos_event_sale_session/tests/__init__.py
  pos_event_sale_session/tests/test_frontend.py
  pos_event_sale_session/views/event_session.xml
  setup/pos_event_sale_session/odoo/addons/pos_event_sale_session
  setup/pos_event_sale_session/setup.py
Labels: needs review, bot is merging ⏳, no stale

#810 [15.0] [ADD] `pos_sale_pos_event_sale_session`: Glue module between `pos_sale` and `pos_event_sale_session`
  pos_sale_pos_event_sale_session/README.rst
  pos_sale_pos_event_sale_session/__init__.py
  pos_sale_pos_event_sale_session/__manifest__.py
  pos_sale_pos_event_sale_session/models/__init__.py
  pos_sale_pos_event_sale_session/models/sale_order_line.py
  pos_sale_pos_event_sale_session/readme/CONTRIBUTORS.rst
  pos_sale_pos_event_sale_session/readme/DESCRIPTION.rst
  pos_sale_pos_event_sale_session/static/src/js/SaleOrderManagementScreen.js
  pos_sale_pos_event_sale_session/static/src/js/models.js
  setup/pos_sale_pos_event_sale_session/odoo/addons/pos_sale_pos_event_sale_session
  setup/pos_sale_pos_event_sale_session/setup.py
Labels: approved, needs review, bot is merging ⏳, no stale

#933 [16.0][MIG] pos_edit_order_line: Migration to 16.0
  pos_edit_order_line/README.rst
  pos_edit_order_line/__init__.py
  pos_edit_order_line/__manifest__.py
  pos_edit_order_line/i18n/it.po
  pos_edit_order_line/i18n/pos_edit_order_line.pot
  pos_edit_order_line/models/__init__.py
  pos_edit_order_line/models/pos_config.py
  pos_edit_order_line/models/res_config_settings.py
  pos_edit_order_line/readme/CONFIGURE.rst
  pos_edit_order_line/readme/CONTRIBUTORS.rst
  pos_edit_order_line/readme/DESCRIPTION.rst
  pos_edit_order_line/readme/HISTORY.rst
  pos_edit_order_line/static/description/icon.png
  pos_edit_order_line/static/description/index.html
  pos_edit_order_line/static/description/pos_edit_order_line.png
  pos_edit_order_line/static/src/css/pos.css
  pos_edit_order_line/static/src/js/EditOrderButton.js
  pos_edit_order_line/static/src/js/EditOrderLineInput.js
  pos_edit_order_line/static/src/js/EditOrderPopup.js
  pos_edit_order_line/static/src/xml/EditOrderButton.xml
  pos_edit_order_line/static/src/xml/EditOrderLineInput.xml
  pos_edit_order_line/static/src/xml/EditOrderPopup.xml
  pos_edit_order_line/views/res_config_settings_view.xml
  setup/pos_edit_order_line/odoo/addons/pos_edit_order_line
  setup/pos_edit_order_line/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#931 [16.0][MIG] pos_global_discount_in_line: Migration to 16.0
  pos_global_discount_in_line/README.rst
  pos_global_discount_in_line/__init__.py
  pos_global_discount_in_line/__manifest__.py
  pos_global_discount_in_line/i18n/it.po
  pos_global_discount_in_line/i18n/pos_global_discount_in_line.pot
  pos_global_discount_in_line/models/__init__.py
  pos_global_discount_in_line/models/pos_config.py
  pos_global_discount_in_line/models/res_config_settings.py
  pos_global_discount_in_line/readme/CONTRIBUTORS.rst
  pos_global_discount_in_line/readme/DESCRIPTION.rst
  pos_global_discount_in_line/readme/USAGE.rst
  pos_global_discount_in_line/static/description/icon.png
  pos_global_discount_in_line/static/description/index.html
  pos_global_discount_in_line/static/src/js/GlobalLineDiscount.js
  pos_global_discount_in_line/views/res_config_settings_views.xml
  setup/pos_global_discount_in_line/odoo/addons/pos_global_discount_in_line
  setup/pos_global_discount_in_line/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#947 [14.0][FIX] pos_margin: Frontend crash with pos_restaurant
  pos_margin/static/src/js/OrderWidget.js
Labels: bot is merging ⏳

#954 [IMP] pos_event_sale: Add hook to store currency_id in database for each existing pos_order_line before installation
  pos_event_sale/__init__.py
  pos_event_sale/__manifest__.py
  pos_event_sale/hooks.py
Labels: approved, bot is merging ⏳

#946 [15.0][MIG] pos_report_session_summary: Migration to 15.0
  pos_report_session_summary/README.rst
  pos_report_session_summary/__init__.py
  pos_report_session_summary/__manifest__.py
  pos_report_session_summary/i18n/ca.po
  pos_report_session_summary/i18n/ca_ES.po
  pos_report_session_summary/i18n/de.po
  pos_report_session_summary/i18n/es.po
  pos_report_session_summary/i18n/fr.po
  pos_report_session_summary/i18n/it.po
  pos_report_session_summary/i18n/pos_report_session_summary.pot
  pos_report_session_summary/i18n/pt.po
  pos_report_session_summary/readme/DESCRIPTION.rst
  pos_report_session_summary/readme/USAGE.rst
  pos_report_session_summary/static/description/icon.png
  pos_report_session_summary/static/description/index.html
  pos_report_session_summary/views/report_session_summary.xml
  pos_report_session_summary/views/session_summary_report.xml
  setup/pos_report_session_summary/odoo/addons/pos_report_session_summary
  setup/pos_report_session_summary/setup.py
Labels: approved, ready to merge, bot is merging ⏳
