Repository OCA/pos, pull requests merged in 2023-08, with the labels that each got.

#1035 [IMP] pos_order_to_sale_order: Improvement for the ability to use the result of sales order creation after inheritance
  pos_order_to_sale_order/static/src/js/CreateOrderPopup.js
Labels: bot is merging ⏳

#952 [ADD] pos_product_mergeable_line
  pos_product_mergeable_line/README.rst
  pos_product_mergeable_line/__init__.py
  pos_product_mergeable_line/__manifest__.py
  pos_product_mergeable_line/i18n/fr.po
  pos_product_mergeable_line/models/__init__.py
  pos_product_mergeable_line/models/product_template.py
  pos_product_mergeable_line/readme/CONTRIBUTORS.rst
  pos_product_mergeable_line/readme/DESCRIPTION.rst
  pos_product_mergeable_line/static/src/js/models.js
  pos_product_mergeable_line/views/templates.xml
  pos_product_mergeable_line/views/view_product_template.xml
  setup/pos_product_mergeable_line/odoo/addons/pos_product_mergeable_line
  setup/pos_product_mergeable_line/setup.py
Labels: bot is merging ⏳, stale

#1042 [16.0][REF] pos_order_to_sale_order: create method optimization
  pos_order_to_sale_order/models/sale_order.py
  pos_order_to_sale_order/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#979 [12.0][FIX] pos_tare - fix stack trace when tare by barecode
  pos_tare/static/src/js/screens.js
Labels: bot is merging ⏳, stale

#1036 [16.0][NEW] pos_order_to_sale_order_report: Add new module - download report after sale order creation from POS
  pos_order_to_sale_order_report/README.rst
  pos_order_to_sale_order_report/__init__.py
  pos_order_to_sale_order_report/__manifest__.py
  pos_order_to_sale_order_report/models/__init__.py
  pos_order_to_sale_order_report/models/pos_config.py
  pos_order_to_sale_order_report/models/res_config_settings.py
  pos_order_to_sale_order_report/readme/CONFIGURE.rst
  pos_order_to_sale_order_report/readme/CONTRIBUTORS.rst
  pos_order_to_sale_order_report/readme/DESCRIPTION.rst
  pos_order_to_sale_order_report/readme/USAGE.rst
  pos_order_to_sale_order_report/static/description/icon.png
  pos_order_to_sale_order_report/static/img/pos_config.png
  pos_order_to_sale_order_report/static/src/js/Popups/CreateOrderPopup.esm.js
  pos_order_to_sale_order_report/views/res_config_settings_view.xml
  setup/pos_order_to_sale_order_report/odoo/addons/pos_order_to_sale_order_report
  setup/pos_order_to_sale_order_report/setup.py
Labels: approved, bot is merging ⏳

#1031 [16.0][FIX] pos_partner_birthdate: partner birthdate field wasn't being saved from PoS
  pos_partner_birthdate/__manifest__.py
  pos_partner_birthdate/readme/CONTRIBUTORS.rst
  pos_partner_birthdate/static/src/js/ClientDetailsEdit.esm.js
  pos_partner_birthdate/static/src/xml/ClientDetailsEdit.xml
Labels: approved, ready to merge, bot is merging ⏳

#1032 [FIX] pos_customer_comment: fix bug with comment field on EditPartnerDetails screen
  pos_customer_comment/__manifest__.py
  pos_customer_comment/readme/CONTRIBUTORS.rst
  pos_customer_comment/static/src/js/PartnerDetailsEdit.esm.js
  pos_customer_comment/static/src/xml/PartnerDetailsEdit.xml
Labels: approved, bot is merging ⏳

#1044 [16.0][FIX] pos_order_remove_line: Trigger
  pos_order_remove_line/static/src/js/orderline.esm.js
Labels: approved, ready to merge, bot is merging ⏳
