Repository OCA/pos, pull requests merged in 2023-07, with the labels that each got.

#1003 [14.0][IMP] pos_session_pay_invoice: Set `target=new` on views
  pos_session_pay_invoice/wizard/cash_invoice_in.xml
  pos_session_pay_invoice/wizard/pos_box_cash_invoice_in.xml
  pos_session_pay_invoice/wizard/pos_box_cash_invoice_out.xml
Labels: approved, ready to merge, bot is merging ⏳

#1010 [15.0][MIG] pos_user_restriction: Migration to 15.0
  pos_user_restriction/README.rst
  pos_user_restriction/__init__.py
  pos_user_restriction/__manifest__.py
  pos_user_restriction/i18n/es.po
  pos_user_restriction/i18n/it.po
  pos_user_restriction/i18n/pos_user_restriction.pot
  pos_user_restriction/models/__init__.py
  pos_user_restriction/models/pos_config.py
  pos_user_restriction/models/pos_session.py
  pos_user_restriction/models/res_users.py
  pos_user_restriction/readme/CONFIGURE.rst
  pos_user_restriction/readme/CONTRIBUTORS.rst
  pos_user_restriction/readme/DESCRIPTION.rst
  pos_user_restriction/readme/ROADMAP.rst
  pos_user_restriction/security/ir.model.access.csv
  pos_user_restriction/security/pos_security.xml
  pos_user_restriction/static/description/icon.png
  pos_user_restriction/static/description/index.html
  pos_user_restriction/tests/__init__.py
  pos_user_restriction/tests/test_pos_user_restriction.py
  pos_user_restriction/views/point_of_sale_views.xml
  pos_user_restriction/views/pos_config_views.xml
  setup/pos_user_restriction/odoo/addons/pos_user_restriction
  setup/pos_user_restriction/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1025 [16.0][FIX] pos_order_to_sale_order
  pos_order_to_sale_order/static/src/js/CreateOrderButton.js
Labels: bot is merging ⏳

#939 [MIG][16.0] pos margin
  pos_margin/README.rst
  pos_margin/__init__.py
  pos_margin/__manifest__.py
  pos_margin/i18n/es.po
  pos_margin/models/__init__.py
  pos_margin/models/pos_config.py
  pos_margin/models/res_config_settings.py
  pos_margin/readme/CONFIGURE.rst
  pos_margin/readme/CONTRIBUTORS.rst
  pos_margin/readme/DESCRIPTION.rst
  pos_margin/readme/HISTORY.rst
  pos_margin/readme/ROADMAP.rst
  pos_margin/readme/USAGE.rst
  pos_margin/report/__init__.py
  pos_margin/report/pos_order_report.py
  pos_margin/static/description/icon.png
  pos_margin/static/description/index.html
  pos_margin/static/description/pos_config_form.png
  pos_margin/static/description/pos_config_setting.png
  pos_margin/static/description/pos_front_end.png
  pos_margin/static/description/pos_order_form.png
  pos_margin/static/src/css/pos_margin.css
  pos_margin/static/src/js/OrderSummaryMargin.esm.js
  pos_margin/static/src/js/models.esm.js
  pos_margin/static/src/xml/pos_margin.xml
  pos_margin/views/res_config_settings_view.xml
  pos_margin/views/view_pos_order.xml
  setup/pos_margin/odoo/addons/pos_margin
  setup/pos_margin/setup.py
Labels: bot is merging ⏳, stale

#1026 [FIX][16.0] pos_order_remove_line: clean toRefundLines when deleting a refunded orderline from remove-line-button
  pos_order_remove_line/static/src/js/orderline.esm.js
Labels: approved, bot is merging ⏳
