Repository OCA/pos, pull requests merged in 2023-09, with the labels that each got.

#859 [16.0][ADD] new module pos_discount_all
  pos_discount_all/README.rst
  pos_discount_all/__init__.py
  pos_discount_all/__manifest__.py
  pos_discount_all/demo/product_product.xml
  pos_discount_all/demo/res_groups.xml
  pos_discount_all/models/__init__.py
  pos_discount_all/models/pos_session.py
  pos_discount_all/models/product_template.py
  pos_discount_all/readme/CONFIGURE.rst
  pos_discount_all/readme/CONTRIBUTORS.rst
  pos_discount_all/readme/CREDITS.rst
  pos_discount_all/readme/DESCRIPTION.rst
  pos_discount_all/readme/DEVELOP.rst
  pos_discount_all/readme/USAGE.rst
  pos_discount_all/static/description/order_summary.png
  pos_discount_all/static/description/pos_receipt.png
  pos_discount_all/static/description/product_template_form.png
  pos_discount_all/static/src/js/models.js
  pos_discount_all/static/src/xml/OrderSummary.xml
  pos_discount_all/tests/__init__.py
  pos_discount_all/tests/test_module.py
  pos_discount_all/tests/tours/PosDiscountAllTour.tour.js
  pos_discount_all/views/view_product_template.xml
  setup/pos_discount_all/odoo/addons/pos_discount_all
  setup/pos_discount_all/setup.py
Labels: approved, bot is merging ⏳, stale

#1052 [14.0][FIX] pos_customer_display: set use_proxy=true
  pos_customer_display/static/src/js/models.js
Labels: bot is merging ⏳

#961 [ADD] pos_ticket_extra_company_info module.
  pos_ticket_extra_company_info/README.rst
  pos_ticket_extra_company_info/__init__.py
  pos_ticket_extra_company_info/__manifest__.py
  pos_ticket_extra_company_info/i18n/fr.po
  pos_ticket_extra_company_info/models/__init__.py
  pos_ticket_extra_company_info/models/pos_config.py
  pos_ticket_extra_company_info/readme/CONTRIBUTORS.rst
  pos_ticket_extra_company_info/readme/CREDITS.rst
  pos_ticket_extra_company_info/readme/DESCRIPTION.rst
  pos_ticket_extra_company_info/static/description/ticket_no_proxy_after.png
  pos_ticket_extra_company_info/static/description/ticket_no_proxy_before.png
  pos_ticket_extra_company_info/static/src/xml/pos_ticket_extra_company_info.xml
  pos_ticket_extra_company_info_l10n_fr/README.rst
  pos_ticket_extra_company_info_l10n_fr/__init__.py
  pos_ticket_extra_company_info_l10n_fr/__manifest__.py
  pos_ticket_extra_company_info_l10n_fr/i18n/fr.po
  pos_ticket_extra_company_info_l10n_fr/readme/CONTRIBUTORS.rst
  pos_ticket_extra_company_info_l10n_fr/readme/CREDITS.rst
  pos_ticket_extra_company_info_l10n_fr/readme/DESCRIPTION.rst
  pos_ticket_extra_company_info_l10n_fr/static/src/js/db.js
  pos_ticket_extra_company_info_l10n_fr/static/src/xml/pos_ticket_extra_company_info_l10n_fr.xml
  pos_ticket_extra_company_info_l10n_fr/views/templates.xml
  setup/pos_ticket_extra_company_info/odoo/addons/pos_ticket_extra_company_info
  setup/pos_ticket_extra_company_info/setup.py
  setup/pos_ticket_extra_company_info_l10n_fr/odoo/addons/pos_ticket_extra_company_info_l10n_fr
  setup/pos_ticket_extra_company_info_l10n_fr/setup.py
Labels: approved, bot is merging ⏳, stale

#1053 [ADD] pos_minimize_menu : new module to save place to display current ticket
  pos_discount_all/tests/test_module.py
  pos_minimize_menu/README.rst
  pos_minimize_menu/__init__.py
  pos_minimize_menu/__manifest__.py
  pos_minimize_menu/demo/pos_config.xml
  pos_minimize_menu/models/__init__.py
  pos_minimize_menu/models/pos_config.py
  pos_minimize_menu/models/res_config_settings.py
  pos_minimize_menu/readme/CONFIGURE.rst
  pos_minimize_menu/readme/CONTRIBUTORS.rst
  pos_minimize_menu/readme/DESCRIPTION.rst
  pos_minimize_menu/readme/DEVELOP.rst
  pos_minimize_menu/static/img/configure_important_buttons.png
  pos_minimize_menu/static/img/important_buttons_displayed.png
  pos_minimize_menu/static/img/with_module.png
  pos_minimize_menu/static/img/without_module.png
  pos_minimize_menu/static/src/js/ProductScreen.js
  pos_minimize_menu/static/src/xml/ProductScreen.xml
  pos_minimize_menu/views/view_res_config_settings.xml
  pos_order_to_sale_order/tests/test_module.py
  setup/pos_minimize_menu/odoo/addons/pos_minimize_menu
  setup/pos_minimize_menu/setup.py
Labels: approved, needs review, ready to merge, bot is merging ⏳

#977 [13.0][MIG] pos_user_restriction: Migration to 13.0
  pos_user_restriction/README.rst
  pos_user_restriction/__init__.py
  pos_user_restriction/__manifest__.py
  pos_user_restriction/i18n/es.po
  pos_user_restriction/i18n/it.po
  pos_user_restriction/i18n/pos_user_restriction.pot
  pos_user_restriction/models/__init__.py
  pos_user_restriction/models/pos_config.py
  pos_user_restriction/readme/CONFIGURE.rst
  pos_user_restriction/readme/CONTRIBUTORS.rst
  pos_user_restriction/readme/DESCRIPTION.rst
  pos_user_restriction/security/ir.model.access.csv
  pos_user_restriction/security/pos_security.xml
  pos_user_restriction/static/description/icon.png
  pos_user_restriction/static/description/index.html
  pos_user_restriction/tests/__init__.py
  pos_user_restriction/tests/test_pos_user_restriction.py
  pos_user_restriction/views/point_of_sale_views.xml
  pos_user_restriction/views/pos_config_views.xml
  setup/pos_user_restriction/odoo/addons/pos_user_restriction
  setup/pos_user_restriction/setup.py
Labels: bot is merging ⏳, stale

#1027 [16.0] [MIG] pos_partner_firstname
  pos_partner_firstname/README.rst
  pos_partner_firstname/__init__.py
  pos_partner_firstname/__manifest__.py
  pos_partner_firstname/i18n/ca.po
  pos_partner_firstname/i18n/ca_ES.po
  pos_partner_firstname/i18n/es.po
  pos_partner_firstname/i18n/fr_CH.po
  pos_partner_firstname/i18n/it.po
  pos_partner_firstname/i18n/pos_partner_firstname.pot
  pos_partner_firstname/models/__init__.py
  pos_partner_firstname/models/pos_session.py
  pos_partner_firstname/models/res_partner.py
  pos_partner_firstname/readme/CONTRIBUTORS.rst
  pos_partner_firstname/readme/DESCRIPTION.rst
  pos_partner_firstname/readme/ROADMAP.rst
  pos_partner_firstname/static/description/icon.png
  pos_partner_firstname/static/description/index.html
  pos_partner_firstname/static/src/js/PartnerDetailsEdit.js
  pos_partner_firstname/static/src/js/PartnerScreen.js
  pos_partner_firstname/static/src/xml/pos.xml
  setup/pos_partner_firstname/odoo/addons/pos_partner_firstname
  setup/pos_partner_firstname/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#945 [ADD] pos_margin_accounting_role
  pos_margin_accounting_role/README.rst
  pos_margin_accounting_role/__init__.py
  pos_margin_accounting_role/__manifest__.py
  pos_margin_accounting_role/readme/CONTRIBUTORS.rst
  pos_margin_accounting_role/readme/DESCRIPTION.rst
  pos_margin_accounting_role/views/view_pos_order.xml
  setup/pos_margin_accounting_role/odoo/addons/pos_margin_accounting_role
  setup/pos_margin_accounting_role/setup.py
Labels: bot is merging ⏳

#957 [16.0][MIG] pos_access_right
  pos_access_right/README.rst
  pos_access_right/__init__.py
  pos_access_right/__manifest__.py
  pos_access_right/demo/res_groups.xml
  pos_access_right/i18n/ar.po
  pos_access_right/i18n/ca.po
  pos_access_right/i18n/es.po
  pos_access_right/i18n/fr.po
  pos_access_right/i18n/it.po
  pos_access_right/i18n/pos_access_right.pot
  pos_access_right/i18n/ru.po
  pos_access_right/models/__init__.py
  pos_access_right/models/pos_config.py
  pos_access_right/models/pos_session.py
  pos_access_right/readme/CONFIGURE.rst
  pos_access_right/readme/CONTRIBUTORS.rst
  pos_access_right/readme/DESCRIPTION.rst
  pos_access_right/readme/USAGE.rst
  pos_access_right/security/res_groups.xml
  pos_access_right/static/description/admin_numpad.png
  pos_access_right/static/description/demo_error.png
  pos_access_right/static/description/demo_numpad.png
  pos_access_right/static/description/icon.png
  pos_access_right/static/description/index.html
  pos_access_right/static/description/new_groups.png
  pos_access_right/static/src/css/pos.css
  pos_access_right/static/src/js/ActionpadWidget.js
  pos_access_right/static/src/js/NumpadWidget.js
  pos_access_right/static/src/js/TicketScreen.js
  pos_access_right/static/src/xml/ActionpadWidget.xml
  pos_access_right/static/src/xml/NumpadWidget.xml
  pos_access_right/static/src/xml/TicketScreen.xml
  pos_access_right/tests/__init__.py
  pos_access_right/tests/test_pos_access_right.py
  setup/pos_access_right/odoo/addons/pos_access_right
  setup/pos_access_right/setup.py
Labels: approved, bot is merging ⏳
