Repository OCA/pos, pull requests merged in 2024-12, with the labels that each got.

#1214 [ADD] New module pos_receipt_vat_detail to display on receipt, the detail of the taxes. (Tax amount and base amount).
  pos_receipt_vat_detail/README.rst
  pos_receipt_vat_detail/__init__.py
  pos_receipt_vat_detail/__manifest__.py
  pos_receipt_vat_detail/i18n/fr.po
  pos_receipt_vat_detail/readme/CONTRIBUTORS.rst
  pos_receipt_vat_detail/readme/DESCRIPTION.rst
  pos_receipt_vat_detail/static/description/index.html
  pos_receipt_vat_detail/static/description/with_module.png
  pos_receipt_vat_detail/static/description/without_module.png
  pos_receipt_vat_detail/static/src/js/models.js
  pos_receipt_vat_detail/static/src/xml/order_receipt.xml
  setup/pos_receipt_vat_detail/odoo/addons/pos_receipt_vat_detail
  setup/pos_receipt_vat_detail/setup.py
Labels: bot is merging ⏳, stale

#1270 [16.0][ADD] pos_cash_control_override: New module
  pos_cash_control_override/README.rst
  pos_cash_control_override/__init__.py
  pos_cash_control_override/__manifest__.py
  pos_cash_control_override/models/__init__.py
  pos_cash_control_override/models/account_bank_statement_line.py
  pos_cash_control_override/models/pos_session.py
  pos_cash_control_override/readme/CONTEXT.md
  pos_cash_control_override/readme/CONTRIBUTORS.md
  pos_cash_control_override/readme/DESCRIPTION.md
  pos_cash_control_override/readme/ROADMAP.md
  pos_cash_control_override/readme/USAGE.md
  pos_cash_control_override/static/description/index.html
  pos_cash_control_override/tests/__init__.py
  pos_cash_control_override/tests/test_frontend.py
  setup/pos_cash_control_override/odoo/addons/pos_cash_control_override
  setup/pos_cash_control_override/setup.py
Labels: approved, bot is merging ⏳

#1218 [16.0][FIX] pos_payment_terminal: force use_proxy only if it's really needed
  pos_payment_terminal/i18n/fr.po
  pos_payment_terminal/i18n/pos_payment_terminal.pot
  pos_payment_terminal/static/src/js/models.js
Labels: bot is merging ⏳, stale

#1277 [17.0][ADD] pos_cash_control_extension: New module pos_cash_control_extension
  pos_cash_control_extension/README.rst
  pos_cash_control_extension/__init__.py
  pos_cash_control_extension/__manifest__.py
  pos_cash_control_extension/models/__init__.py
  pos_cash_control_extension/models/pos_session.py
  pos_cash_control_extension/pyproject.toml
  pos_cash_control_extension/readme/CONTRIBUTORS.md
  pos_cash_control_extension/readme/DESCRIPTION.md
  pos_cash_control_extension/static/description/icon.png
  pos_cash_control_extension/static/description/icon.svg
  pos_cash_control_extension/static/description/index.html
  pos_cash_control_extension/tests/__init__.py
  pos_cash_control_extension/tests/test_cash_control.py
Labels: approved, ready to merge, bot is merging ⏳

#1217 [16.0][ADD] pos_loyalty_exclude
  pos_loyalty_exclude/README.rst
  pos_loyalty_exclude/__init__.py
  pos_loyalty_exclude/__manifest__.py
  pos_loyalty_exclude/models/__init__.py
  pos_loyalty_exclude/models/loyalty_rule.py
  pos_loyalty_exclude/readme/CONTRIBUTORS.rst
  pos_loyalty_exclude/readme/DESCRIPTION.rst
  pos_loyalty_exclude/static/description/index.html
  pos_loyalty_exclude/static/src/tours/PosLoyaltyExcludeTour.esm.js
  pos_loyalty_exclude/tests/__init__.py
  pos_loyalty_exclude/tests/test_pos_loyalty_exclude.py
  setup/pos_loyalty_exclude/odoo/addons/pos_loyalty_exclude
  setup/pos_loyalty_exclude/setup.py
Labels: approved, ready to merge, bot is merging ⏳
