Repository OCA/pos, pull requests merged in 2024-01, with the labels that each got.

#1119 [14.0][FIX] pos_order_return: empty returns
  pos_order_return/models/pos_order.py
Labels: approved, bot is merging ⏳

#1117 [ADD] pos_partner_ref module
  pos_partner_ref/README.rst
  pos_partner_ref/__init__.py
  pos_partner_ref/__manifest__.py
  pos_partner_ref/models/__init__.py
  pos_partner_ref/models/pos_session.py
  pos_partner_ref/pyproject.toml
  pos_partner_ref/readme/CONTRIBUTORS.md
  pos_partner_ref/readme/DESCRIPTION.md
  pos_partner_ref/readme/newsfragments/.gitkeep
  pos_partner_ref/static/description/icon.png
  pos_partner_ref/static/description/index.html
  pos_partner_ref/static/src/js/ClientDetailsEdit.esm.js
  pos_partner_ref/static/src/js/PosDB.esm.js
  pos_partner_ref/static/src/xml/screens.xml
Labels: approved, ready to merge, bot is merging ⏳

#1118 [IMP] pos_partner_birthdate: Adding birthdate on partner list
  pos_partner_birthdate/README.rst
  pos_partner_birthdate/__manifest__.py
  pos_partner_birthdate/readme/CONTRIBUTORS.md
  pos_partner_birthdate/static/description/index.html
  pos_partner_birthdate/static/src/js/PartnerLine.esm.js
  pos_partner_birthdate/static/src/js/PosDB.esm.js
  pos_partner_birthdate/static/src/xml/screens.xml
Labels: approved, bot is merging ⏳

#1122 [16.0][FIX]pos_partner_firstname: Create and Update partner
  pos_partner_firstname/static/src/js/PartnerDetailsEdit.js
  pos_partner_firstname/static/src/xml/pos.xml
Labels: bot is merging ⏳

#1106 [17.0][MIG] pos_lot_selection: Migration to 17.0
  pos_lot_selection/README.rst
  pos_lot_selection/__init__.py
  pos_lot_selection/__manifest__.py
  pos_lot_selection/i18n/es.po
  pos_lot_selection/i18n/it.po
  pos_lot_selection/i18n/pos_lot_selection.pot
  pos_lot_selection/models/__init__.py
  pos_lot_selection/models/pos_session.py
  pos_lot_selection/models/product_product.py
  pos_lot_selection/models/stock_lot.py
  pos_lot_selection/pyproject.toml
  pos_lot_selection/readme/CONTRIBUTORS.md
  pos_lot_selection/readme/DESCRIPTION.md
  pos_lot_selection/readme/USAGE.md
  pos_lot_selection/static/description/icon.png
  pos_lot_selection/static/description/index.html
  pos_lot_selection/static/src/js/EditListPopup.esm.js
  pos_lot_selection/static/src/js/models.esm.js
  pos_lot_selection/static/src/xml/LotSelectorPopup.xml
  pos_lot_selection/static/tests/tours/LotSelection.tour.esm.js
  pos_lot_selection/tests/__init__.py
  pos_lot_selection/tests/test_frontend.py
Labels: approved, ready to merge, bot is merging ⏳

#1121 [16.0][ADD] pos_partner_sale_warning
  pos_partner_sale_warning/README.rst
  pos_partner_sale_warning/__init__.py
  pos_partner_sale_warning/__manifest__.py
  pos_partner_sale_warning/models/__init__.py
  pos_partner_sale_warning/models/pos_session.py
  pos_partner_sale_warning/readme/CONFIGURE.md
  pos_partner_sale_warning/readme/CONTEXT.md
  pos_partner_sale_warning/readme/CONTRIBUTORS.md
  pos_partner_sale_warning/readme/DESCRIPTION.md
  pos_partner_sale_warning/readme/ROADMAP.md
  pos_partner_sale_warning/readme/USAGE.md
  pos_partner_sale_warning/static/description/index.html
  pos_partner_sale_warning/static/src/js/PartnerListScreen.esm.js
  pos_partner_sale_warning/static/src/tests/tours/PosPartnerSaleWarning.esm.tour.js
  pos_partner_sale_warning/tests/__init__.py
  pos_partner_sale_warning/tests/test_pos_ui.py
  setup/pos_partner_sale_warning/odoo/addons/pos_partner_sale_warning
  setup/pos_partner_sale_warning/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1133 [FIX] eslint warnings
  pos_access_right/static/src/js/ActionpadWidget.js
  pos_access_right/static/src/js/NumpadWidget.js
  pos_access_right/static/src/js/TicketScreen.js
  pos_escpos_status/static/src/js/ProxyStatus.js
  pos_financial_risk/static/src/js/PaymentScreen.esm.js
  pos_global_discount_in_line/static/src/js/GlobalLineDiscount.js
  pos_lot_barcode/static/src/js/Popups/EditListPopup.js
  pos_lot_barcode/static/src/js/Screens/ProductScreen.js
  pos_lot_selection/static/src/js/EditListPopup.js
  pos_lot_selection/static/src/js/OrderWidget.js
  pos_lot_selection/static/src/js/ProductScreen.js
  pos_lot_selection/static/src/js/models.js
  pos_margin/static/src/js/models.esm.js
  pos_order_remove_line/static/src/js/orderline.esm.js
  pos_order_reorder/static/src/js/Screens/TicketScreen/ControlButtons/ReorderButton.esm.js
  pos_order_to_sale_order_delivery/static/src/js/Popups/ChooseDeliveryCarrierPopup.esm.js
  pos_order_to_sale_order_delivery/static/src/js/Popups/CreateOrderPopup.esm.js
  pos_order_to_sale_order_delivery/static/src/js/models.esm.js
  pos_order_to_sale_order_report/static/src/js/Popups/CreateOrderPopup.esm.js
  pos_order_to_sale_order_sale_financial_risk/static/src/js/CreateOrderPopup.esm.js
  pos_order_to_sale_order_sale_financial_risk/static/src/js/models.esm.js
  pos_partner_firstname/static/src/js/PartnerDetailsEdit.js
  pos_partner_firstname/static/src/js/PartnerScreen.js
  pos_payment_terminal/static/src/js/models.js
  pos_product_multi_barcode/static/src/js/db.js
  pos_product_quick_info/static/src/js/Screens/ProductScreen/ProductItem.js
  pos_sale_order_print/static/src/js/SaleOrderManagementScreen.esm.js
  pos_sale_order_print/static/src/js/pos_sale_order_print.esm.js
  pos_stock_available_online/static/src/js/Screens/ProductScreen/ProductItem.esm.js
  pos_stock_available_online/static/src/js/Screens/ProductScreen/ProductsWidget.esm.js
Labels: approved, bot is merging ⏳

#912 [16.0][ADD] pos_sale_product_config_no_variant
  pos_sale_product_config_no_variant/README.rst
  pos_sale_product_config_no_variant/__init__.py
  pos_sale_product_config_no_variant/__manifest__.py
  pos_sale_product_config_no_variant/models/__init__.py
  pos_sale_product_config_no_variant/models/pos_order.py
  pos_sale_product_config_no_variant/models/pos_order_line.py
  pos_sale_product_config_no_variant/models/pos_session.py
  pos_sale_product_config_no_variant/readme/CONTRIBUTORS.rst
  pos_sale_product_config_no_variant/readme/CREDITS.rst
  pos_sale_product_config_no_variant/readme/DESCRIPTION.rst
  pos_sale_product_config_no_variant/readme/USAGE.rst
  pos_sale_product_config_no_variant/static/description/icon.png
  pos_sale_product_config_no_variant/static/description/index.html
  pos_sale_product_config_no_variant/static/src/js/OrderLines.js
  pos_sale_product_config_no_variant/static/src/js/PosProductConfig.js
  pos_sale_product_config_no_variant/static/src/js/ProductScreen.js
  pos_sale_product_config_no_variant/views/pos_order_views.xml
  setup/pos_sale_product_config_no_variant/odoo/addons/pos_sale_product_config_no_variant
  setup/pos_sale_product_config_no_variant/setup.py
Labels: bot is merging ⏳, no stale

#996 [14.0][ADD] pos_return_voucher
  pos_return_voucher/README.rst
  pos_return_voucher/__init__.py
  pos_return_voucher/__manifest__.py
  pos_return_voucher/models/__init__.py
  pos_return_voucher/models/pos_config.py
  pos_return_voucher/models/pos_order.py
  pos_return_voucher/models/pos_payment.py
  pos_return_voucher/models/pos_payment_method.py
  pos_return_voucher/models/pos_return_voucher.py
  pos_return_voucher/readme/CONFIGURE.rst
  pos_return_voucher/readme/CONTRIBUTORS.rst
  pos_return_voucher/readme/DESCRIPTION.rst
  pos_return_voucher/readme/USAGE.rst
  pos_return_voucher/security/ir.model.access.csv
  pos_return_voucher/static/description/icon.png
  pos_return_voucher/static/description/index.html
  pos_return_voucher/static/description/order-mgmt-icon.png
  pos_return_voucher/static/description/pos-payment-emitted.png
  pos_return_voucher/static/description/pos-payment-validated.png
  pos_return_voucher/static/description/pos-return.png
  pos_return_voucher/static/description/pos-set-return-voucher.png
  pos_return_voucher/static/description/pos_return_voucher-config.png
  pos_return_voucher/static/description/pos_return_voucher-payment-config.png
  pos_return_voucher/static/description/pos_return_voucher-payment-method.png
  pos_return_voucher/static/src/js/PaymentScreen.js
  pos_return_voucher/static/src/js/ReceiptScreen.js
  pos_return_voucher/static/src/js/SetReturnVoucherPopup.js
  pos_return_voucher/static/src/js/models.js
  pos_return_voucher/static/src/xml/OrderReceipt.xml
  pos_return_voucher/static/src/xml/SetReturnVoucherPopup.xml
  pos_return_voucher/views/pos_config.xml
  pos_return_voucher/views/pos_order.xml
  pos_return_voucher/views/pos_payment.xml
  pos_return_voucher/views/pos_payment_method.xml
  pos_return_voucher/views/pos_return_voucher.xml
  pos_return_voucher/views/templates.xml
  setup/pos_return_voucher/odoo/addons/pos_return_voucher
  setup/pos_return_voucher/setup.py
Labels: approved, bot is merging ⏳

#1126 [17.0][MIG] pos_partner_firstname: Migration to 17.0
  pos_partner_firstname/README.rst
  pos_partner_firstname/__init__.py
  pos_partner_firstname/__manifest__.py
  pos_partner_firstname/i18n/ca.po
  pos_partner_firstname/i18n/ca_ES.po
  pos_partner_firstname/i18n/es.po
  pos_partner_firstname/i18n/fr.po
  pos_partner_firstname/i18n/fr_CH.po
  pos_partner_firstname/i18n/it.po
  pos_partner_firstname/i18n/pos_partner_firstname.pot
  pos_partner_firstname/models/__init__.py
  pos_partner_firstname/models/pos_config.py
  pos_partner_firstname/models/pos_session.py
  pos_partner_firstname/pyproject.toml
  pos_partner_firstname/readme/CONTRIBUTORS.md
  pos_partner_firstname/readme/DESCRIPTION.md
  pos_partner_firstname/readme/ROADMAP.md
  pos_partner_firstname/static/description/icon.png
  pos_partner_firstname/static/description/index.html
  pos_partner_firstname/static/src/app/PartnerDetailsEdit.esm.js
  pos_partner_firstname/static/src/app/PartnerDetailsEdit.scss
  pos_partner_firstname/static/src/app/PartnerDetailsEdit.xml
Labels: approved, bot is merging ⏳

#1105 [17.0][MIG] pos_lot_barcode: Migration to 17.0
  pos_lot_barcode/README.rst
  pos_lot_barcode/__init__.py
  pos_lot_barcode/__manifest__.py
  pos_lot_barcode/i18n/es.po
  pos_lot_barcode/i18n/it.po
  pos_lot_barcode/i18n/pos_lot_barcode.pot
  pos_lot_barcode/pyproject.toml
  pos_lot_barcode/readme/CONFIGURATION.rst
  pos_lot_barcode/readme/CONTRIBUTORS.md
  pos_lot_barcode/readme/DESCRIPTION.md
  pos_lot_barcode/security/ir.model.access.csv
  pos_lot_barcode/static/description/icon.png
  pos_lot_barcode/static/description/index.html
  pos_lot_barcode/static/src/js/Popups/EditListPopup.esm.js
  pos_lot_barcode/static/src/js/Popups/ErrorMultiLotBarcodePopup.esm.js
  pos_lot_barcode/static/src/js/Screens/ProductScreen.esm.js
  pos_lot_barcode/static/src/xml/Popups/ErrorMultiLotBarcodePopup.xml
  pos_lot_barcode/static/tests/tours/LotScanning.tour.esm.js
  pos_lot_barcode/tests/__init__.py
  pos_lot_barcode/tests/test_frontend.py
Labels: bot is merging ⏳

#1127 16.0 mig pos_to_weight_by_product_uom (from 12.0)
  pos_to_weight_by_product_uom/README.rst
  pos_to_weight_by_product_uom/__init__.py
  pos_to_weight_by_product_uom/__manifest__.py
  pos_to_weight_by_product_uom/hooks.py
  pos_to_weight_by_product_uom/i18n/ca.po
  pos_to_weight_by_product_uom/i18n/de.po
  pos_to_weight_by_product_uom/i18n/es.po
  pos_to_weight_by_product_uom/i18n/es_MX.po
  pos_to_weight_by_product_uom/i18n/fi.po
  pos_to_weight_by_product_uom/i18n/fr.po
  pos_to_weight_by_product_uom/i18n/fr_CH.po
  pos_to_weight_by_product_uom/i18n/hr.po
  pos_to_weight_by_product_uom/i18n/hr_HR.po
  pos_to_weight_by_product_uom/i18n/it.po
  pos_to_weight_by_product_uom/i18n/pos_to_weight_by_product_uom.pot
  pos_to_weight_by_product_uom/i18n/pt.po
  pos_to_weight_by_product_uom/i18n/pt_BR.po
  pos_to_weight_by_product_uom/i18n/ro.po
  pos_to_weight_by_product_uom/i18n/sl.po
  pos_to_weight_by_product_uom/i18n/tr_TR.po
  pos_to_weight_by_product_uom/i18n/vi_VN.po
  pos_to_weight_by_product_uom/i18n/zh_CN.po
  pos_to_weight_by_product_uom/migrations/16.0.1.0.0/pre-migration.py
  pos_to_weight_by_product_uom/models/__init__.py
  pos_to_weight_by_product_uom/models/product_product.py
  pos_to_weight_by_product_uom/models/product_template.py
  pos_to_weight_by_product_uom/models/uom_category.py
  pos_to_weight_by_product_uom/models/uom_uom.py
  pos_to_weight_by_product_uom/readme/CONFIGURE.rst
  pos_to_weight_by_product_uom/readme/CONTRIBUTORS.rst
  pos_to_weight_by_product_uom/readme/DESCRIPTION.rst
  pos_to_weight_by_product_uom/readme/USAGE.rst
  pos_to_weight_by_product_uom/static/description/index.html
  pos_to_weight_by_product_uom/static/description/product_form.png
  pos_to_weight_by_product_uom/static/description/uom_category_form.png
  pos_to_weight_by_product_uom/tests/__init__.py
  pos_to_weight_by_product_uom/tests/test_module.py
  pos_to_weight_by_product_uom/views/view_uom_category.xml
  pos_to_weight_by_product_uom/views/view_uom_uom.xml
  setup/pos_to_weight_by_product_uom/odoo/addons/pos_to_weight_by_product_uom
  setup/pos_to_weight_by_product_uom/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1144 [ADD] pos_product_packaging_container_deposit: Introduce new module in 16.0
  pos_product_packaging_container_deposit/README.rst
  pos_product_packaging_container_deposit/__init__.py
  pos_product_packaging_container_deposit/__manifest__.py
  pos_product_packaging_container_deposit/i18n/pos_product_packaging_container_deposit.pot
  pos_product_packaging_container_deposit/models/__init__.py
  pos_product_packaging_container_deposit/models/pos_order_line.py
  pos_product_packaging_container_deposit/models/pos_session.py
  pos_product_packaging_container_deposit/models/product_packaging.py
  pos_product_packaging_container_deposit/readme/CONTRIBUTORS.rst
  pos_product_packaging_container_deposit/readme/CREDITS.rst
  pos_product_packaging_container_deposit/readme/DESCRIPTION.rst
  pos_product_packaging_container_deposit/readme/USAGE.rst
  pos_product_packaging_container_deposit/static/description/icon.png
  pos_product_packaging_container_deposit/static/description/index.html
  pos_product_packaging_container_deposit/static/src/js/ProductScreen.esm.js
  pos_product_packaging_container_deposit/static/src/js/models.esm.js
  pos_product_packaging_container_deposit/tests/__init__.py
  pos_product_packaging_container_deposit/tests/test_deposit.py
  pos_product_packaging_container_deposit/tests/tours/TestDepostit.tour.js
  setup/pos_product_packaging_container_deposit/odoo/addons/pos_product_packaging_container_deposit
  setup/pos_product_packaging_container_deposit/setup.py
Labels: approved, bot is merging ⏳
