Repository OCA/pos, pull requests merged in 2024-04, with the labels that each got.

#1150 [16.0][FIX] pos_reset_search: TypeError on _clearSearch method.
  pos_reset_search/README.rst
  pos_reset_search/__manifest__.py
  pos_reset_search/readme/CONTRIBUTORS.rst
  pos_reset_search/static/description/index.html
  pos_reset_search/static/src/js/Screens/ProductScreen/ControlButtons/ProductsWidgetControlPanel.esm.js
  pos_reset_search/static/src/js/Screens/ProductScreen/ProductScreen.js
Labels: approved

#1038 [16.0][FIX] bug on printing coupons redeemed
  pos_loyalty_redeem_payment/models/pos_order.py
Labels: approved, needs review, ready to merge, bot is merging ⏳

#1176 [16.0][FIX] pos_payment_change: ondelete='cascade' for O2M fields
  pos_payment_change/wizards/pos_payment_change_wizard_new_line.py
  pos_payment_change/wizards/pos_payment_change_wizard_old_line.py
Labels: bot is merging ⏳

#1167 [16.0][ADD] pos_receipt_replace_user_by_trigram
  pos_receipt_replace_user_by_trigram/README.rst
  pos_receipt_replace_user_by_trigram/__init__.py
  pos_receipt_replace_user_by_trigram/__manifest__.py
  pos_receipt_replace_user_by_trigram/models/__init__.py
  pos_receipt_replace_user_by_trigram/models/pos_config.py
  pos_receipt_replace_user_by_trigram/models/pos_session.py
  pos_receipt_replace_user_by_trigram/models/res_config_settings.py
  pos_receipt_replace_user_by_trigram/models/res_partner.py
  pos_receipt_replace_user_by_trigram/readme/CONFIGURE.rst
  pos_receipt_replace_user_by_trigram/readme/CONTRIBUTORS.rst
  pos_receipt_replace_user_by_trigram/readme/DESCRIPTION.rst
  pos_receipt_replace_user_by_trigram/static/description/index.html
  pos_receipt_replace_user_by_trigram/static/img/pos_config.png
  pos_receipt_replace_user_by_trigram/static/img/pos_receipt.png
  pos_receipt_replace_user_by_trigram/static/src/js/models.js
  pos_receipt_replace_user_by_trigram/static/src/js/order_receipt.js
  pos_receipt_replace_user_by_trigram/static/src/xml/order_receipt.xml
  pos_receipt_replace_user_by_trigram/tests/__init__.py
  pos_receipt_replace_user_by_trigram/tests/test_get_trigram.py
  pos_receipt_replace_user_by_trigram/utils.py
  pos_receipt_replace_user_by_trigram/views/res_config_settings.xml
  pos_receipt_replace_user_by_trigram/views/res_users.xml
  pos_receipt_replace_user_by_trigram_hr/README.rst
  pos_receipt_replace_user_by_trigram_hr/__init__.py
  pos_receipt_replace_user_by_trigram_hr/__manifest__.py
  pos_receipt_replace_user_by_trigram_hr/models/__init__.py
  pos_receipt_replace_user_by_trigram_hr/models/hr_employee.py
  pos_receipt_replace_user_by_trigram_hr/models/pos_session.py
  pos_receipt_replace_user_by_trigram_hr/readme/CONTRIBUTORS.rst
  pos_receipt_replace_user_by_trigram_hr/readme/DESCRIPTION.rst
  pos_receipt_replace_user_by_trigram_hr/static/description/index.html
  setup/pos_receipt_replace_user_by_trigram/odoo/addons/pos_receipt_replace_user_by_trigram
  setup/pos_receipt_replace_user_by_trigram/setup.py
  setup/pos_receipt_replace_user_by_trigram_hr/odoo/addons/pos_receipt_replace_user_by_trigram_hr
  setup/pos_receipt_replace_user_by_trigram_hr/setup.py
Labels: bot is merging ⏳

#1179 [FIX] pos_lot_barcode: Use new logic for testing
  pos_lot_barcode/static/tests/tours/LotScanning.tour.esm.js
Labels: bot is merging ⏳

#1182 [16.0][ADD] pos_receipt_hide_info
  pos_receipt_hide_info/README.rst
  pos_receipt_hide_info/__init__.py
  pos_receipt_hide_info/__manifest__.py
  pos_receipt_hide_info/models/__init__.py
  pos_receipt_hide_info/models/pos_config.py
  pos_receipt_hide_info/models/res_config_settings.py
  pos_receipt_hide_info/readme/CONTRIBUTORS.rst
  pos_receipt_hide_info/readme/CREDITS.rst
  pos_receipt_hide_info/readme/DESCRIPTION.rst
  pos_receipt_hide_info/static/description/index.html
  pos_receipt_hide_info/static/src/js/order_receipt.js
  pos_receipt_hide_info/static/src/xml/order_receipt.xml
  pos_receipt_hide_info/views/res_config_settings.xml
  setup/pos_receipt_hide_info/odoo/addons/pos_receipt_hide_info
  setup/pos_receipt_hide_info/setup.py
Labels: approved, bot is merging ⏳

#1174 [16.0][ADD] pos_daily_sales_reports_category_only
  pos_daily_sales_reports_category_only/README.rst
  pos_daily_sales_reports_category_only/__init__.py
  pos_daily_sales_reports_category_only/__manifest__.py
  pos_daily_sales_reports_category_only/models/__init__.py
  pos_daily_sales_reports_category_only/models/pos_config.py
  pos_daily_sales_reports_category_only/models/pos_daily_sales_reports.py
  pos_daily_sales_reports_category_only/models/res_config_settings.py
  pos_daily_sales_reports_category_only/readme/CONTRIBUTORS.rst
  pos_daily_sales_reports_category_only/readme/CREDITS.rst
  pos_daily_sales_reports_category_only/readme/DESCRIPTION.rst
  pos_daily_sales_reports_category_only/static/description/index.html
  pos_daily_sales_reports_category_only/static/img/pos_config.png
  pos_daily_sales_reports_category_only/static/img/sample_report.png
  pos_daily_sales_reports_category_only/static/src/xml/SaleDetailsReport.xml
  pos_daily_sales_reports_category_only/tests/__init__.py
  pos_daily_sales_reports_category_only/tests/test_daily_sales_reports.py
  pos_daily_sales_reports_category_only/views/point_of_sale_view.xml
  pos_daily_sales_reports_category_only/views/res_config_settings.xml
  setup/pos_daily_sales_reports_category_only/odoo/addons/pos_daily_sales_reports_category_only
  setup/pos_daily_sales_reports_category_only/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1183 [14.0][IMP] pos_sale_order_load: configurable product load pop-up
  pos_sale_order_load/models/pos_config.py
  pos_sale_order_load/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  pos_sale_order_load/views/pos_config_views.xml
Labels: bot is merging ⏳
