Repository OCA/pos, pull requests merged in 2024-11, with the labels that each got.

#1146 [16.0] MIG: pos_price_to_weight (from 12.0)
  pos_price_to_weight/README.rst
  pos_price_to_weight/__init__.py
  pos_price_to_weight/__manifest__.py
  pos_price_to_weight/demo/barcode_rule.xml
  pos_price_to_weight/demo/product_product.xml
  pos_price_to_weight/i18n/ca.po
  pos_price_to_weight/i18n/es.po
  pos_price_to_weight/i18n/fr.po
  pos_price_to_weight/i18n/it.po
  pos_price_to_weight/i18n/pos_price_to_weight.pot
  pos_price_to_weight/models/__init__.py
  pos_price_to_weight/models/barcode_rule.py
  pos_price_to_weight/readme/CONFIGURE.rst
  pos_price_to_weight/readme/CONTRIBUTORS.rst
  pos_price_to_weight/readme/CREDITS.rst
  pos_price_to_weight/readme/DESCRIPTION.rst
  pos_price_to_weight/static/description/barcode_rule.png
  pos_price_to_weight/static/description/icon.png
  pos_price_to_weight/static/description/index.html
  pos_price_to_weight/static/description/pos_test_1.png
  pos_price_to_weight/static/description/pos_test_2.png
  pos_price_to_weight/static/src/js/ProductScreen.js
  setup/pos_price_to_weight/odoo/addons/pos_price_to_weight
  setup/pos_price_to_weight/setup.py
Labels: bot is merging ⏳, stale

#1132 [16.0] mig pos_ticket_extra_company_info_l10n_fr
  pos_ticket_extra_company_info_l10n_fr/README.rst
  pos_ticket_extra_company_info_l10n_fr/__init__.py
  pos_ticket_extra_company_info_l10n_fr/__manifest__.py
  pos_ticket_extra_company_info_l10n_fr/i18n/fr.po
  pos_ticket_extra_company_info_l10n_fr/i18n/it.po
  pos_ticket_extra_company_info_l10n_fr/i18n/pos_ticket_extra_company_info_l10n_fr.pot
  pos_ticket_extra_company_info_l10n_fr/models/__init__.py
  pos_ticket_extra_company_info_l10n_fr/models/pos_session.py
  pos_ticket_extra_company_info_l10n_fr/readme/CONTRIBUTORS.rst
  pos_ticket_extra_company_info_l10n_fr/readme/CREDITS.rst
  pos_ticket_extra_company_info_l10n_fr/readme/DESCRIPTION.rst
  pos_ticket_extra_company_info_l10n_fr/static/description/icon.png
  pos_ticket_extra_company_info_l10n_fr/static/description/index.html
  pos_ticket_extra_company_info_l10n_fr/static/description/pos_ticket.png
  pos_ticket_extra_company_info_l10n_fr/static/src/js/models.esm.js
  pos_ticket_extra_company_info_l10n_fr/static/src/xml/OrderReceipt.xml
  pos_ticket_extra_company_info_l10n_fr/views/templates.xml
  setup/pos_ticket_extra_company_info_l10n_fr/odoo/addons/pos_ticket_extra_company_info_l10n_fr
  setup/pos_ticket_extra_company_info_l10n_fr/setup.py
Labels: bot is merging ⏳, stale

#1195 [ADD] pos_order_copy
  pos_order_copy/README.rst
  pos_order_copy/__init__.py
  pos_order_copy/__manifest__.py
  pos_order_copy/models/__init__.py
  pos_order_copy/models/pos_order.py
  pos_order_copy/models/pos_session.py
  pos_order_copy/pyproject.toml
  pos_order_copy/readme/CONTRIBUTORS.md
  pos_order_copy/readme/DESCRIPTION.md
  pos_order_copy/static/description/icon.png
  pos_order_copy/static/description/index.html
  pos_order_copy/static/src/app/product_screen/CopyOrderButton.esm.js
  pos_order_copy/static/src/app/product_screen/CopyOrderButton.xml
  pos_order_copy/static/src/app/store/pos_store.esm.js
  pos_order_copy/static/src/app/ticket_screen/ticket_screen.esm.js
  pos_order_copy/static/src/app/ticket_screen/ticket_screen.xml
Labels: bot is merging ⏳, stale

#1241 [17.0][ADD] pos_partner_vat_required: New module pos_partner_vat_required
  pos_partner_vat_required/README.rst
  pos_partner_vat_required/__init__.py
  pos_partner_vat_required/__manifest__.py
  pos_partner_vat_required/i18n/ca_ES.po
  pos_partner_vat_required/i18n/es.po
  pos_partner_vat_required/pyproject.toml
  pos_partner_vat_required/readme/CONTRIBUTORS.md
  pos_partner_vat_required/readme/DESCRIPTION.md
  pos_partner_vat_required/static/description/icon.png
  pos_partner_vat_required/static/description/icon.svg
  pos_partner_vat_required/static/description/index.html
  pos_partner_vat_required/static/src/app/PartnerDetailsEdit.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#1247 [17.0][ADD] pos_partner_firstname_required: New module pos_partner_firstname_required
  pos_partner_firstname_required/README.rst
  pos_partner_firstname_required/__init__.py
  pos_partner_firstname_required/__manifest__.py
  pos_partner_firstname_required/i18n/ca_ES.po
  pos_partner_firstname_required/i18n/es.po
  pos_partner_firstname_required/pyproject.toml
  pos_partner_firstname_required/readme/CONTRIBUTORS.md
  pos_partner_firstname_required/readme/DESCRIPTION.md
  pos_partner_firstname_required/static/description/icon.png
  pos_partner_firstname_required/static/description/icon.svg
  pos_partner_firstname_required/static/description/index.html
  pos_partner_firstname_required/static/src/app/PartnerDetailsEdit.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#1246 [17.0][ADD] pos_partner_address_required: New module pos_partner_address_required
  pos_partner_address_required/README.rst
  pos_partner_address_required/__init__.py
  pos_partner_address_required/__manifest__.py
  pos_partner_address_required/i18n/ca_ES.po
  pos_partner_address_required/i18n/es.po
  pos_partner_address_required/pyproject.toml
  pos_partner_address_required/readme/CONTRIBUTORS.md
  pos_partner_address_required/readme/DESCRIPTION.md
  pos_partner_address_required/static/description/icon.png
  pos_partner_address_required/static/description/icon.svg
  pos_partner_address_required/static/description/index.html
  pos_partner_address_required/static/src/app/PartnerDetailsEdit.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#1210 [ADD] pos_receipt_usability : new module to improve the display of the receipt screen
  pos_receipt_usability/README.rst
  pos_receipt_usability/__init__.py
  pos_receipt_usability/__manifest__.py
  pos_receipt_usability/i18n/fr.po
  pos_receipt_usability/readme/CONTRIBUTORS.rst
  pos_receipt_usability/readme/DESCRIPTION.rst
  pos_receipt_usability/static/description/index.html
  pos_receipt_usability/static/description/with_module.png
  pos_receipt_usability/static/description/without_module.png
  pos_receipt_usability/static/src/css/pos_receipt_usability.scss
  pos_receipt_usability/static/src/xml/PaymentScreen.xml
  setup/pos_receipt_usability/odoo/addons/pos_receipt_usability
  setup/pos_receipt_usability/setup.py
Labels: bot is merging ⏳, stale

#1136 [ADD] pos_payment_usability : module to try to fix bad UX in payment PoS screen
  pos_payment_usability/README.rst
  pos_payment_usability/__init__.py
  pos_payment_usability/__manifest__.py
  pos_payment_usability/i18n/fr.po
  pos_payment_usability/readme/CONTRIBUTORS.rst
  pos_payment_usability/readme/DESCRIPTION.rst
  pos_payment_usability/static/description/with_module.png
  pos_payment_usability/static/description/without_module.png
  pos_payment_usability/static/src/css/pos_payment_usability.scss
  pos_payment_usability/static/src/xml/PaymentScreen.xml
  setup/pos_payment_usability/odoo/addons/pos_payment_usability
  setup/pos_payment_usability/setup.py
Labels: bot is merging ⏳, no stale
