Repository OCA/pos, pull requests merged in 2024-02, with the labels that each got.

#1142 [ADD] pos_sale_order_load: Importing sales orders at the POS
  pos_disable_pricelist_selection/models/pos_config.py
  pos_sale_order_load/README.rst
  pos_sale_order_load/__init__.py
  pos_sale_order_load/__manifest__.py
  pos_sale_order_load/i18n/pt_BR.po
  pos_sale_order_load/models/__init__.py
  pos_sale_order_load/models/crm_team.py
  pos_sale_order_load/models/pos_config.py
  pos_sale_order_load/models/pos_order.py
  pos_sale_order_load/models/pos_session.py
  pos_sale_order_load/models/res_config_settings.py
  pos_sale_order_load/models/sale_order.py
  pos_sale_order_load/models/stock_picking.py
  pos_sale_order_load/readme/CONTRIBUTORS.rst
  pos_sale_order_load/readme/CREDITS.rst
  pos_sale_order_load/readme/DESCRIPTION.rst
  pos_sale_order_load/readme/USAGE.rst
  pos_sale_order_load/static/description/icon.png
  pos_sale_order_load/static/description/index.html
  pos_sale_order_load/static/description/printscreen.png
  pos_sale_order_load/static/src/css/pos.css
  pos_sale_order_load/static/src/css/pos_sale.css
  pos_sale_order_load/static/src/js/OrderManagementScreen/MobileSaleOrderManagementScreen.js
  pos_sale_order_load/static/src/js/OrderManagementScreen/SaleOrderFetcher.js
  pos_sale_order_load/static/src/js/OrderManagementScreen/SaleOrderList.js
  pos_sale_order_load/static/src/js/OrderManagementScreen/SaleOrderManagementControlPanel.js
  pos_sale_order_load/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  pos_sale_order_load/static/src/js/OrderManagementScreen/SaleOrderRow.js
  pos_sale_order_load/static/src/js/ProductScreen.js
  pos_sale_order_load/static/src/js/SetSaleOrderButton.js
  pos_sale_order_load/static/src/js/models.js
  pos_sale_order_load/static/src/xml/OrderManagementScreen/MobileSaleOrderManagementScreen.xml
  pos_sale_order_load/static/src/xml/OrderManagementScreen/SaleOrderList.xml
  pos_sale_order_load/static/src/xml/OrderManagementScreen/SaleOrderManagementControlPanel.xml
  pos_sale_order_load/static/src/xml/OrderManagementScreen/SaleOrderManagementScreen.xml
  pos_sale_order_load/static/src/xml/OrderManagementScreen/SaleOrderRow.xml
  pos_sale_order_load/static/src/xml/ProductScreen/Orderline.xml
  pos_sale_order_load/static/src/xml/ReceiptScreen/OrderReceipt.xml
  pos_sale_order_load/static/src/xml/SetSaleOrderButton.xml
  pos_sale_order_load/static/tests/helpers/ProductScreenTourMethods.js
  pos_sale_order_load/static/tests/helpers/ReceiptScreenTourMethods.js
  pos_sale_order_load/static/tests/tours/pos_sale_tours.js
  pos_sale_order_load/tests/__init__.py
  pos_sale_order_load/tests/test_pos_and_sale_order.py
  pos_sale_order_load/tests/test_sale_order.py
  pos_sale_order_load/views/pos_assets_common.xml
  pos_sale_order_load/views/pos_config_views.xml
  pos_sale_order_load/views/pos_order_views.xml
  pos_sale_order_load/views/sale_order_views.xml
  pos_sale_order_load/views/stock_template.xml
  setup/pos_sale_order_load/odoo/addons/pos_sale_order_load
  setup/pos_sale_order_load/setup.py
Labels: approved, bot is merging ⏳

#1116 [DOC]Appropriate readm for v16
  pos_payment_change/readme/CONFIGURE.rst
Labels: bot is merging ⏳

#1141 [17.0][ADD] pos_partner_second_lastname
  pos_partner_firstname/static/src/app/PartnerDetailsEdit.esm.js
  pos_partner_second_lastname/README.rst
  pos_partner_second_lastname/__init__.py
  pos_partner_second_lastname/__manifest__.py
  pos_partner_second_lastname/models/__init__.py
  pos_partner_second_lastname/models/pos_session.py
  pos_partner_second_lastname/pyproject.toml
  pos_partner_second_lastname/readme/CONTRIBUTORS.md
  pos_partner_second_lastname/readme/DESCRIPTION.md
  pos_partner_second_lastname/static/description/icon.png
  pos_partner_second_lastname/static/description/index.html
  pos_partner_second_lastname/static/src/app/PartnerDetailsEdit.esm.js
  pos_partner_second_lastname/static/src/app/PartnerDetailsEdit.xml
Labels: approved, ready to merge, bot is merging ⏳

#1153 [IMP] pos_partner_firstname: set name invisible instead of readonly when is_company=False
  pos_partner_firstname/static/src/xml/pos.xml
Labels: approved, ready to merge, bot is merging ⏳

#1156 [17.0][IMP] pos_partner_firstname: set name invisible instead of readonly w…
  pos_partner_firstname/static/src/app/PartnerDetailsEdit.xml
Labels: approved, bot is merging ⏳

#1123 [ADD] pos_lot_expiry
  pos_product_expiry/README.rst
  pos_product_expiry/__init__.py
  pos_product_expiry/__manifest__.py
  pos_product_expiry/models/__init__.py
  pos_product_expiry/models/pos_config.py
  pos_product_expiry/models/pos_session.py
  pos_product_expiry/models/res_config_settings.py
  pos_product_expiry/models/stock_lot.py
  pos_product_expiry/pyproject.toml
  pos_product_expiry/readme/CONTRIBUTORS.md
  pos_product_expiry/readme/DESCRIPTION.md
  pos_product_expiry/static/description/icon.png
  pos_product_expiry/static/description/index.html
  pos_product_expiry/static/src/js/app/models.esm.js
  pos_product_expiry/static/tests/tours/ProductExpiry.tour.esm.js
  pos_product_expiry/tests/__init__.py
  pos_product_expiry/tests/test_frontend.py
  pos_product_expiry/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1066 [14.0][IMP] pos_no_cash_bank_statement: bank statement name generation
  pos_no_cash_bank_statement/models/pos_session.py
Labels: bot is merging ⏳
