Repository OCA/pos, pull requests merged in 2024-08, with the labels that each got.

#1221 [16.0][MIG] pos_customer_tree_view_vat: Migration to 16.0
  pos_customer_tree_view_vat/README.rst
  pos_customer_tree_view_vat/__init__.py
  pos_customer_tree_view_vat/__manifest__.py
  pos_customer_tree_view_vat/i18n/es.po
  pos_customer_tree_view_vat/i18n/it.po
  pos_customer_tree_view_vat/i18n/pos_customer_tree_view_vat.pot
  pos_customer_tree_view_vat/readme/CONTRIBUTORS.rst
  pos_customer_tree_view_vat/readme/CREDITS.rst
  pos_customer_tree_view_vat/readme/DESCRIPTION.rst
  pos_customer_tree_view_vat/static/description/icon.png
  pos_customer_tree_view_vat/static/description/index.html
  pos_customer_tree_view_vat/static/description/printscreen.png
  pos_customer_tree_view_vat/static/src/xml/partner_line.xml
  pos_customer_tree_view_vat/static/src/xml/partner_list_screen.xml
  setup/pos_customer_tree_view_vat/odoo/addons/pos_customer_tree_view_vat
  setup/pos_customer_tree_view_vat/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1180 [16.0] pos_membership_extension : change membership category
  pos_membership_extension/static/src/js/models.js
Labels: bot is merging ⏳, stale

#1155 [16.0][MIG] pos_payment_restriction: Migration to 16.0
  pos_payment_restriction/README.rst
  pos_payment_restriction/__init__.py
  pos_payment_restriction/__manifest__.py
  pos_payment_restriction/models/__init__.py
  pos_payment_restriction/models/pos_config.py
  pos_payment_restriction/models/res_config_settings.py
  pos_payment_restriction/readme/CONTRIBUTORS.rst
  pos_payment_restriction/readme/DESCRIPTION.rst
  pos_payment_restriction/readme/HISTORY.rst
  pos_payment_restriction/readme/USAGE.rst
  pos_payment_restriction/static/description/icon.png
  pos_payment_restriction/static/description/index.html
  pos_payment_restriction/static/src/js/PaymentScreen.js
  pos_payment_restriction/views/pos_config.xml
  pos_payment_restriction/views/pos_payment_restriction.xml
  pos_payment_restriction/views/res_config_settings.xml
  setup/pos_payment_restriction/odoo/addons/pos_payment_restriction
  setup/pos_payment_restriction/setup.py
Labels: bot is merging ⏳, stale

#1229 [16.0][MIG] pos_report_session_summary: Migration to version 16.0
  pos_report_session_summary/README.rst
  pos_report_session_summary/__init__.py
  pos_report_session_summary/__manifest__.py
  pos_report_session_summary/i18n/ca.po
  pos_report_session_summary/i18n/ca_ES.po
  pos_report_session_summary/i18n/de.po
  pos_report_session_summary/i18n/es.po
  pos_report_session_summary/i18n/fr.po
  pos_report_session_summary/i18n/it.po
  pos_report_session_summary/i18n/pos_report_session_summary.pot
  pos_report_session_summary/i18n/pt.po
  pos_report_session_summary/readme/DESCRIPTION.rst
  pos_report_session_summary/readme/ROADMAP.rst
  pos_report_session_summary/readme/USAGE.rst
  pos_report_session_summary/static/description/icon.png
  pos_report_session_summary/static/description/index.html
  pos_report_session_summary/views/report_session_summary.xml
  pos_report_session_summary/views/session_summary_report.xml
  setup/pos_report_session_summary/odoo/addons/pos_report_session_summary
  setup/pos_report_session_summary/setup.py
Labels: bot is merging ⏳
