Repository OCA/pos, pull requests merged in 2024-07, with the labels that each got.

#1181 [16.0][IMP] pos_product_label: improve print_product_labels
  pos_product_label/README.rst
  pos_product_label/models/pos_session.py
  pos_product_label/readme/CONTRIBUTORS.rst
  pos_product_label/static/description/index.html
Labels: approved, bot is merging ⏳

#1197 [16][UPD] pos_receipt_replace_user_by_trigram_hr: enable auto_install
  pos_receipt_replace_user_by_trigram_hr/__manifest__.py
  pos_receipt_replace_user_by_trigram_hr/static/description/index.html
Labels: bot is merging ⏳

#1203 [12.0] Replace 'Camptocamp SA' with 'Camptocamp'
  pos_remove_pos_category/__manifest__.py
Labels: bot is merging ⏳

#1158 [16.0][ADD] pos_screen_element_custom_size
  pos_screen_element_custom_size/README.rst
  pos_screen_element_custom_size/__init__.py
  pos_screen_element_custom_size/__manifest__.py
  pos_screen_element_custom_size/models/__init__.py
  pos_screen_element_custom_size/models/pos_config.py
  pos_screen_element_custom_size/models/res_config_settings.py
  pos_screen_element_custom_size/readme/CONFIGURE.md
  pos_screen_element_custom_size/readme/CONTEXT.md
  pos_screen_element_custom_size/readme/DESCRIPTION.md
  pos_screen_element_custom_size/readme/ROADMAP.md
  pos_screen_element_custom_size/readme/USAGE.md
  pos_screen_element_custom_size/static/description/index.html
  pos_screen_element_custom_size/static/src/xml/ProductItem.xml
  pos_screen_element_custom_size/static/src/xml/ProductsWidget.xml
  pos_screen_element_custom_size/views/res_config_settings_views.xml
  setup/pos_screen_element_custom_size/odoo/addons/pos_screen_element_custom_size
  setup/pos_screen_element_custom_size/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1173 [16.0][MIG] pos_hide_banknote_button: Migration to 16.0 (from 12.0)
  pos_hide_banknote_button/README.rst
  pos_hide_banknote_button/__init__.py
  pos_hide_banknote_button/__manifest__.py
  pos_hide_banknote_button/readme/CONTRIBUTORS.rst
  pos_hide_banknote_button/readme/DESCRIPTION.rst
  pos_hide_banknote_button/static/description/after.png
  pos_hide_banknote_button/static/description/before.png
  pos_hide_banknote_button/static/description/icon.png
  pos_hide_banknote_button/static/description/index.html
  pos_hide_banknote_button/static/src/scss/pos_hide_banknote_button.scss
  setup/pos_hide_banknote_button/odoo/addons/pos_hide_banknote_button
  setup/pos_hide_banknote_button/setup.py
Labels: bot is merging ⏳

#1148 [16.0][MIG] pos_timeout: Migration to 16.0
  pos_timeout/README.rst
  pos_timeout/__init__.py
  pos_timeout/__manifest__.py
  pos_timeout/i18n/ca.po
  pos_timeout/i18n/es.po
  pos_timeout/i18n/fr.po
  pos_timeout/i18n/hr_HR.po
  pos_timeout/i18n/it.po
  pos_timeout/i18n/nl_NL.po
  pos_timeout/i18n/pos_timeout.pot
  pos_timeout/models/__init__.py
  pos_timeout/models/pos_config.py
  pos_timeout/models/res_config_settings.py
  pos_timeout/readme/CONFIGURE.rst
  pos_timeout/readme/CONTRIBUTORS.rst
  pos_timeout/readme/CREDITS.rst
  pos_timeout/readme/DESCRIPTION.rst
  pos_timeout/static/description/icon.png
  pos_timeout/static/description/index.html
  pos_timeout/static/description/pos_config.png
  pos_timeout/static/src/js/models.js
  pos_timeout/views/res_config_settings.xml
  setup/pos_timeout/odoo/addons/pos_timeout
  setup/pos_timeout/setup.py
Labels: approved, needs review, bot is merging ⏳

#1215 [14.0][FIX] pos_sale_order_load: Fix ValueError Invalid field 'pos_allow_negative_qty'
  pos_sale_order_load/tests/test_sale_order.py
Labels: bot is merging ⏳

#1222 [16.0][ADD] pos_config_logo: New module
  pos_config_logo/README.rst
  pos_config_logo/__init__.py
  pos_config_logo/__manifest__.py
  pos_config_logo/models/__init__.py
  pos_config_logo/models/pos_config.py
  pos_config_logo/models/res_config_settings.py
  pos_config_logo/readme/CONFIGURE.md
  pos_config_logo/readme/CONTEXT.md
  pos_config_logo/readme/CONTRIBUTORS.md
  pos_config_logo/readme/DESCRIPTION.md
  pos_config_logo/readme/USAGE.md
  pos_config_logo/static/description/index.html
  pos_config_logo/static/src/js/models.esm.js
  pos_config_logo/views/res_config_settings_views.xml
  setup/pos_config_logo/odoo/addons/pos_config_logo
  setup/pos_config_logo/setup.py
Labels: approved, bot is merging ⏳

#1225 [16.0][MIG] pos_supplierinfo_search: Migration to version 16.0
  pos_supplierinfo_search/README.rst
  pos_supplierinfo_search/__init__.py
  pos_supplierinfo_search/__manifest__.py
  pos_supplierinfo_search/i18n/es.po
  pos_supplierinfo_search/i18n/it.po
  pos_supplierinfo_search/i18n/pos_supplierinfo_search.pot
  pos_supplierinfo_search/models/__init__.py
  pos_supplierinfo_search/models/pos_session.py
  pos_supplierinfo_search/models/product.py
  pos_supplierinfo_search/readme/CONTRIBUTORS.rst
  pos_supplierinfo_search/readme/DESCRIPTION.rst
  pos_supplierinfo_search/readme/USAGE.rst
  pos_supplierinfo_search/static/description/icon.png
  pos_supplierinfo_search/static/description/index.html
  pos_supplierinfo_search/static/src/js/db.js
  setup/pos_supplierinfo_search/odoo/addons/pos_supplierinfo_search
  setup/pos_supplierinfo_search/setup.py
Labels: approved, merged 🎉

#1223 [14.0][MIG] pos_config_logo: Migration to 14.0
  pos_config_logo/README.rst
  pos_config_logo/__init__.py
  pos_config_logo/__manifest__.py
  pos_config_logo/models/__init__.py
  pos_config_logo/models/pos_config.py
  pos_config_logo/readme/CONFIGURE.md
  pos_config_logo/readme/CONTEXT.md
  pos_config_logo/readme/CONTRIBUTORS.md
  pos_config_logo/readme/DESCRIPTION.md
  pos_config_logo/readme/USAGE.md
  pos_config_logo/static/description/index.html
  pos_config_logo/static/src/js/models.js
  pos_config_logo/views/assets.xml
  pos_config_logo/views/pos_config_views.xml
  setup/pos_config_logo/odoo/addons/pos_config_logo
  setup/pos_config_logo/setup.py
Labels: approved, bot is merging ⏳
