Repository OCA/pos, pull requests merged in 2025-02, with the labels that each got.

#1278 [16.0][ADD] pos_container_deposit
  pos_container_deposit/README.rst
  pos_container_deposit/__init__.py
  pos_container_deposit/__manifest__.py
  pos_container_deposit/demo/product_product.xml
  pos_container_deposit/i18n/nl.po
  pos_container_deposit/models/__init__.py
  pos_container_deposit/models/pos_session.py
  pos_container_deposit/models/product_product.py
  pos_container_deposit/models/product_template.py
  pos_container_deposit/readme/CONFIGURE.rst
  pos_container_deposit/readme/CONTEXT.rst
  pos_container_deposit/readme/CONTRIBUTORS.rst
  pos_container_deposit/readme/DESCRIPTION.rst
  pos_container_deposit/readme/USAGE.rst
  pos_container_deposit/static/description/index.html
  pos_container_deposit/static/src/js/components.js
  pos_container_deposit/static/src/js/models.js
  pos_container_deposit/static/tests/tours/pos_container_deposit_tour.js
  pos_container_deposit/tests/__init__.py
  pos_container_deposit/tests/test_pos_container_deposit.py
  pos_container_deposit/tests/test_pos_container_deposit_frontend.py
  pos_container_deposit/views/product_template.xml
  pos_ticket_extra_company_info_l10n_fr/static/src/js/models.esm.js
  setup/pos_container_deposit/odoo/addons/pos_container_deposit
  setup/pos_container_deposit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1316 16.0 fix eslint remove warning
  pos_bypass_global_discount/static/src/tours/PosBypassGlobalDiscount.esm.js
  pos_customer_comment/static/src/xml/PartnerLine.xml
  pos_daily_sales_reports_category_only/tests/test_daily_sales_reports.py
  pos_daily_sales_reports_category_only/views/point_of_sale_view.xml
  pos_default_partner/tests/test_pos_default_partner.py
  pos_loyalty_exclude/static/src/tours/PosLoyaltyExcludeTour.esm.js
  pos_membership/static/src/xml/PartnerLine.xml
  pos_order_to_sale_order/static/tests/tours/PosOrderToSaleOrderTour.esm.js
  pos_partner_firstname/static/src/xml/pos.xml
  pos_partner_location_abstract/static/src/js/PartnerMapEdit.esm.js
  pos_partner_location_google_map/static/src/js/PartnerMapGoogleEdit.esm.js
  pos_picking_delayed/tests/test_module.py
  pos_product_display_default_code/tests/test_load_params_product.py
  pos_product_packaging_container_deposit/static/src/js/models.esm.js
  pos_sale_product_config_no_variant/static/src/js/OrderLines.js
  pos_sale_product_config_no_variant/static/src/js/PosProductConfig.js
  pos_stock_available_online/models/pos_config.py
Labels: bot is merging ⏳

#1319 [FIX] pos_stock_available_online: prevent ensure_one() error, if we write on many items. (for exemple many quants)
  pos_stock_available_online/models/stock_notifier_pos_mixin.py
Labels: bot is merging ⏳

#1318 [16.0][FIX] pos_order_to_sale_order: recompute taxes
  pos_order_to_sale_order/models/sale_order.py
Labels: approved, bot is merging ⏳
