Repository OCA/pos, pull requests merged in 2025-04, with the labels that each got.

#1258 [16.0][ADD] pos_auto_invoice
  pos_auto_invoice/README.rst
  pos_auto_invoice/__init__.py
  pos_auto_invoice/__manifest__.py
  pos_auto_invoice/i18n/pos_auto_invoice.pot
  pos_auto_invoice/models/__init__.py
  pos_auto_invoice/models/pos_config.py
  pos_auto_invoice/models/res_config_settings.py
  pos_auto_invoice/readme/CONFIGURE.rst
  pos_auto_invoice/readme/CONTRIBUTORS.rst
  pos_auto_invoice/readme/DESCRIPTION.rst
  pos_auto_invoice/static/description/index.html
  pos_auto_invoice/static/src/js/models.esm.js
  pos_auto_invoice/views/res_config_settings_view.xml
  setup/pos_auto_invoice/odoo/addons/pos_auto_invoice
  setup/pos_auto_invoice/setup.py
Labels: approved, bot is merging ⏳, stale

#1346 [18.0][ADD] pos_barcode_rule_priced_with_change_rate
  pos_barcode_rule_priced_with_change_rate/README.rst
  pos_barcode_rule_priced_with_change_rate/__init__.py
  pos_barcode_rule_priced_with_change_rate/__manifest__.py
  pos_barcode_rule_priced_with_change_rate/i18n/fr.po
  pos_barcode_rule_priced_with_change_rate/i18n/pos_barcode_rule_priced_with_change_rate.pot
  pos_barcode_rule_priced_with_change_rate/models/__init__.py
  pos_barcode_rule_priced_with_change_rate/models/barcode_rule.py
  pos_barcode_rule_priced_with_change_rate/models/pos_config.py
  pos_barcode_rule_priced_with_change_rate/models/res_config_settings.py
  pos_barcode_rule_priced_with_change_rate/pyproject.toml
  pos_barcode_rule_priced_with_change_rate/readme/CONTRIBUTORS.md
  pos_barcode_rule_priced_with_change_rate/readme/CREDITS.md
  pos_barcode_rule_priced_with_change_rate/readme/DESCRIPTION.md
  pos_barcode_rule_priced_with_change_rate/static/description/index.html
  pos_barcode_rule_priced_with_change_rate/static/src/overrides/components/product_screen/product_screen.esm.js
  pos_barcode_rule_priced_with_change_rate/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#1337 [18.0][MIG] pos_lot_barcode: Migration to 18.0.
  pos_lot_barcode/README.rst
  pos_lot_barcode/__init__.py
  pos_lot_barcode/__manifest__.py
  pos_lot_barcode/i18n/es.po
  pos_lot_barcode/i18n/fr.po
  pos_lot_barcode/i18n/it.po
  pos_lot_barcode/i18n/pos_lot_barcode.pot
  pos_lot_barcode/pyproject.toml
  pos_lot_barcode/readme/CONFIGURATION.rst
  pos_lot_barcode/readme/CONTRIBUTORS.md
  pos_lot_barcode/readme/DESCRIPTION.md
  pos_lot_barcode/security/ir.model.access.csv
  pos_lot_barcode/static/description/icon.png
  pos_lot_barcode/static/description/index.html
  pos_lot_barcode/static/src/js/Popups/EditListPopup.esm.js
  pos_lot_barcode/static/src/js/Screens/ProductScreen.esm.js
  pos_lot_barcode/static/tests/tours/LotScanning.tour.esm.js
  pos_lot_barcode/tests/__init__.py
  pos_lot_barcode/tests/test_frontend.py
Labels: needs review, bot is merging ⏳

#1352 [18.0][MIG] pos_display_total_quantity: Migration to 18.0
  pos_display_total_quantity/README.rst
  pos_display_total_quantity/__init__.py
  pos_display_total_quantity/__manifest__.py
  pos_display_total_quantity/i18n/fr.po
  pos_display_total_quantity/i18n/fr_CH.po
  pos_display_total_quantity/i18n/pos_display_total_quantity.pot
  pos_display_total_quantity/pyproject.toml
  pos_display_total_quantity/readme/CONTRIBUTORS.md
  pos_display_total_quantity/readme/CREDITS.md
  pos_display_total_quantity/readme/DESCRIPTION.md
  pos_display_total_quantity/static/description/icon.png
  pos_display_total_quantity/static/description/index.html
  pos_display_total_quantity/static/src/js/overrides/components/order_widget/order_widget.esm.js
  pos_display_total_quantity/static/src/xml/pos_display_total_quantity.xml
  pos_display_total_quantity/static/tests/tours/DisplayTotal.tour.esm.js
  pos_display_total_quantity/tests/__init__.py
  pos_display_total_quantity/tests/test_frontend.py
Labels: approved, ready to merge, bot is merging ⏳

#1353 [18.0][MIG] pos_display_order_number: Migration to 18.0
  pos_display_order_number/README.rst
  pos_display_order_number/__init__.py
  pos_display_order_number/__manifest__.py
  pos_display_order_number/i18n/fr.po
  pos_display_order_number/i18n/fr_CH.po
  pos_display_order_number/i18n/pos_display_order_number.pot
  pos_display_order_number/pyproject.toml
  pos_display_order_number/readme/CONTRIBUTORS.md
  pos_display_order_number/readme/CREDITS.md
  pos_display_order_number/readme/DESCRIPTION.md
  pos_display_order_number/static/description/icon.png
  pos_display_order_number/static/description/index.html
  pos_display_order_number/static/src/js/overrides/components/order_widget/order_widget.esm.js
  pos_display_order_number/static/src/xml/pos_display_order_number.xml
  pos_display_order_number/static/tests/tours/DisplayOrderNumber.tour.esm.js
  pos_display_order_number/tests/__init__.py
  pos_display_order_number/tests/test_frontend.py
Labels: bot is merging ⏳

#1365 [ADD] pos_partner_vat_valid: New module pos_partner_vat_valid
  pos_partner_vat_valid/README.rst
  pos_partner_vat_valid/__init__.py
  pos_partner_vat_valid/__manifest__.py
  pos_partner_vat_valid/i18n/ca.po
  pos_partner_vat_valid/i18n/es.po
  pos_partner_vat_valid/models/__init__.py
  pos_partner_vat_valid/models/res_partner.py
  pos_partner_vat_valid/pyproject.toml
  pos_partner_vat_valid/readme/CONTRIBUTORS.md
  pos_partner_vat_valid/readme/DESCRIPTION.md
  pos_partner_vat_valid/static/description/icon.png
  pos_partner_vat_valid/static/description/icon.svg
  pos_partner_vat_valid/static/description/index.html
  pos_partner_vat_valid/static/src/app/PartnerDetailsEdit.esm.js
  pos_partner_vat_valid/tests/__init__.py
  pos_partner_vat_valid/tests/test_verify_vat.py
Labels: approved, bot is merging ⏳

#1309 [17.0][MIG] pos_margin
  pos_margin/README.rst
  pos_margin/__init__.py
  pos_margin/__manifest__.py
  pos_margin/i18n/es.po
  pos_margin/i18n/it.po
  pos_margin/i18n/pos_margin.pot
  pos_margin/models/__init__.py
  pos_margin/models/pos_config.py
  pos_margin/models/res_config_settings.py
  pos_margin/pyproject.toml
  pos_margin/readme/CONFIGURE.md
  pos_margin/readme/CONTRIBUTORS.md
  pos_margin/readme/DESCRIPTION.md
  pos_margin/readme/HISTORY.md
  pos_margin/readme/ROADMAP.md
  pos_margin/readme/USAGE.md
  pos_margin/report/__init__.py
  pos_margin/report/pos_order_report.py
  pos_margin/static/description/icon.png
  pos_margin/static/description/index.html
  pos_margin/static/description/pos_config_form.png
  pos_margin/static/description/pos_config_setting.png
  pos_margin/static/description/pos_front_end.png
  pos_margin/static/description/pos_order_form.png
  pos_margin/static/src/css/pos_margin.css
  pos_margin/static/src/js/OrderSummaryMargin.esm.js
  pos_margin/static/src/js/models.esm.js
  pos_margin/static/src/xml/pos_margin.xml
  pos_margin/views/res_config_settings_view.xml
  pos_margin/views/view_pos_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#1368 [16.0][FIX]pos_access_right: change deleteOrder to _onDeleteOrder
  pos_access_right/static/src/js/TicketScreen.js
Labels: approved, bot is merging ⏳

#1367 [16.0][ADD]pos_hr_access_right
  pos_hr_access_right/README.rst
  pos_hr_access_right/__init__.py
  pos_hr_access_right/__manifest__.py
  pos_hr_access_right/models/__init__.py
  pos_hr_access_right/models/pos_session.py
  pos_hr_access_right/readme/CONFIGURE.rst
  pos_hr_access_right/readme/CONTRIBUTORS.rst
  pos_hr_access_right/readme/DESCRIPTION.rst
  pos_hr_access_right/readme/USAGE.rst
  pos_hr_access_right/static/description/icon.png
  pos_hr_access_right/static/description/index.html
  pos_hr_access_right/static/src/js/ActionpadWidget.js
  pos_hr_access_right/static/src/js/NumpadWidget.js
  pos_hr_access_right/static/src/js/TicketScreen.js
  pos_hr_access_right/tests/__init__.py
  pos_hr_access_right/tests/test_pos_hr_access_right.py
  setup/pos_hr_access_right/odoo/addons/pos_hr_access_right
  setup/pos_hr_access_right/setup.py
Labels: approved, bot is merging ⏳

#1370 [16.0][FIX]pos_hr_access_right: Error when delete order
  pos_hr_access_right/static/src/js/TicketScreen.js
Labels: approved, bot is merging ⏳
