Repository OCA/pos, pull requests merged in 2025-09, with the labels that each got.

#1129 [17.0] [ADD] pos_order_split_invoice
  pos_order_split_invoice/README.rst
  pos_order_split_invoice/__init__.py
  pos_order_split_invoice/__manifest__.py
  pos_order_split_invoice/models/__init__.py
  pos_order_split_invoice/models/account_move.py
  pos_order_split_invoice/models/pos_order.py
  pos_order_split_invoice/models/pos_order_line.py
  pos_order_split_invoice/models/pos_session.py
  pos_order_split_invoice/models/product_pricelist.py
  pos_order_split_invoice/pyproject.toml
  pos_order_split_invoice/readme/CONFIGURE.md
  pos_order_split_invoice/readme/CONTRIBUTORS.md
  pos_order_split_invoice/readme/DESCRIPTION.md
  pos_order_split_invoice/readme/USAGE.md
  pos_order_split_invoice/static/description/icon.png
  pos_order_split_invoice/static/description/index.html
  pos_order_split_invoice/static/src/app/store/pos_store.esm.js
  pos_order_split_invoice/static/src/generic_components/product_card.esm.js
  pos_order_split_invoice/static/src/generic_components/product_card.xml
  pos_order_split_invoice/static/src/models/order.esm.js
  pos_order_split_invoice/static/src/models/order_line.esm.js
  pos_order_split_invoice/static/src/models/product.esm.js
  pos_order_split_invoice/static/src/screens/product_screen/product_list.xml
  pos_order_split_invoice/static/tests/tours/TestSplitInvoice.esm.js
  pos_order_split_invoice/tests/__init__.py
  pos_order_split_invoice/tests/test_frontend.py
  pos_order_split_invoice/views/account_move.xml
  pos_order_split_invoice/views/pos_order.xml
  pos_order_split_invoice/views/pos_session.xml
  pos_order_split_invoice/views/product_pricelist.xml
  pos_user_restriction/tests/test_hacks.py
Labels: bot is merging ⏳, stale

#1280 [17.0][ADD] pos_session_sequence: New module pos_session_sequence
  pos_session_sequence/README.rst
  pos_session_sequence/__init__.py
  pos_session_sequence/__manifest__.py
  pos_session_sequence/demo/pos_session_sequence.xml
  pos_session_sequence/i18n/ca.po
  pos_session_sequence/i18n/es.po
  pos_session_sequence/models/__init__.py
  pos_session_sequence/models/pos_config.py
  pos_session_sequence/models/pos_session.py
  pos_session_sequence/models/res_config_settings.py
  pos_session_sequence/pyproject.toml
  pos_session_sequence/readme/CONTRIBUTORS.md
  pos_session_sequence/readme/DESCRIPTION.md
  pos_session_sequence/readme/USAGE.md
  pos_session_sequence/static/description/icon.png
  pos_session_sequence/static/description/icon.svg
  pos_session_sequence/static/description/index.html
  pos_session_sequence/tests/__init__.py
  pos_session_sequence/tests/test_pos_session_sequence.py
  pos_session_sequence/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1383 [17.0][MIG] pos_partner_sale_warning
  pos_partner_sale_warning/README.rst
  pos_partner_sale_warning/__init__.py
  pos_partner_sale_warning/__manifest__.py
  pos_partner_sale_warning/i18n/es.po
  pos_partner_sale_warning/i18n/it.po
  pos_partner_sale_warning/i18n/pos_partner_sale_warning.pot
  pos_partner_sale_warning/models/__init__.py
  pos_partner_sale_warning/models/pos_session.py
  pos_partner_sale_warning/pyproject.toml
  pos_partner_sale_warning/readme/CONFIGURE.md
  pos_partner_sale_warning/readme/CONTEXT.md
  pos_partner_sale_warning/readme/CONTRIBUTORS.md
  pos_partner_sale_warning/readme/DESCRIPTION.md
  pos_partner_sale_warning/readme/ROADMAP.md
  pos_partner_sale_warning/readme/USAGE.md
  pos_partner_sale_warning/static/description/icon.png
  pos_partner_sale_warning/static/description/index.html
  pos_partner_sale_warning/static/src/js/PartnerListScreen.esm.js
  pos_partner_sale_warning/static/src/tests/tours/PosPartnerSaleWarning.esm.js
  pos_partner_sale_warning/tests/__init__.py
  pos_partner_sale_warning/tests/test_pos_ui.py
Labels: approved, ready to merge, bot is merging ⏳

#1265 [ADD] pos_category_complete_name new module
  pos_category_complete_name/README.rst
  pos_category_complete_name/__init__.py
  pos_category_complete_name/__manifest__.py
  pos_category_complete_name/i18n/fr.po
  pos_category_complete_name/models/__init__.py
  pos_category_complete_name/models/pos_category.py
  pos_category_complete_name/readme/CONTRIBUTORS.rst
  pos_category_complete_name/readme/DESCRIPTION.rst
  pos_category_complete_name/static/description/index.html
  pos_category_complete_name/tests/__init__.py
  pos_category_complete_name/tests/test_pos_category_complete_name.py
  setup/pos_category_complete_name/odoo/addons/pos_category_complete_name
  setup/pos_category_complete_name/setup.py
Labels: bot is merging ⏳
