Repository OCA/pos, pull requests merged in 2025-01, with the labels that each got.

#1250 [16.0][FIX] pos_stock_available_online: stock move updates
  pos_stock_available_online/models/__init__.py
  pos_stock_available_online/models/stock_move.py
  pos_stock_available_online/models/stock_notifier_pos_mixin.py
  pos_stock_available_online/models/stock_quant.py
Labels: approved, bot is merging ⏳

#1281 [16.0][FIX] pos_product_multi_barcode: incoherent data
  pos_product_multi_barcode/static/src/js/db.js
Labels: approved, ready to merge, bot is merging ⏳

#1285 [16.0][FIX] pos_stock_available_online: warehouse to notify
  pos_stock_available_online/models/stock_notifier_pos_mixin.py
Labels: approved, bot is merging ⏳

#1228 [ADD] new module pos_payment_description to see payment details in pos.order tree view
  pos_payment_description/README.rst
  pos_payment_description/__init__.py
  pos_payment_description/__manifest__.py
  pos_payment_description/i18n/fr.po
  pos_payment_description/models/__init__.py
  pos_payment_description/models/pos_order.py
  pos_payment_description/readme/CONTRIBUTORS.rst
  pos_payment_description/readme/DESCRIPTION.rst
  pos_payment_description/static/description/index.html
  pos_payment_description/static/description/pos_order_tree.png
  pos_payment_description/views/view_pos_order.xml
  setup/pos_payment_description/odoo/addons/pos_payment_description
  setup/pos_payment_description/setup.py
Labels: bot is merging ⏳, stale

#1235 [16.0][Add] pos_product_pricelist_alternative
  pos_product_pricelist_alternative/README.rst
  pos_product_pricelist_alternative/__init__.py
  pos_product_pricelist_alternative/__manifest__.py
  pos_product_pricelist_alternative/models/__init__.py
  pos_product_pricelist_alternative/models/pos_session.py
  pos_product_pricelist_alternative/readme/CONTRIBUTORS.rst
  pos_product_pricelist_alternative/readme/DESCRIPTION.rst
  pos_product_pricelist_alternative/static/description/index.html
  pos_product_pricelist_alternative/static/src/models.js
  setup/pos_product_pricelist_alternative/odoo/addons/pos_product_pricelist_alternative
  setup/pos_product_pricelist_alternative/setup.py
Labels: approved, bot is merging ⏳
